namespace itsppisapi.SaveDtos
{
    public class PTS006SaveDto
    {
        public decimal T_DAY { get; set; }
        public decimal T_YEAR { get; set; }
        public decimal T_MONTH { get; set; }
        public decimal T_VERSION { get; set; }
        public decimal T_USER_ID { get; set; }
        public decimal T_PWR_CONSP_AB { get; set; }
        public decimal T_PWR_CONSP_ACT { get; set; }
        public decimal T_PWR_CONSP_AMM { get; set; }
        public decimal T_PWR_CONSP_AMMSTRG { get; set; }
        public decimal T_PWR_CONSP_UPHS { get; set; }
        public decimal T_PWR_CONSP_CPP { get; set; }
        public decimal T_PWR_CONSP_DMP { get; set; }
        public decimal T_PWR_CONSP_EDG { get; set; }
        public decimal T_PWR_CONSP_ETP { get; set; }
        public decimal T_PWR_CONSP_FIRE { get; set; }
        public decimal T_PWR_CONSP_HOUSING { get; set; }
        public decimal T_PWR_CONSP_IAC_SPG { get; set; }
        public decimal T_PWR_CONSP_KSR { get; set; }
        public decimal T_PWR_CONSP_UCT { get; set; }
        public decimal T_PWR_CONSP_UREA { get; set; }
        public decimal T_PWR_CONSP_WPT { get; set; }
        public decimal T_PWR_TFR_NE { get; set; }
        public decimal T_PWR_GEN_GT1 { get; set; }
        public decimal T_PWR_GEN_GT2 { get; set; }
        public decimal T_PWR_PRCHSD { get; set; }
        public decimal T_PWR_RAW_PUMPS { get; set; }
        public decimal T_SELF_PWR_CONSP_GP2 { get; set; }
        public decimal T_PRCHSD_PWR_CONSP_GP2 { get; set; }
        public decimal T_TOT_PWR_GEN { get; set; }
        public decimal T_PWR_SPG_CONSP { get; set; }
        public decimal T_PWR_OFFSITE_CONSP { get; set; }
        public decimal T_LOSS_GEN_PWR { get; set; }
        public decimal T_PWR_CONSP_IAC_OFFSITE { get; set; }
        public decimal T_PWR_CONSP_U11 { get; set; }
        public decimal T_PWR_CONSP_U21 { get; set; }
        public decimal T_TOT_PWR_AVAIL { get; set; }
        public decimal T_TOT_EBUS_CONSP { get; set; }
        public decimal T_TOT_NEBUS_CONSP { get; set; }
        public decimal T_PWR_CONSP_BLDG_STRTS { get; set; }
        public decimal T_PWR_ALLOC_IA_GP2 { get; set; }
        public decimal T_PWR_CONSP_AMMSTRG_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_UPHS_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_ETP_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_FIRE_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_CONST_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_HOUSING_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_KSR_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_BLDG_STRTS_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_RSEB_GPII { get; set; }
        public decimal T_PWR_CONSP_NAP_STRG { get; set; }
        public decimal T_PWR_CONSP_NAP_HANDLG_CPP { get; set; }
        public decimal T_PWR_CONSP_NAP_HANDLG_AB { get; set; }
        public decimal T_PWR_CONSP_NAP_HANDLG_AMM { get; set; }
        public decimal T_PWR_CONSP_NAP_STRG_UNIT2 { get; set; }
        public decimal T_PWR_CONSP_DMP_UNIT2 { get; set; }
        public decimal T_PWR_TFR_EBUS { get; set; }
        public decimal T_PUR_PWR_CONSP_WPT { get; set; }
        public decimal T_PUR_PWR_CONSP_WPT_UNIT1 { get; set; }
        public decimal T_PUR_PWR_CONSP_WPT_UNIT2 { get; set; }
        public decimal T_NEBUS_CONSP_UNIT2 { get; set; }
        public decimal T_GEN_PWR_CONSP_KSR_UNIT1 { get; set; }
        public decimal T_GEN_PWR_CONSP_KSR_UNIT2 { get; set; }
        public decimal T_PUR_PWR_CONSP_BAGG_UNIT1 { get; set; }
        public decimal T_PUR_PWR_CONSP_BAGG_UNIT2 { get; set; }
        public decimal T_PUR_PWR_CONSP_RW { get; set; }
        public decimal T_PUR_PWR_CONSP_DMP { get; set; }
        public decimal T_PUR_PWR_CONSP_ETP_UNIT1 { get; set; }
        public decimal T_PUR_PWR_CONSP_ETP_UNIT2 { get; set; }
        public decimal T_PUR_PWR_CONSP_ACT { get; set; }
        public decimal T_PUR_PWR_CONSP_UCT { get; set; }
        public decimal T_PUR_PWR_CONSP_IAC { get; set; }
        public decimal T_PUR_PWR_CONSP_DMP_UNIT2 { get; set; }
        public decimal T_PUR_PWR_CONSP_IA_UNIT2 { get; set; }
        public decimal T_PUR_PWR_CONSP_DMP_UNIT1 { get; set; }
        public decimal T_PUR_PWR_ALLOC_DMP_UNIT2 { get; set; }
        public decimal T_GEN_PWR_CONSP_REVAMP_UNIT1 { get; set; }
        public decimal T_PUR_PWR_CONSP_SSP { get; set; }
        public decimal T_IEX_PURCHASED { get; set; }
        public decimal T_PUR_POWER_TOTAL { get; set; }
        public decimal T_PUR_PWR_CONST_CFG3 { get; set; }
        public decimal T_GEN_PWR_EXPORTT_GP3 { get; set; }
        public decimal T_PUR_PWR_EXPORTT_GP3 { get; set; }
        public decimal T_PWR_CONSP_HOUSING_UNIT3 { get; set; }
        public decimal T_PWR_CONSP_BLDG_STRTS_UNIT3 { get; set; }
        public decimal T_PWR_ALLOC_GP3_GP1 { get; set; }
        public decimal T_PWR_IMPORTF_GT3 { get; set; }
        public decimal T_PWR_ALLOC_GP3_GP2 { get; set; }
        public decimal T_PRCHSD_PWR_CONSP_GP3 { get; set; }
        public decimal T_PWR_CONSP_UPHS_UNIT3 { get; set; }
    }
}