namespace itsppisapi.Dtos
{
    public class PTS227SaveDto
    {
        public decimal T_YEAR { get; set; }
        public decimal T_IDENTITY { get; set; }
        public decimal T_VERSION { get; set; }
        public decimal T_USER_ID { get; set; }

        public decimal T_CPP_PROD { get; set; }
        public decimal T_CPP_DRW_FR_GP1 { get; set; }
        public decimal T_CPP_GN_EDG_GP2 { get; set; }
        public decimal T_PWR_TOT_AVL { get; set; }
        public decimal T_PWR_RUN_HRS { get; set; }
        public decimal T_CPP_CONSP_AM2_PLT { get; set; }
        public decimal T_CPP_CONSP_AM2_BL_GRS { get; set; }
        public decimal T_CPP_CONSP_AM2_BL_NET { get; set; }
        public decimal T_CPP_CONSP_AM2_BL_NON_PLT { get; set; }
        public decimal T_CPP_CONSP_AM2_NP_TRF_LOS { get; set; }
        public decimal T_CPP_OTH_AC_NG312 { get; set; }
        public decimal T_CPP_OTH_UPS_NG601A { get; set; }
        public decimal T_CPP_OTH_UPS_NG601B { get; set; }
        public decimal T_CPP_AV_UPS { get; set; }
        public decimal T_CPP_NP_ETP { get; set; }
        public decimal T_CPP_NP_BAT_CHG { get; set; }
        public decimal T_CPP_NP_STOT { get; set; }
        public decimal T_CPP_RMH_PORT { get; set; }
        public decimal T_CPP_1901_NP_STOT { get; set; }
        public decimal T_CPP_1901_GTOT { get; set; }
        public decimal T_CPP_ALLOC_NAP { get; set; }
        public decimal T_CPP_CONSP_AM2_RMH { get; set; }
        public decimal T_CPP_CONSP_AM2_STRG { get; set; }
        public decimal T_CPP_CONSP_UR2 { get; set; }
        public decimal T_CPP_CONSP_UPHS { get; set; }
        public decimal T_CPP_CONSP_UPHS_GP1 { get; set; }
        public decimal T_CPP_CONSP_UPHS_GP2 { get; set; }
        public decimal T_CPP_1905_UPHS { get; set; }
        public decimal T_CPP_CONSP_AB3 { get; set; }
        public decimal T_CPP_CONSP_AB3_FDFAN { get; set; }
        public decimal T_CPP_CONSP_AB3_RMH { get; set; }
        public decimal T_CPP_TOTAL_CONSP_IN_CPP { get; set; }
        public decimal T_CPP_CONSP_BL { get; set; }
        public decimal T_CPP_CONSP_RMH { get; set; }
        public decimal T_CPP_CONSP_ACT { get; set; }
        public decimal T_CPP_CONSP_UCT { get; set; }
        public decimal T_CPP_CONSP_WPT { get; set; }
        public decimal T_CPP_CONSP_DMW { get; set; }
        public decimal T_CPP_CONSP_IA_SPG { get; set; }
        public decimal T_CPP_CONSP_IA_OFFSITE { get; set; }
        public decimal T_CPP_CONSP_IA { get; set; }
        public decimal T_CPP_CONSP_IA_GP1 { get; set; }
        public decimal T_CPP_CONSP_IA_GP2 { get; set; }
        public decimal T_CPP_1905_CONSP_IA_GP2 { get; set; }
        public decimal T_CPP_CONSP_ETP { get; set; }
        public decimal T_CPP_CONSP_ETP_GP1 { get; set; }
        public decimal T_CPP_CONSP_ETP_GP2 { get; set; }
        public decimal T_CPP_1901_CONSP_ETP_GP2 { get; set; }
        public decimal T_CPP_CONSP_FIRE { get; set; }
        public decimal T_CPP_CONSP_FIRE_GP1 { get; set; }
        public decimal T_CPP_CONSP_FIRE_GP2 { get; set; }
        public decimal T_CPP_CONSP_RW_PMP { get; set; }
        public decimal T_CPP_CONSP_KS { get; set; }
        public decimal T_CPP_CONSP_KS_GP1 { get; set; }
        public decimal T_CPP_CONSP_KS_GP2 { get; set; }
        public decimal T_CPP_CONSP_MISC { get; set; }
        public decimal T_CPP_CONSP_OTHERS_GP1 { get; set; }
        public decimal T_CPP_CONSP_DIRECT_GP1 { get; set; }
        public decimal T_CPP_CONSP_RMH_GP1 { get; set; }
        public decimal T_CPP_CONSP_MISC_GP1 { get; set; }
        public decimal T_CPP_TOT_CONSP { get; set; }
        public decimal T_CPP_DIRECT_GP2 { get; set; }
        public decimal T_CPP_LINE_INC_TRF_LOSS { get; set; }
        public decimal T_CPP_PERCENT_LOSS { get; set; }
        public decimal T_CPP_CONSP_UR2_AFT_ADJ { get; set; }
        public decimal T_CPP_TOTAL_CONSP { get; set; }
        public decimal T_CPP_ALLOC_DM_TOT { get; set; }
        public decimal T_CPP_ALLOC_AM2_DM { get; set; }
        public decimal T_CPP_ALLOC_UR2_DM { get; set; }
        public decimal T_CPP_ALLOC_GP2_DM { get; set; }
        public decimal T_CPP_ALLOC_GP1_DM { get; set; }
        public decimal T_CPP_TO_WPT { get; set; }
        public decimal T_CPP_ALLOC_GP2_AM2_CT_MKUP_PW { get; set; }
        public decimal T_CPP_ALLOC_GP2_AM2_STORAGE { get; set; }
        public decimal T_CPP_ALLOC_GP2_UR2_CT_MKUP_PW { get; set; }
        public decimal T_CPP_ALLOC_GP2_UR2_NP_PW { get; set; }
        public decimal T_CPP_ALLOC_GP2_UR2_TOT_PW { get; set; }
        public decimal T_CPP_ALLOC_DM_GP2_PW { get; set; }
        public decimal T_CPP_ALLOC_TOT_GP2_PW { get; set; }
        public decimal T_CPP_ALLOC_GP1_PW { get; set; }
        public decimal T_CPP_TOT_PWR_BK_GP2 { get; set; }
        public decimal T_CPP_CONSP_IA_GP2_HLF { get; set; }
        public decimal T_CPP_CONSP_UPH { get; set; }
        public decimal T_CPP_CONSP_BYPD_HNDL { get; set; }
        public decimal T_1901_PLT_CONSP_STOT { get; set; }
        public decimal T_CPP_ALLOC_PLT_LIGHT { get; set; }
        public decimal T_CPP_ALLOC_RMH_PLT_CONSP { get; set; }
        public decimal T_CPP_CONSP_AM2_BL_NET_SC_AP { get; set; }
        public decimal T_CPP_CONSP_ACT_SC_AP { get; set; }
        public decimal T_CPP_CONSP_IA_GP2_SC_AP { get; set; }
        public decimal T_CPP_CONSP_AM2_RMH_SC_AP { get; set; }
        public decimal T_CPP_CONSP_UPH_SC_AP { get; set; }
        public decimal T_CPP_CONSP_BYPD_HNDL_SC_AP { get; set; }
        public decimal T_CPP_ALLOC_AM2_DM_SC_AP { get; set; }
        public decimal T_CPP_ALO_G2_AMCTMKUP_PW_SC_AP { get; set; }
        public decimal T_CPP_ALLOC_GP2_AM_STORG_SC_AP { get; set; }
        public decimal T_CPP_1901_CONSP_ETP_GP2_SC_AP { get; set; }
        public decimal T_1901_PLT_CONSP_STOT_SC_AP { get; set; }
        public decimal T_CPP_ALLOC_PLT_LIGHT_SC_AP { get; set; }
        public decimal T_CPP_ALLO_RMH_PLT_CONSP_SC_AP { get; set; }
        public decimal T_CPP_AM2_NP_TRF_LOS_SC_AP { get; set; }
        public decimal T_CPP_AV_UPS_SC_AP { get; set; }
        public decimal T_CPP_NP_BAT_CHG_SC_AP { get; set; }
        public decimal T_CPP_NP_ETP_SC_AP { get; set; }
        public decimal T_CPP_NP_STOT_SC_AP { get; set; }
        public decimal T_CPP_RMH_PORT_SC_AP { get; set; }
        public decimal T_CPP_1901_NP_STOT_SC_AP { get; set; }
        public decimal T_CPP_1901_GTOT_SC_AP { get; set; }
        public decimal T_CPP_CONSP_AM2_BL_NET_SC_AH { get; set; }
        public decimal T_CPP_CONSP_ACT_SC_AH { get; set; }
        public decimal T_CPP_CONSP_IA_GP2_SC_AH { get; set; }
        public decimal T_CPP_CONSP_AM2_RMH_SC_AH { get; set; }
        public decimal T_CPP_CONSP_UPH_SC_AH { get; set; }
        public decimal T_CPP_CONSP_BYPD_HNDL_SC_AH { get; set; }
        public decimal T_CPP_ALLOC_AM2_DM_SC_AH { get; set; }
        public decimal T_CPP_ALO_G2_AMCTMKUP_PW_SC_AH { get; set; }
        public decimal T_CPP_ALLOC_GP2_AM_STORG_SC_AH { get; set; }
        public decimal T_CPP_1901_CONSP_ETP_GP2_SC_AH { get; set; }
        public decimal T_1901_PLT_CONSP_STOT_SC_AH { get; set; }
        public decimal T_CPP_ALLOC_PLT_LIGHT_SC_AH { get; set; }
        public decimal T_CPP_ALLO_RMH_PLT_CONSP_SC_AH { get; set; }
        public decimal T_CPP_AM2_NP_TRF_LOS_SC_AH { get; set; }
        public decimal T_CPP_AV_UPS_SC_AH { get; set; }
        public decimal T_CPP_NP_BAT_CHG_SC_AH { get; set; }
        public decimal T_CPP_NP_ETP_SC_AH { get; set; }
        public decimal T_CPP_NP_STOT_SC_AH { get; set; }
        public decimal T_CPP_RMH_PORT_SC_AH { get; set; }
        public decimal T_CPP_1901_NP_STOT_SC_AH { get; set; }
        public decimal T_CPP_1901_GTOT_SC_AH { get; set; }
        public decimal T_CPP_UR_PL_BL { get; set; }
        public decimal T_CPP_RMH_SITE { get; set; }
        public decimal T_CPP_1905_STOT { get; set; }
        public decimal T_CPP_NP_PLT_LT { get; set; }
        public decimal T_CPP_NP_BAGG { get; set; }
        public decimal T_CPP_NP_TWN { get; set; }
        public decimal T_CPP_NP_WPT { get; set; }
        public decimal T_CPP_CONSP_UR_NET { get; set; }
        public decimal T_CPP_NP_PDB { get; set; }
        public decimal T_CPP_ETP { get; set; }
        public decimal T_CPP_1905_NP_STOT { get; set; }
        public decimal T_CPP_1905_RMH_PORT { get; set; }
        public decimal T_CPP_UR_1905_BL { get; set; }
        public decimal T_CPP_1905_TOT { get; set; }
        public decimal T_CPP_UR_PL_BL_SC_UP { get; set; }
        public decimal T_CPP_CONSP_UCT_SC_UP { get; set; }
        public decimal T_CPP_1905_CONSP_IA_GP2_SC_UP { get; set; }
        public decimal T_CPP_RMH_SITE_SC_UP { get; set; }
        public decimal T_CPP_CONSP_UPHS_GP2_SC_UP { get; set; }
        public decimal T_CPP_ALO_GP2_UR2_TOT_PW_SC_UP { get; set; }
        public decimal T_CPP_ALLOC_UR2_DM_SC_UP { get; set; }
        public decimal T_CPP_1901_CONSP_ETP_GP2_SC_UP { get; set; }
        public decimal T_CPP_CONSP_KS_GP2_SC_UP { get; set; }
        public decimal T_CPP_1905_STOT_SC_UP { get; set; }
        public decimal T_CPP_NP_PLT_LT_SC_UP { get; set; }
        public decimal T_CPP_NP_BAGG_SC_UP { get; set; }
        public decimal T_CPP_NP_TWN_SC_UP { get; set; }
        public decimal T_CPP_NP_WPT_SC_UP { get; set; }
        public decimal T_CPP_CONSP_FIRE_GP2_SC_UP { get; set; }
        public decimal T_CPP_CONSP_AM2_NPTRFLOS_SC_UP { get; set; }
        public decimal T_CPP_NP_PDB_SC_UP { get; set; }
        public decimal T_CPP_CONSP_MISC_GP1_SC_UP { get; set; }
        public decimal T_CPP_ETP_SC_UP { get; set; }
        public decimal T_CPP_NP_STOT_SC_UP { get; set; }
        public decimal T_CPP_RMH_PORT_SC_UP { get; set; }
        public decimal T_CPP_UR_1905_BL_SC_UP { get; set; }
        public decimal T_CPP_1905_TOT_SC_UP { get; set; }
        public decimal T_CPP_UR_PL_BL_SC_UH { get; set; }
        public decimal T_CPP_CONSP_UCT_SC_UH { get; set; }
        public decimal T_CPP_1905_CONSP_IA_GP2_SC_UH { get; set; }
        public decimal T_CPP_RMH_SITE_SC_UH { get; set; }
        public decimal T_CPP_CONSP_UPHS_GP2_SC_UH { get; set; }
        public decimal T_CPP_ALO_GP2_UR2_TOT_PW_SC_UH { get; set; }
        public decimal T_CPP_ALLOC_UR2_DM_SC_UH { get; set; }
        public decimal T_CPP_1901_CONSP_ETP_GP2_SC_UH { get; set; }
        public decimal T_CPP_CONSP_KS_GP2_SC_UH { get; set; }
        public decimal T_CPP_1905_STOT_SC_UH { get; set; }
        public decimal T_CPP_NP_PLT_LT_SC_UH { get; set; }
        public decimal T_CPP_NP_BAGG_SC_UH { get; set; }
        public decimal T_CPP_NP_TWN_SC_UH { get; set; }
        public decimal T_CPP_NP_WPT_SC_UH { get; set; }
        public decimal T_CPP_CONSP_FIRE_GP2_SC_UH { get; set; }
        public decimal T_CPP_CONSP_AM2_NPTRFLOS_SC_UH { get; set; }
        public decimal T_CPP_NP_PDB_SC_UH { get; set; }
        public decimal T_CPP_CONSP_MISC_GP1_SC_UH { get; set; }
        public decimal T_CPP_ETP_SC_UH { get; set; }
        public decimal T_CPP_NP_STOT_SC_UH { get; set; }
        public decimal T_CPP_RMH_PORT_SC_UH { get; set; }
        public decimal T_CPP_UR_1905_BL_SC_UH { get; set; }
        public decimal T_CPP_1905_TOT_SC_UH { get; set; }
        public decimal T_CPP_PL_CT { get; set; }
        public decimal T_CPP_PL_IA { get; set; }
        public decimal T_CPP_PL_COAL_HDL { get; set; }
        public decimal T_CPP_PL_ASH_HDL { get; set; }
        public decimal T_CPP_PL_OTH_DMP { get; set; }
        public decimal T_CPP_PL_ETP { get; set; }
        public decimal T_CPP_PL_STOT { get; set; }
        public decimal T_CPP_NP_LIGHT { get; set; }
        public decimal T_CPP_NP_COAL_HDL { get; set; }
        public decimal T_CPP_NP_ASH_HDL { get; set; }
        public decimal T_CPP_NP_TRM_LOSS { get; set; }
        public decimal T_CPP_NP_OTH_UPS { get; set; }
        public decimal T_CPP_1909_NP_ETP { get; set; }
        public decimal T_CPP_1909_NP_STOT { get; set; }
        public decimal T_CPP_1909_RMH_PORT { get; set; }
        public decimal T_CPP_1909_GTOT { get; set; }
        public decimal T_CPP_CONSP_AB3_FDFAN_SC_SP { get; set; }
        public decimal T_CPP_PL_CT_SC_SP { get; set; }
        public decimal T_CPP_PL_IA_SC_SP { get; set; }
        public decimal T_CPP_PL_COAL_HDL_SC_SP { get; set; }
        public decimal T_CPP_PL_ASH_HDL_SC_SP { get; set; }
        public decimal T_CPP_PL_OTH_DMP_SC_SP { get; set; }
        public decimal T_CPP_PL_ETP_SC_SP { get; set; }
        public decimal T_CPP_CONSP_AB3_RMH_SC_SP { get; set; }
        public decimal T_CPP_PL_STOT_SC_SP { get; set; }
        public decimal T_CPP_NP_LIGHT_SC_SP { get; set; }
        public decimal T_CPP_NP_COAL_HDL_SC_SP { get; set; }
        public decimal T_CPP_NP_ASH_HDL_SC_SP { get; set; }
        public decimal T_CPP_NP_TRM_LOSS_SC_SP { get; set; }
        public decimal T_CPP_NP_OTH_UPS_SC_SP { get; set; }
        public decimal T_CPP_NP_ETP_SC_SP { get; set; }
        public decimal T_CPP_NP_STOT_SC_SP { get; set; }
        public decimal T_CPP_RMH_PORT_SC_SP { get; set; }
        public decimal T_CPP_1909_GTOT_SC_SP { get; set; }
        public decimal T_CPP_CONSP_AB3_FDFAN_SC_SH { get; set; }
        public decimal T_CPP_PL_CT_SC_SH { get; set; }
        public decimal T_CPP_PL_IA_SC_SH { get; set; }
        public decimal T_CPP_PL_COAL_HDL_SC_SH { get; set; }
        public decimal T_CPP_PL_ASH_HDL_SC_SH { get; set; }
        public decimal T_CPP_PL_OTH_DMP_SC_SH { get; set; }
        public decimal T_CPP_PL_ETP_SC_SH { get; set; }
        public decimal T_CPP_CONSP_AB3_RMH_SC_SH { get; set; }
        public decimal T_CPP_PL_STOT_SC_SH { get; set; }
        public decimal T_CPP_NP_LIGHT_SC_SH { get; set; }
        public decimal T_CPP_NP_COAL_HDL_SC_SH { get; set; }
        public decimal T_CPP_NP_ASH_HDL_SC_SH { get; set; }
        public decimal T_CPP_NP_TRM_LOSS_SC_SH { get; set; }
        public decimal T_CPP_NP_OTH_UPS_SC_SH { get; set; }
        public decimal T_CPP_NP_ETP_SC_SH { get; set; }
        public decimal T_CPP_NP_STOT_SC_SH { get; set; }
        public decimal T_CPP_RMH_PORT_SC_SH { get; set; }
        public decimal T_CPP_1909_GTOT_SC_SH { get; set; }
        public decimal T_CPP_NPC_AM2_SCA_UP { get; set; }
        public decimal T_CPP_NPC_UR2_SCA_UP { get; set; }
        public decimal T_CPP_NPC_SCA_UP { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_WPT_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_DMW_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_IA_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_RMH_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_UPH_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_ETP_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_KS_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_FS_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_UR_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TOT_GP2 { get; set; }
        public decimal T_CPP_ALLOC_BK_TO_AB3_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_WPT_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_DMW_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_IA_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_UPH_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_ETP_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_KS_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_FS_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_AM2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_AMM_TOT_GP2 { get; set; }
        public decimal T_CPP_TOT_WS1 { get; set; }
        public decimal T_CPP_ALLOC_TO_WPT_UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_DMW_UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_IA_UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_RMH_UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_UPH__UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_ETP_UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_TO_AMM__UR2_GP2 { get; set; }
        public decimal T_CPP_ALLOC_UR2_GP2 { get; set; }
        public decimal T_CPP_TO_UR2_TOT { get; set; }
        public decimal T_CPP_ALLOC_TO_UR2_TOT { get; set; }
        public decimal T_CPP_WS1_TOT_PWR { get; set; }
        public decimal T_CPP_WS1_TOT_GT_ENERGY { get; set; }
        public decimal T_CPP_ENERGY_WS1 { get; set; }
        public decimal T_CPP_WS1_ELECTRICITY { get; set; }
        public decimal T_CPP_WS1_ELECTRICITY_ENERGY { get; set; }
        public decimal T_CPP_FAI_TOT_PWR_AMM { get; set; }
        public decimal T_CPP_FAI_TOT_PWR_UR { get; set; }
        public decimal T_FI1_TOT_CPP_SC_UP { get; set; }
        public decimal T_MI3_TOT_CPP_SC_UP { get; set; }
        public decimal T_CPP_UTIL_BAT_CHG_503 { get; set; }
        public decimal T_CPP_NP_BAT_CHG_1901 { get; set; }
        public decimal T_CPP_CONSP_ACT_1901 { get; set; }
        public string T_STATUS { get; set; }
        public decimal T_CPP_NP_BAT_CHG_NEW_SC_AP { get; set; }
        public decimal T_CPP_UTIL_BAT_CHG_503_SC_AP { get; set; }
        public decimal T_CPP_NP_BAT_CHG_NEW_SC_AH { get; set; }
        public decimal T_CPP_UTIL_BAT_CHG_503_SC_AH { get; set; }
        public decimal T_CPP_1905_CONSP_ETP_GP2 { get; set; }
        public decimal T_CPP_ALLOC_DMP_GP2 { get; set; }
        public decimal T_GEN_PWR_EXPORTT_GP3 { get; set; }
        public decimal T_PWR_ALLOC_GP3_GP1 { get; set; }
        public decimal T_PWR_IMPORTF_GT3 { get; set; }
        public decimal T_PWR_ALLOC_GP3_GP2 { get; set; }
        public decimal T_PWR_CONSP_UPHS_UNIT3 { get; set; }
    }
    public class PTS227Dto
    {
        public decimal T_YEAR { get; set; }
        public decimal T_IDENTITY { get; set; }
        public decimal T_VERSION { get; set; }
        public string Btn { get; set; }
    }
}
