namespace itsppisapi.Models
{
    public class PUS201Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string U2_TRANS_DATE { get; set; }
        public decimal U2_TOT_AMM_CONSP_INT { get; set; }
        public decimal U2_TOT_AMM_CONSP { get; set; }
        public decimal U2_TOT_UREA_PROD { get; set; }
        public decimal U2_EFF_FACTOR { get; set; }
        public decimal U2_UREA_CAP_UTIL { get; set; }
        public decimal U2_TA_CO2_CONSP_INT { get; set; }
        public decimal U2_TA_CO2_CONSP { get; set; }
        public decimal U2_TA_STREAM_HRS { get; set; }
        public decimal U2_TA_AMM_CONSP { get; set; }
        public decimal U2_TA_UREA_PROD { get; set; }
        public decimal U2_TA_CAP_UTIL { get; set; }
        public decimal U2_TB_CO2_CONSP_INT { get; set; }
        public decimal U2_TB_CO2_CONSP { get; set; }
        public decimal U2_TB_STREAM_HRS { get; set; }
        public decimal U2_TB_AMM_CONSP { get; set; }
        public decimal U2_TB_UREA_PROD { get; set; }
        public decimal U2_TB_CAP_UTIL { get; set; }
        public string U2_REMARKS_D { get; set; }
        public string U2_REMARKS_M { get; set; }
        public decimal U2_TA_BFW_CONSP_INT { get; set; }
        public decimal U2_TA_BFW_CONSP { get; set; }
        public decimal U2_TB_BFW_CONSP { get; set; }
        public decimal U2_FIRE_CONSP_UCT2_INT { get; set; }
        public decimal U2_FIRE_CONSP_UCT2 { get; set; }
        public decimal U2_FW_CONSP_SW_GPI_INT { get; set; }
        public decimal U2_FW_CONSP_SW_GPI_INT_DIFF { get; set; }
        public decimal U2_FW_CONSP_SW_GPI { get; set; }
        public decimal U2_FW_CONSP_SW_GPII_INT { get; set; }
        public decimal U2_FW_CONSP_SW_GPII_INT_DIFF { get; set; }
        public decimal U2_FW_CONSP_SW_GPII { get; set; }
        public decimal U2_TA_UTC_PROD_INT { get; set; }
        public decimal U2_TA_UTC_PROD { get; set; }
        public decimal U2_TB_UTC_PROD_INT { get; set; }
        public decimal U2_TB_UTC_PROD { get; set; }
        public decimal U2_USC_PROD_INT { get; set; }
        public decimal U2_USC_PROD { get; set; }
        public decimal U2_UPC_PROD_INT { get; set; }
        public decimal U2_UPC_PROD { get; set; }
        public decimal U2_TOT_CONDENSATE_PROD { get; set; }
        public decimal U2_EFF_WATER_EXP { get; set; }
        public decimal U2_TOT_SH_CONSP_INT { get; set; }
        public decimal U2_TOT_SH_CONSP { get; set; }
        public decimal U2_TA_SH_CONSP { get; set; }
        public decimal U2_TB_SH_CONSP { get; set; }
        public decimal U2_CO2_SALES_INT { get; set; }
        public decimal U2_CO2_SALES { get; set; }
        public decimal TXT_AMM_CONSP { get; set; }
        public decimal TXT_AMM_STORAGE { get; set; }
        public decimal TXT_CO2_CONSP { get; set; }
        public decimal TXT_TOT_BFW_CONSP { get; set; }
        public decimal TXT_PW_UCT { get; set; }
        public decimal TXT_SM_CONSP_UCT { get; set; }
        public decimal TXT_TA_PWR_CONSP { get; set; }
        public decimal TXT_TB_PWR_CONSP { get; set; }
        public decimal TXT_UCT_PWR_CONSP { get; set; }
        public decimal TXT_TOT_PWR_CONSP { get; set; }
        public decimal TXT_SP_TA_SH_CONSP { get; set; }
        public decimal TXT_SP_TB_SH_CONSP { get; set; }
        public decimal TXT_SP_TOT_SH_CONSP { get; set; }
        public decimal TXT_SP_TA_AMM_CONSP { get; set; }
        public decimal TXT_SP_TB_AMM_CONSP { get; set; }
        public decimal TXT_SP_TOT_AMM_CONSP { get; set; }
        public decimal TXT_SP_TA_CO2_CONSP { get; set; }
        public decimal TXT_SP_TB_CO2_CONSP { get; set; }
        public decimal TXT_SP_TOT_CO2_CONSP { get; set; }
        public decimal TXT_SP_TA_BFW_CONSP { get; set; }
        public decimal TXT_SP_TB_BFW_CONSP { get; set; }
        public decimal TXT_SP_TOT_BFW_CONSP { get; set; }
        public decimal TXT_SP_TA_PWR_CONSP { get; set; }
        public decimal TXT_SP_TB_PWR_CONSP { get; set; }
        public decimal TXT_SP_TOT_PWR_CONSP { get; set; }
        public decimal TXT_SP_TA_UTC_PROD { get; set; }
        public decimal TXT_SP_TB_UTC_PROD { get; set; }
        public decimal TXT_SP_USC_CONSP { get; set; }
        public decimal TXT_SP_UPC_CONSP { get; set; }
        public decimal TXT_SP_UCT_PWR_CONSP { get; set; }
        public decimal TXT_SP_TOT_UTC_PROD { get; set; }
        public string DATE_MOD { get; set; }
        public string USER_NAME { get; set; }

        // PRV 
        public string PRV_U2_TRANS_DATE { get; set; }
        public decimal PRV_U2_TOT_AMM_CONSP_INT { get; set; }
        public decimal PRV_U2_TOT_AMM_CONSP { get; set; }
        public decimal PRV_U2_TOT_UREA_PROD { get; set; }
        public decimal PRV_U2_TA_CO2_CONSP_INT { get; set; }
        public decimal PRV_U2_TA_CO2_CONSP { get; set; }
        public decimal PRV_U2_TA_AMM_CONSP { get; set; }
        public decimal PRV_U2_TA_UREA_PROD { get; set; }
        public decimal PRV_U2_TB_CO2_CONSP_INT { get; set; }
        public decimal PRV_U2_TB_CO2_CONSP { get; set; }
        public decimal PRV_U2_TB_AMM_CONSP { get; set; }
        public decimal PRV_U2_TB_UREA_PROD { get; set; }
        public decimal PRV_U2_TA_BFW_CONSP_INT { get; set; }
        public decimal PRV_U2_TA_BFW_CONSP { get; set; }
        public decimal PRV_U2_TB_BFW_CONSP { get; set; }
        public decimal PRV_U2_FIRE_CONSP_UCT2_INT { get; set; }
        public decimal PRV_U2_FIRE_CONSP_UCT2 { get; set; }
        public decimal PRV_U2_FW_CONSP_SW_GPI_INT { get; set; }
        public decimal PRV_U2_FW_CONSP_SW_GPI_INT_DIFF { get; set; }
        public decimal PRV_U2_FW_CONSP_SW_GPI { get; set; }
        public decimal PRV_U2_FW_CONSP_SW_GPII_INT { get; set; }
        public decimal PRV_U2_FW_CONSP_SW_GPII_INT_DIFF { get; set; }
        public decimal PRV_U2_FW_CONSP_SW_GPII { get; set; }
        public decimal PRV_U2_TA_UTC_PROD_INT { get; set; }
        public decimal PRV_U2_TA_UTC_PROD { get; set; }
        public decimal PRV_U2_TB_UTC_PROD_INT { get; set; }
        public decimal PRV_U2_TB_UTC_PROD { get; set; }
        public decimal PRV_U2_USC_PROD_INT { get; set; }
        public decimal PRV_U2_USC_PROD { get; set; }
        public decimal PRV_U2_UPC_PROD_INT { get; set; }
        public decimal PRV_U2_UPC_PROD { get; set; }
        public decimal PRV_U2_TOT_CONDENSATE_PROD { get; set; }
        public decimal PRV_U2_EFF_WATER_EXP { get; set; }
        public decimal PRV_U2_TOT_SH_CONSP_INT { get; set; }
        public decimal PRV_U2_TOT_SH_CONSP { get; set; }
        public decimal PRV_U2_TA_SH_CONSP { get; set; }
        public decimal PRV_U2_TB_SH_CONSP { get; set; }
        public decimal PRV_U2_CO2_SALES_INT { get; set; }
        public decimal PRV_U2_CO2_SALES { get; set; }
        public decimal PRV_U2_EFF_FACTOR { get; set; }
        public decimal PRV_U2_UREA_CAP_UTIL { get; set; }
        public decimal PRV_U2_TA_STREAM_HRS { get; set; }
        public decimal PRV_U2_TA_CAP_UTIL { get; set; }
        public decimal PRV_U2_TB_STREAM_HRS { get; set; }
        public decimal PRV_U2_TB_CAP_UTIL { get; set; }
        public string PRV_U2_REMARKS { get; set; }
    }

    public class PUS201DVDto
    {
        public string PARM_EFF { get; set; }
        public string PARM_UREA_CAPACITY { get; set; }
        public string PARM_G_MF_SW { get; set; }
        public string PROD_TO_DATE { get; set; }
        public string HIGHEST_YEARLY_PROD_DATE { get; set; }
        public decimal HIGHEST_YEARLY_PROD { get; set; }
        public string HIGHEST_MONTHLY_PROD_DATE { get; set; }
        public decimal HIGHEST_MONTHLY_PROD { get; set; }
        public decimal HIGHEST_UREA_PROD { get; set; }
        public string HIGHEST_UREA_PROD_DATE { get; set; }
        public decimal HIGHEST_TA_PROD { get; set; }
        public string HIGHEST_TA_PROD_DATE { get; set; }
        public decimal HIGHEST_TB_PROD { get; set; }
        public string HIGHEST_TB_PROD_DATE { get; set; }
    }
}
