namespace itsppisapi.Dtos
{
    public class POS010SaveDto
    {

        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public decimal OU1_USER_ID { get; set; }

        public decimal OU1_RW_MEAS_STOCK { get; set; }
        public decimal OU1_RW_CALC_STOCK { get; set; }
        public decimal OU1_RW_RECPT_KSR_INT { get; set; }
        public decimal OU1_RW_RECPT_KSR_INT_DIFF { get; set; }
        public decimal OU1_RW_RECPT_KSR { get; set; }
        public decimal OU1_RW_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_RW_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_RW_TOTAL_RECPT { get; set; }
        public decimal OU1_RW_CONSP_WPT_INT { get; set; }
        public decimal OU1_RW_CONSP_WPT_INT_DIFF { get; set; }
        public decimal OU1_RW_CONSP_WPT { get; set; }
        public decimal OU1_RW_CONSP_GB { get; set; }
        public decimal OU1_RW_CONSP_DILUTION { get; set; }
        public decimal OU1_RW_EXPORTT_UNIT2_INT { get; set; }
        public decimal OU1_RW_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_RW_TOTAL_CONSP { get; set; }
        public decimal OU1_RW_R2_TANK_LEVEL { get; set; }
        public decimal OU1_RW_R2_TANK_STOCK { get; set; }
        public decimal OU1_RW_R3_TANK_LEVEL { get; set; }
        public decimal OU1_RW_R3_TANK_STOCK { get; set; }
        public decimal OU1_FW_TANK1_LEVEL { get; set; }
        public decimal OU1_FW_TANK1_STOCK { get; set; }
        public decimal OU1_FW_TANK2_LEVEL { get; set; }
        public decimal OU1_FW_TANK2_STOCK { get; set; }
        public decimal OU1_FW_TANK3_LEVEL { get; set; }
        public decimal OU1_FW_TANK3_STOCK { get; set; }
        public decimal OU1_FW_STOCK { get; set; }
        public decimal OU1_FW_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_FW_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_FW_TOTAL_RECPT { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT1 { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT1_DIFF { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT2 { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT2_DIFF { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT3 { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT3_DIFF { get; set; }
        public decimal OU1_FW_CONSP_DMP { get; set; }
        public decimal OU1_FW_CONSP_ACT_INT { get; set; }
        public decimal OU1_FW_CONSP_ACT { get; set; }
        public decimal OU1_FW_CONSP_UCT_INT { get; set; }
        public decimal OU1_FW_CONSP_UCT_INT_DIFF { get; set; }
        public decimal OU1_FW_CONSP_UCT { get; set; }
        public decimal OU1_FW_CONSP_DW_INT1 { get; set; }
        public decimal OU1_FW_CONSP_DW_INT1_DIFF { get; set; }
        public decimal OU1_FW_CONSP_DW_INT2 { get; set; }
        public decimal OU1_FW_CONSP_DW_INT2_DIFF { get; set; }
        public decimal OU1_FW_CONSP_DW { get; set; }
        public decimal OU1_FW_CONSP_SW_INT { get; set; }
        public decimal OU1_FW_CONSP_SW_DIFF { get; set; }
        public decimal OU1_FW_CONSP_FIRE { get; set; }
        public decimal OU1_FW_CONSP_SW { get; set; }
        public decimal OU1_FW_CONSP_BW { get; set; }
        public decimal OU1_FW_EXPORTT_UNIT2_INT { get; set; }
        public decimal OU1_FW_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_FW_TOTAL_CONSP { get; set; }
        public decimal OU1_DMW_TANK1_LEVEL { get; set; }
        public decimal OU1_DMW_TANK1_STOCK { get; set; }
        public decimal OU1_DMW_TANK2_LEVEL { get; set; }
        public decimal OU1_DMW_TANK2_STOCK { get; set; }
        public decimal OU1_DMW_STOCK { get; set; }
        public decimal OU1_REGN_LOSS_DMP { get; set; }
        public decimal OU1_DMW_PROD_INT1 { get; set; }
        public decimal OU1_DMW_PROD_INT1_DIFF { get; set; }
        public decimal OU1_DMW_PROD_INT2 { get; set; }
        public decimal OU1_DMW_PROD_INT2_DIFF { get; set; }
        public decimal OU1_DMW_PROD_INT3 { get; set; }
        public decimal OU1_DMW_PROD_INT3_DIFF { get; set; }
        public decimal OU1_DMW_PROD { get; set; }
        public decimal OU1_DMW_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_DMW_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_DMW_NET_PROD { get; set; }
        public decimal OU1_APC_PROD_INT { get; set; }
        public decimal OU1_APC_PROD { get; set; }
        public decimal OU1_CTTC_PROD { get; set; }
        public decimal OU1_APC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_APC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_ATC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_ATC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_UPC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_UPC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_UTC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_UTC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_USC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_USC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_CTTC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_CTTC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_TOTAL_CONDENSATE { get; set; }
        public decimal OU1_CONDENSATE_DRAINED { get; set; }
        public decimal OU1_NET_CONDENSATE { get; set; }
        public decimal OU1_PW_FEED_MB { get; set; }
        public decimal OU1_REGN_LOSS_MB { get; set; }
        public decimal OU1_DMW_EXPORTT_UNIT2_INT { get; set; }
        public decimal OU1_DMW_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_DMW_NET_CONSP { get; set; }
        public decimal OU1_PW_TANK1_LEVEL { get; set; }
        public decimal OU1_PW_TANK1_STOCK { get; set; }
        public decimal OU1_PW_TANK2_LEVEL { get; set; }
        public decimal OU1_PW_TANK2_STOCK { get; set; }
        public decimal OU1_PW_STOCK { get; set; }
        public decimal OU1_PW_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_PW_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_PW_NET_PROD { get; set; }
        public decimal OU1_PW_CONSP_UNIT1_INT { get; set; }
        public decimal OU1_PW_CONSP_UNIT1 { get; set; }
        public decimal OU1_PW_EXPORTT_UNIT2_INT { get; set; }
        public decimal OU1_PW_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_TOTAL_PW_DISTRIBUTION { get; set; }
        public decimal OU1_PW_CONSP_AMM { get; set; }
        public decimal OU1_PW_CONSP_SPG_INT { get; set; }
        public decimal OU1_PW_CONSP_SPG { get; set; }
        public string OU1_REMARKS { get; set; }
        public decimal OU1_FW_EXPORTT_UNIT2_INT_DIFF { get; set; }
        public decimal OU1_FW_CONSP_DW_UNIT2 { get; set; }
        public decimal OU1_FW_CONSP_FIRE_UNIT2 { get; set; }
        public decimal OU1_FW_CONSP_MISC_UNIT2 { get; set; }
        public decimal OU1_FW_CONSP_TOTL_UNIT2 { get; set; }
        public decimal OU1_RW_CONSP_GB_GP1 { get; set; }
        public decimal OU1_RW_CONSP_GB_GP2 { get; set; }
        public decimal OU1_RW_CONSP_DILUTION_GP1 { get; set; }
        public decimal OU1_RW_CONSP_DILUTION_GP2 { get; set; }
        public decimal OU1_FW_CONSP_DMP_GP1 { get; set; }
        public decimal OU1_FW_CONSP_DMP_GP2 { get; set; }
        public decimal OU1_REGN_LOSS_DMP_GP1 { get; set; }
        public decimal OU1_REGN_LOSS_DMP_GP2 { get; set; }
        public decimal OU1_TC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_TC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_SC_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_SC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_REGN_LOSS_MB_GP1 { get; set; }
        public decimal OU1_REGN_LOSS_MB_GP2 { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT4 { get; set; }
        public decimal OU1_FW_CONSP_DMP_INT4_DIFF { get; set; }
        public decimal OU1_DMW_MAKEUP_GPII { get; set; }
        public decimal OU1_FW_CONSP_BW_GPII { get; set; }
        public decimal OU1_FW_CONSP_BW_GPI { get; set; }
        public decimal OU1_CONDENSATE_DRAINED_GPII { get; set; }
        public decimal OU1_CONDENSATE_DRAINED_GPI { get; set; }
        public decimal OU1_DMW_MAKEUP_GPI { get; set; }
        public decimal OU1_RW_RECPT_KSR_INT2 { get; set; }
        public decimal OU1_RW_RECPT_KSR_INT2_DIFF { get; set; }
        public decimal OU1_TC_TFRT_PW_UNIT1 { get; set; }
        public decimal OU1_TC_TFRT_PW_UNIT2 { get; set; }
        public decimal OU1_COND_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_COND_EXPORTT_UNIT1 { get; set; }
        public decimal OU1_APC_PROD_INT_DIFF { get; set; }
        public decimal OU1_DMW_MAKEUP_GPII_INT { get; set; }
        public decimal OU1_PW_EXPORTT_UNIT2_TANK { get; set; }
        public decimal OU1_PW_EXPORTT_UNIT1_TANK { get; set; }
        public decimal OU1_PW_EXPORTT_GPII { get; set; }
        public decimal OU1_TOTAL_PW_CONSP_UNIT1 { get; set; }
        public decimal OU1_TOTAL_PW_CONSP_UNIT2 { get; set; }
        public decimal OU1_PW_FEED_UNIT1 { get; set; }
        public decimal OU1_PW_FEED_UNIT2 { get; set; }
        public decimal OU1_NET_COND_GPII { get; set; }
        public decimal OU1_PW_FEED_EXPORTT_UNIT1 { get; set; }
        public decimal OU1_PW_FEED_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_FW_TEMP_TANK_LEVEL { get; set; }
        public decimal OU1_FW_TEMP_TANK_STOCK { get; set; }
        public decimal OU1_FW_TEMP_TANK_CONSP { get; set; }
        public decimal OU1_EFFL_CONSP_ACT { get; set; }
        public decimal OU1_WTR_CONSP_ACT { get; set; }
        public decimal OU1_FW_CONSP_SW_GPIA { get; set; }
        public decimal OU1_FIRE_CONSP_UCT_GPI { get; set; }
        public decimal OU1_FIRE_CONSP_UCT_GPI_INT { get; set; }
        public decimal OU1_FIRE_CONSP_UCT_GPI_INT_DIFF { get; set; }
        public decimal OU1_FW_CONSP_UCT_GPI { get; set; }
        public decimal OU1_PW_CONSP_MEEFOG_INT { get; set; }
        public decimal OU1_PW_CONSP_MEEFOG { get; set; }
        public decimal OU1_PW_CONSP_SPG_WO_MEEFOG { get; set; }
        public decimal OU1_RW_CONSP_WPT_INT_NEW { get; set; }
        public decimal OU1_RW_WPT_CONSP_INT_NEW_DIFF { get; set; }
        public decimal OU1_RW_WPT_CONSP_OLD_INT { get; set; }
        public decimal OU1_RW_WPT_CONSP_NEW_INT { get; set; }
        public decimal OU1_FW_GP1_GP2_SINK { get; set; }
        public decimal OU1_FW_GP1_MEAS_ACT_MAKEUP { get; set; }
        public decimal OU1_FW_GP2_MEAS_ACT_MAKEUP { get; set; }
        public decimal OU1_FW_GP1_SINK { get; set; }
        public decimal OU1_FW_GPII_SINK { get; set; }
        public decimal OU1_FW_CONSP_SSP { get; set; }
        public decimal OU1_FW_CONSP_DW_SSP { get; set; }
        public decimal OU1_RW_EXPORTT_UNIT3 { get; set; }
        public decimal OU1_PW_IMPORT_GP3 { get; set; }
        public decimal OU1_DMW_TANK3_STOCK { get; set; }
        public decimal OU1_FW_TANK4_STOCK { get; set; }
        public decimal OU1_WPT_3_CONS { get; set; }
        public decimal OU1_SPG_CT_GP3 { get; set; }
        public decimal OU1_PW_GP1_FEED_EXPORT_GP3 { get; set; }
        public decimal OU1_FW_GP3_UE { get; set; }
        public decimal OU1_PW_GP1_FEED_IMPORT_GP3 { get; set; }
        public decimal OU1_WPT_TOTAL { get; set; }
        public decimal OU1_SW_GP3_UE { get; set; }
        public decimal OU1_PW_GP2_FEED_EXPORT_GP3 { get; set; }
        public decimal OU1_PW_GP1_IMPORT_GP3 { get; set; }
        public decimal OU1_DW_GP3_UE { get; set; }
        public decimal OU1_BACKWASH_WPT_GP3 { get; set; }
        public decimal OU1_PW_GP1_EXPORT_GP3 { get; set; }
        public decimal OU1_PW_TANK3_STOCK_GP3 { get; set; }
        public decimal OU1_PW_GP2_EXPORT_GP3 { get; set; }
        public decimal OU1_DMW_PROD_GP3 { get; set; }
        public decimal OU1_PW_FEED_IMPORT_GP3 { get; set; }
        public decimal OU1_RW_KST_32LINE_INT { get; set; }
        public decimal OU1_RW_KST_32LINE_INT_DIFF { get; set; }
    }
}
