namespace itsppisapi.Dtos
{
    public class POS003SaveDto
    {

        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public decimal OU1_USER_ID { get; set; }

        public decimal OU1_HCL_RECPT { get; set; }
        public decimal OU1_HCL_OTANK_LEVEL { get; set; }
        public decimal OU1_HCL_OTANK_STOCK { get; set; }
        public decimal OU1_HCL_NTANK_LEVEL { get; set; }
        public decimal OU1_HCL_NTANK_STOCK { get; set; }
        public decimal OU1_HCL_STOCK { get; set; }
        public decimal OU1_HCL_CONSP { get; set; }
        public decimal OU1_SULACID_RECPT { get; set; }
        public decimal OU1_SULACID_TANK_LEVEL { get; set; }
        public decimal OU1_SULACID_STOCK { get; set; }
        public decimal OU1_SULACID_CONSP { get; set; }
        public decimal OU1_CLYE_RECPT { get; set; }
        public decimal OU1_CLYE_TANK_LEVEL { get; set; }
        public decimal OU1_CLYE_STOCK { get; set; }
        public decimal OU1_CLYE_CONSP { get; set; }
        public decimal OU1_HSD_RECPT { get; set; }
        public decimal OU1_HSD_EDG_LEVEL { get; set; }
        public decimal OU1_HSD_EDG_STOCK { get; set; }
        public decimal OU1_HSD_GT_LEVEL { get; set; }
        // public decimal OU1_HSD_GT_STOCK { get; set; }
        public decimal OU1_HSD_NEW_LEVEL { get; set; }
        public decimal OU1_HSD_NEW_STOCK { get; set; }
        public decimal OU1_HSD_STOCK { get; set; }
        public decimal OU1_HSD_CONSP { get; set; }
        public decimal OU1_ALUM_RECPT { get; set; }
        public decimal OU1_ALUM_STOCK { get; set; }
        public decimal OU1_ALUM_CONSP { get; set; }
        public decimal OU1_CHLWPT_RECPT { get; set; }
        public decimal OU1_CHLWPT_STOCK { get; set; }
        public decimal OU1_CHLWPT_CONSP { get; set; }
        public decimal OU1_CHLRW_RECPT { get; set; }
        public decimal OU1_CHLRW_STOCK { get; set; }
        public decimal OU1_CHLRW_CONSP { get; set; }
        public decimal OU1_CHLCT_RECPT { get; set; }
        public decimal OU1_CHLCT_STOCK { get; set; }
        public decimal OU1_CHLCT_CONSP { get; set; }
        public decimal OU1_HYPO_RECPT { get; set; }
        public decimal OU1_HYPO_STOCK { get; set; }
        public decimal OU1_HYPO_CONSP { get; set; }
        public decimal OU1_N7356_RECPT { get; set; }
        public decimal OU1_N7356_STOCK { get; set; }
        public decimal OU1_N7356_CONSP { get; set; }
        public decimal OU1_N8301D_RECPT { get; set; }
        public decimal OU1_N8301D_STOCK { get; set; }
        public decimal OU1_N8301D_CONSP { get; set; }
        public decimal OU1_N7348_RECPT { get; set; }
        public decimal OU1_N7348_STOCK { get; set; }
        public decimal OU1_N7348_CONSP { get; set; }
        public decimal OU1_N7342_RECPT { get; set; }
        public decimal OU1_N7342_STOCK { get; set; }
        public decimal OU1_N7342_CONSP { get; set; }
        public decimal OU1_N7307_RECPT { get; set; }
        public decimal OU1_N7307_STOCK { get; set; }
        public decimal OU1_N7307_CONSP { get; set; }
        public decimal OU1_STBX_RECPT { get; set; }
        public decimal OU1_STBX_STOCK { get; set; }
        public decimal OU1_STBX_CONSP { get; set; }
        public decimal OU1_HYDRAZINE_RECPT { get; set; }
        public decimal OU1_HYDRAZINE_STOCK { get; set; }
        public decimal OU1_HYDRAZINE_CONSP { get; set; }
        public decimal OU1_TSP_RECPT { get; set; }
        public decimal OU1_TSP_STOCK { get; set; }
        public decimal OU1_TSP_CONSP { get; set; }
        public decimal OU1_HITECH_RECPT { get; set; }
        public decimal OU1_HITECH_STOCK { get; set; }
        public decimal OU1_HITECH_CONSP { get; set; }
        public decimal OU1_POLYEL_RECPT { get; set; }
        public decimal OU1_POLYEL_STOCK { get; set; }
        public decimal OU1_POLYEL_CONSP { get; set; }
        public decimal OU1_ACT_ALUM_RECPT { get; set; }
        public decimal OU1_ACT_ALUM_STOCK { get; set; }
        public decimal OU1_ACT_ALUM_CONSP { get; set; }
        public decimal OU1_MOLSIEVE_RECPT { get; set; }
        public decimal OU1_MOLSIEVE_STOCK { get; set; }
        public decimal OU1_MOLSIEVE_CONSP { get; set; }
        public decimal OU1_ACT_CARBON_RECPT { get; set; }
        public decimal OU1_ACT_CARBON_STOCK { get; set; }
        public decimal OU1_ACT_CARBON_CONSP { get; set; }
        public decimal OU1_SSF_PEB_RECPT { get; set; }
        public decimal OU1_SSF_PEB_STOCK { get; set; }
        public decimal OU1_SSF_PEB_CONSP { get; set; }
        public decimal OU1_SSF_SAND_RECPT { get; set; }
        public decimal OU1_SSF_SAND_STOCK { get; set; }
        public decimal OU1_SSF_SAND_CONSP { get; set; }
        public decimal OU1_DMP_PEB_RECPT { get; set; }
        public decimal OU1_DMP_PEB_STOCK { get; set; }
        public decimal OU1_DMP_PEB_CONSP { get; set; }
        public decimal OU1_WPT_SAND_RECPT { get; set; }
        public decimal OU1_WPT_SAND_STOCK { get; set; }
        public decimal OU1_WPT_SAND_CONSP { get; set; }
        public decimal OU1_INDION225_RECPT { get; set; }
        public decimal OU1_INDION225_STOCK { get; set; }
        public decimal OU1_INDION225_CONSP { get; set; }
        public decimal OU1_INDION850_RECPT { get; set; }
        public decimal OU1_INDION850_STOCK { get; set; }
        public decimal OU1_INDION850_CONSP { get; set; }
        public decimal OU1_FFIP_RECPT { get; set; }
        public decimal OU1_FFIP_CONSP { get; set; }
        public decimal OU1_FFIP_STOCK { get; set; }
        public decimal OU1_N8301D_REMARK { get; set; }
        public decimal OU1_N7356_REMARK { get; set; }
        public decimal OU1_N7348_REMARK { get; set; }
        public decimal OU1_N7342_REMARK { get; set; }
        public decimal OU1_N7307_REMARK { get; set; }
        public decimal OU1_STABREX_REMARK { get; set; }
        public string OU1_REMARKS { get; set; }
        public decimal OU1_HSD_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_HCL_G2TANK_LEVEL { get; set; }
        public decimal OU1_CLYE_G2TANK_LEVEL { get; set; }
        public decimal OU1_HLIME_RECPT { get; set; }
        public decimal OU1_HLIME_STOCK { get; set; }
        public decimal OU1_HLIME_CONSP { get; set; }
        public decimal OU1_HCL_G2TANK_STOCK { get; set; }
        public decimal OU1_CLYE_G2TANK_STOCK { get; set; }
        public decimal OU1_CLYE_OTANK_STOCK { get; set; }
        public decimal OU1_HYPO_RECPT_STP { get; set; }
        public decimal OU1_HYPO_CONSP_STP { get; set; }
        public decimal OU1_HYPO_STOCK_STP { get; set; }
        public decimal OU1_N7308_RECPT { get; set; }
        public decimal OU1_N7308_CONSP { get; set; }
        public decimal OU1_N7308_STOCK { get; set; }
        public decimal OU1_BLEACH_POWDER_RECPT { get; set; }
        public decimal OU1_BLEACH_POWDER_CONSP { get; set; }
        public decimal OU1_BLEACH_POWDER_STOCK { get; set; }
        public decimal OU1_PAC_RECPT { get; set; }
        public decimal OU1_PAC_CONSP { get; set; }
        public decimal OU1_PAC_STOCK { get; set; }
        public decimal OU1_NAP315_RECPT { get; set; }
        public decimal OU1_NAP315_CONSP { get; set; }
        public decimal OU1_NAP315_STOCK { get; set; }
        public decimal OU1_NA1005_RECPT { get; set; }
        public decimal OU1_NA1005_CONSP { get; set; }
        public decimal OU1_NA1005_STOCK { get; set; }
        public decimal OU1_NA1002_RECPT { get; set; }
        public decimal OU1_NA1002_CONSP { get; set; }
        public decimal OU1_NA1002_STOCK { get; set; }
        public decimal OU1_RESIN_T42_RECPT { get; set; }
        public decimal OU1_RESIN_T42_CONSP { get; set; }
        public decimal OU1_RESIN_T42_STOCK { get; set; }
        public decimal OU1_RESIN_T23_RECPT { get; set; }
        public decimal OU1_RESIN_T23_CONSP { get; set; }
        public decimal OU1_RESIN_T23_STOCK { get; set; }
        public decimal OU1_N8300_RECPT { get; set; }
        public decimal OU1_N8300_CONSP { get; set; }
        public decimal OU1_N8300_STOCK { get; set; }
        public decimal OU1_N73202_RECPT { get; set; }
        public decimal OU1_N73202_CONSP { get; set; }
        public decimal OU1_N73202_STOCK { get; set; }
        public decimal OU1_PAC_TANKA_LEVEL { get; set; }
        public decimal OU1_PAC_TANKA_STOCK { get; set; }
        public decimal OU1_PAC_TANKB_STOCK { get; set; }
        public decimal OU1_PAC_TANKB_LEVEL { get; set; }
        public decimal OU1_CD2001L_RECPT { get; set; }
        public decimal OU1_CD2001L_CONSP { get; set; }
        public decimal OU1_CD2001L_STOCK { get; set; }
        public decimal OU1_CDDS_HPA_RECPT { get; set; }
        public decimal OU1_CDDS_HPA_CONSP { get; set; }
        public decimal OU1_CDDS_HPA_STOCK { get; set; }
        public decimal OU1_CDDS_2625AC_RECPT { get; set; }
        public decimal OU1_CDDS_2625AC_CONSP { get; set; }
        public decimal OU1_CDDS_2625AC_STOCK { get; set; }
        public decimal OU1_HCL_NEWTANK_STOCK { get; set; }
    }
    public class Func_IN_STK_Dto
    {
        public string OU1_CHEMICAL_ID { get; set; }
        public decimal OU1_CHEMICAL_LEVEL { get; set; }
    }
}
