namespace itsppisapi.Models
{
    public class PGS005Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public string OU1_DATE_MOD { get; set; }
        public decimal OU1_USER_ID { get; set; }
        public string OU1_USER_NAME { get; set; }
        public decimal RW_CALC_STOCK2 { get; set; }
        public decimal OU1_RW_CALC_STOCK { get; set; }
        public decimal OU1_RW_RECPT_KSR { get; set; }
        public decimal OU1_FW_CONSP_BW { get; set; }
        public decimal OU1_RW_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_FW_CONSP_BW_GP2 { get; set; }
        public decimal OU1_RW_TOTAL_RECPT { get; set; }
        public decimal OU1_RW_CONSP_WPT { get; set; }
        public decimal OU1_RW_CONSP_DILUTION { get; set; }
        public decimal OU1_RW_CONSP_DILUTION_GP2 { get; set; }
        public decimal OU1_RW_CONSP_GB { get; set; }
        public decimal OU1_RW_CONSP_GB_GP2 { get; set; }
        public decimal OU1_RW_TOTAL_CONSP { get; set; }
        public decimal FW_STOCK2 { get; set; }
        public decimal OU1_FW_STOCK { get; set; }
        public decimal RW_CONSP_WPT2 { get; set; }
        public decimal OU1_FW_TOTAL_RECPT { get; set; }
        public decimal OU1_FW_CONSP_DMP { get; set; }
        public decimal OU1_FW_CONSP_DMP_GP2 { get; set; }
        public decimal OU1_FW_CONSP_UCT { get; set; }
        public decimal OU1_FW_CONSP_UCT_GP2 { get; set; }
        public decimal OU1_FW_CONSP_ACT { get; set; }
        public decimal OU1_FW_CONSP_ACT_GP2 { get; set; }
        public decimal OU1_FW_CONSP_DW { get; set; }
        public decimal OU1_FW_CONSP_DW_GP2 { get; set; }
        public decimal FW_CONSP_BW2 { get; set; }
        public decimal FW_CONSP_BW2_GP2 { get; set; }
        public decimal OU1_FW_CONSP_SW { get; set; }
        public decimal OU1_FW_CONSP_SW_GP2 { get; set; }
        public decimal OU1_FW_CONSP_FIRE { get; set; }
        public decimal OU1_FW_CONSP_FIRE_GP2 { get; set; }
        public decimal OU1_FW_TOTAL_CONSP_GP1 { get; set; }
        public decimal OU1_FW_TOTAL_CONSP_GP2 { get; set; }
        public decimal OU1_FW_SUM_TOTAL_CONSP { get; set; }
        public decimal OU1_APC_PROD { get; set; }
        public decimal OU1_UPC_PROD { get; set; }
        public decimal OU1_ATC_PROD { get; set; }
        public decimal OU1_UTC_PROD { get; set; }
        public decimal OU1_CTTC_PROD { get; set; }
        public decimal OU1_USC_PROD { get; set; }
        public decimal OU1_APC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_UPC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_ATC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_UTC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_CTTC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_USC_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_TOTAL_CONDENSATE { get; set; }
        public decimal OU1_CONDENSATE_DRAINED_GP1 { get; set; }
        public decimal OU1_NET_CONDENSATE { get; set; }
        public decimal OU1_CONDENSATE_DRAINED_GP2 { get; set; }
        public decimal DMW_STOCK2 { get; set; }
        public decimal OU1_DMW_STOCK { get; set; }
        public decimal FW_CONSP_DMP_GP1 { get; set; }
        public decimal FW_CONSP_DMP_GP2 { get; set; }
        public decimal OU1_REGN_LOSS_DMP_GP1 { get; set; }
        public decimal OU1_REGN_LOSS_DMP_GP2 { get; set; }
        public decimal APC_PROD2 { get; set; }
        public decimal APC_IMPORTF_UNIT2_2 { get; set; }
        public decimal UPC_PROD2 { get; set; }
        public decimal UPC_IMPORTF_UNIT2_2 { get; set; }
        public decimal USC_PROD2 { get; set; }
        public decimal USC_IMPORTF_UNIT2_2 { get; set; }
        public decimal ATC_PROD2 { get; set; }
        public decimal ATC_IMPORTF_UNIT2_2 { get; set; }
        public decimal UTC_PROD2 { get; set; }
        public decimal UTC_IMPORTF_UNIT2_2 { get; set; }
        public decimal CTTC_PROD2 { get; set; }
        public decimal CTTC_IMPORTF_UNIT2_2 { get; set; }
        public decimal CONDENSATE_DRAINED_GP1 { get; set; }
        public decimal CONDENSATE_DRAINED_GP2 { get; set; }
        public decimal OU1_DMW_PROD { get; set; }
        public decimal OU1_DMW_NET_PROD { get; set; }
        public decimal OU1_PW_FEED_MB { get; set; }
        public decimal OU1_REGN_LOSS_MB_GP2 { get; set; }
        public decimal OU1_REGN_LOSS_MB_GP1 { get; set; }
        public decimal OU1_DMW_NET_CONSP { get; set; }
        public decimal PW_STOCK2 { get; set; }
        public decimal OU1_PW_STOCK { get; set; }
        public decimal PW_FEED_MB2 { get; set; }
        public decimal OU1_PW_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_PW_NET_PROD { get; set; }
        public decimal OU1_PW_CONSP_AMM { get; set; }
        public decimal OU1_PW_CONSP_UREA { get; set; }
        public decimal OU1_PW_CONSP_SPG { get; set; }
        public decimal OU1_PW_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_TOTAL_PW_DISTRIBUTION { get; set; }
    }
}
