namespace itsppisapi.Models
{
  public class PES002Model
  {
    public string MINDT { get; set; }
    public string MAXDT { get; set; }
    public string E1_TRANS_DATE { get; set; }
    public string E1_UNIT_ID { get; set; }
    public string E1_DMY_FLG { get; set; }
    public string E1_USER_ID { get; set; }
    public string E1_DATE_MOD { get; set; }
    public string E1_FREEZE_FLG { get; set; }
    public decimal E1_GT1_INT { get; set; }
    public decimal E1_GT1_PROD { get; set; }
    public decimal E1_GT2_INT { get; set; }
    public decimal E1_GT2_PROD { get; set; }
    public decimal E1_RSEB_INT { get; set; }
    public decimal E1_RSEB_PURCHASED { get; set; }
    public decimal E1_LOSS_GEN { get; set; }
    public decimal E1_LOSS_RSEB { get; set; }
    public decimal E1_AMM_INT { get; set; }
    public decimal E1_AMM_CONSP { get; set; }
    public decimal E1_U11_INT { get; set; }
    public decimal E1_U11_CONSP { get; set; }
    public decimal E1_U21_INT { get; set; }
    public decimal E1_U21_CONSP { get; set; }
    public decimal E1_SPG_INT { get; set; }
    public decimal E1_SPG_CONSP { get; set; }
    public decimal E1_SPG_COND_ID { get; set; }
    public decimal E1_SPG_SUB_COND_ID { get; set; }
    public decimal E1_OFFSITE_INT { get; set; }
    public decimal E1_OFFSITE_CONSP { get; set; }
    public decimal E1_OFFSITE_COND_ID { get; set; }
    public decimal E1_OFFSITE_SUB_COND_ID { get; set; }
    public decimal E1_AMM_STORAGE_INT { get; set; }
    public decimal E1_AMM_STORAGE_CONSP { get; set; }
    public decimal E1_UPHS_INT { get; set; }
    public decimal E1_UPHS_CONSP { get; set; }
    public decimal E1_RW_INT { get; set; }
    public decimal E1_RW_CONSP { get; set; }
    public decimal E1_TFR_TO_NEBUS_INT { get; set; }
    public decimal E1_TFR_TO_NEBUS { get; set; }
    public decimal E1_UNIT2_FDR1_INT { get; set; }
    public decimal E1_UNIT2_FDR1_CONSP { get; set; }
    public decimal E1_UNIT2_FDR2_INT { get; set; }
    public decimal E1_UNIT2_FDR2_CONSP { get; set; }
    public decimal E1_UNIT2_BAGG_INT { get; set; }
    public decimal E1_UNIT2_BAGG_CONSP { get; set; }
    public string E1_REMARKS { get; set; }
    public decimal E1_AB_CONSP { get; set; }
    public decimal E1_CPP_CONSP { get; set; }
    public decimal E1_IAC_SPG_CONSP { get; set; }
    public decimal E1_IAC_OFFSITE_CONSP { get; set; }
    public decimal E1_ACT_CONSP { get; set; }
    public decimal E1_UCT_CONSP { get; set; }
    public decimal E1_WPT_CONSP { get; set; }
    public decimal E1_DMP_CONSP { get; set; }
    public decimal E1_ETP_CONSP { get; set; }
    public decimal E1_FIRE_CONSP { get; set; }
    public decimal E1_CIVIL_BLDG_INT { get; set; }
    public decimal E1_CIVIL_BLDG_CONSP { get; set; }
    public decimal E1_CONST_POWER_UNIT2_INT { get; set; }
    public decimal E1_CONST_POWER_UNIT2_CONSP { get; set; }
    public decimal E1_HOUSE_COL_INT { get; set; }
    public decimal E1_HOUSE_COL_CONSP { get; set; }
    public decimal E1_KSR_INT { get; set; }
    public decimal E1_KSR_CONSP { get; set; }
    public decimal E1_TFR_TO_EBUS_INT { get; set; }
    public decimal E1_TFR_TO_EBUS { get; set; }
    public decimal E1_WS_FENCELIGHT_INT { get; set; }
    public decimal E1_WS_FENCELIGHT_CONSP { get; set; }
    public string E1_FREEZE_TIME { get; set; }
    public decimal E1_TOT_GT_GEN { get; set; }
    public decimal E1_TOT_EBUS_CONSP { get; set; }
    public decimal E1_TOT_NEBUS_CONSP { get; set; }
    public decimal E1_UNIT2_OFFSITE_INT { get; set; }
    public decimal E1_UNIT2_OFFSITE_CONSP { get; set; }
    public decimal E1_PUR_PWR_UNIT2_INT { get; set; }
    public decimal E1_PUR_PWR_UNIT2_CONSP { get; set; }
    public decimal E1_NAP_STORAGE_INT { get; set; }
    public decimal E1_HOLDING_POND_INT { get; set; }
    public decimal E1_NAP_STORAGE_CONSP { get; set; }
    public decimal E1_HOLDING_POND_CONSP { get; set; }
    public decimal E1_HOLDING_POND_INT2 { get; set; }
    public decimal E1_HOLDING_POND_CONSP2 { get; set; }
    public decimal E1_OFFSITE_15MVA_INT { get; set; }
    public decimal E1_OFFSITE_15MVA_CONSP { get; set; }
    public decimal E1_OFFSITE_3MVA_INT { get; set; }
    public decimal E1_OFFSITE_3MVA_CONSP { get; set; }
    public decimal E1_GEN_PWR_KSR_INT { get; set; }
    public decimal E1_GEN_PWR_KSR_CONSP { get; set; }
    public decimal E1_GEN_PWR_HOUSE_COL_INT { get; set; }
    public decimal E1_GEN_PWR_HOUSE_COL_CONSP { get; set; }
    public decimal E1_GEN_PWR_CIVIL_BLDG_INT { get; set; }
    public decimal E1_GEN_PWR_CIVIL_BLDG_CONSP { get; set; }
    public decimal E1_GEN_PWR_WS_FENCELIGHT_INT { get; set; }
    public decimal E1_GEN_PWR_WS_FENCELIGHT_CONSP { get; set; }
    public decimal E1_PUR_PWR_UPHS1_INT { get; set; }
    public decimal E1_PUR_PWR_UPHS1_CONSP { get; set; }
    public decimal E1_PUR_PWR_RW_INT { get; set; }
    public decimal E1_PUR_PWR_RW_CONSP { get; set; }
    public decimal E1_PUR_PWR_UPHS2_INT { get; set; }
    public decimal E1_PUR_PWR_UPHS2_CONSP { get; set; }
    public decimal E1_PUR_PWR_3MVA_INT { get; set; }
    public decimal E1_PUR_PWR_3MVA_CONSP { get; set; }
    public decimal E1_PUR_PWR_OTHER_INT { get; set; }
    public decimal E1_PUR_PWR_OTHER_CONSP { get; set; }
    public decimal E1_PUR_PWR_WPT_CONSP { get; set; }
    public decimal E1_PUR_PWR_DMP_CONSP { get; set; }
    public decimal E1_PUR_PWR_ETP_CONSP { get; set; }
    public decimal E1_PUR_PWR_ACT_CONSP { get; set; }
    public decimal E1_PUR_PWR_UCT_CONSP { get; set; }
    public decimal E1_PUR_PWR_IAC_CONSP { get; set; }
    public decimal E1_3MVA_COND_ID { get; set; }
    public decimal E1_3MVA_SUB_COND_ID { get; set; }
    public decimal E1_PUR_PWR_RATE { get; set; }
    public decimal E1_PUR_PWR_NAPSTRG_INT { get; set; }
    public decimal E1_PUR_PWR_NAPSTRG_CONSP { get; set; }
    public decimal E1_PWR_CONSP_E_LOAD { get; set; }
    public decimal E1_PWR_CONSP_NE_LOAD { get; set; }
    public decimal E1_CIVIL_BLDG_CONSP_RATE { get; set; }
    public decimal E1_HOUSE_COL_CONSP_RATE { get; set; }
    public decimal E1_KSR_CONSP_RATE { get; set; }
    public decimal E1_WS_FENCELIGHT_CONSP_RATE { get; set; }
    public decimal E1_PUR_PWR_UPHS1_CONSP_RATE { get; set; }
    public decimal E1_PUR_PWR_RW_CONSP_RATE { get; set; }
    public decimal E1_PUR_PWR_3MVA_CONSP_RATE { get; set; }
    public decimal E1_PUR_PWR_OTHER_CONSP_RATE { get; set; }
    public string E1_PUR_PWR_CONSP_COND { get; set; }
    public decimal E1_PUR_PWR_IND_LOAD { get; set; }
    public decimal E1_PUR_PWR_HOUSE_LOAD { get; set; }
    public decimal E1_PUR_PWR_HOUSE_RDG_CORR { get; set; }
    public decimal E1_PUR_PWR_MAX_DEMAND { get; set; }
    public decimal E1_PUR_PWR_UPSH2_CONSP_RATE { get; set; }
    public decimal E1_PUR_PWR_NAPSTRG_CONSP_RATE { get; set; }
    public decimal E1_PUR_PWR_AVL_BAL_LOAD { get; set; }
    public decimal E1_REVAMP_CONSP_UNIT1 { get; set; }
    public decimal E1_PUR_PWR_SSP_INT { get; set; }
    public decimal E1_PUR_PWR_CONSP_SSP { get; set; }
    public decimal E1_PUR_PWR_SSP_CONSP_RATE { get; set; }
    public decimal E1_IEX_PURCHASED { get; set; }
    public decimal E1_PUR_POWER_TOTAL { get; set; }
    public decimal E1_PUR_PWR_GP3_CONSP { get; set; }
    public decimal E1_PUR_PWR_GP3_CONSP_RATE { get; set; }
    public decimal E1_RECEIPT_UPH2_GP3 { get; set; }
    public decimal E1_PUR_PWR_GP3_INT { get; set; }
    public decimal E1_GT2_EXPORT_GP3_ID { get; set; }
    public decimal E1_RECEIPT_UPH12_TOTAL { get; set; }
    public decimal E1_GT1_EXPORT_GP3_ID { get; set; }
    public decimal E1_RECEIPT_UPH1_GP3 { get; set; }
    public decimal E1_GT1_EXPORT_GP3 { get; set; }
    public decimal E1_GT2_EXPORT_GP3 { get; set; }
    public decimal TXT_TOT_OFFSITE_CONSP { get; set; }
    
    //PRV
    public string PRV_E1_TRANS_DATE { get; set; }
    public string PRV_E1_UNIT_ID { get; set; }
    public string PRV_E1_DMY_FLG { get; set; }
    public string PRV_E1_USER_ID { get; set; }
    public string PRV_E1_DATE_MOD { get; set; }
    public string PRV_E1_FREEZE_FLG { get; set; }
    public decimal PRV_E1_GT1_INT { get; set; }
    public decimal PRV_E1_GT1_PROD { get; set; }
    public decimal PRV_E1_GT2_INT { get; set; }
    public decimal PRV_E1_GT2_PROD { get; set; }
    public decimal PRV_E1_RSEB_INT { get; set; }
    public decimal PRV_E1_RSEB_PURCHASED { get; set; }
    public decimal PRV_E1_LOSS_GEN { get; set; }
    public decimal PRV_E1_LOSS_RSEB { get; set; }
    public decimal PRV_E1_AMM_INT { get; set; }
    public decimal PRV_E1_AMM_CONSP { get; set; }
    public decimal PRV_E1_U11_INT { get; set; }
    public decimal PRV_E1_U11_CONSP { get; set; }
    public decimal PRV_E1_U21_INT { get; set; }
    public decimal PRV_E1_U21_CONSP { get; set; }
    public decimal PRV_E1_SPG_INT { get; set; }
    public decimal PRV_E1_SPG_CONSP { get; set; }
    public decimal PRV_E1_SPG_COND_ID { get; set; }
    public decimal PRV_E1_SPG_SUB_COND_ID { get; set; }
    public decimal PRV_E1_OFFSITE_INT { get; set; }
    public decimal PRV_E1_OFFSITE_CONSP { get; set; }
    public decimal PRV_E1_OFFSITE_COND_ID { get; set; }
    public decimal PRV_E1_OFFSITE_SUB_COND_ID { get; set; }
    public decimal PRV_E1_AMM_STORAGE_INT { get; set; }
    public decimal PRV_E1_AMM_STORAGE_CONSP { get; set; }
    public decimal PRV_E1_UPHS_INT { get; set; }
    public decimal PRV_E1_UPHS_CONSP { get; set; }
    public decimal PRV_E1_RW_INT { get; set; }
    public decimal PRV_E1_RW_CONSP { get; set; }
    public decimal PRV_E1_TFR_TO_NEBUS_INT { get; set; }
    public decimal PRV_E1_TFR_TO_NEBUS { get; set; }
    public decimal PRV_E1_UNIT2_FDR1_INT { get; set; }
    public decimal PRV_E1_UNIT2_FDR1_CONSP { get; set; }
    public decimal PRV_E1_UNIT2_FDR2_INT { get; set; }
    public decimal PRV_E1_UNIT2_FDR2_CONSP { get; set; }
    public decimal PRV_E1_UNIT2_BAGG_INT { get; set; }
    public decimal PRV_E1_UNIT2_BAGG_CONSP { get; set; }
    public string PRV_E1_REMARKS { get; set; }
    public decimal PRV_E1_AB_CONSP { get; set; }
    public decimal PRV_E1_CPP_CONSP { get; set; }
    public decimal PRV_E1_IAC_SPG_CONSP { get; set; }
    public decimal PRV_E1_IAC_OFFSITE_CONSP { get; set; }
    public decimal PRV_E1_ACT_CONSP { get; set; }
    public decimal PRV_E1_UCT_CONSP { get; set; }
    public decimal PRV_E1_WPT_CONSP { get; set; }
    public decimal PRV_E1_DMP_CONSP { get; set; }
    public decimal PRV_E1_ETP_CONSP { get; set; }
    public decimal PRV_E1_FIRE_CONSP { get; set; }
    public decimal PRV_E1_CIVIL_BLDG_INT { get; set; }
    public decimal PRV_E1_CIVIL_BLDG_CONSP { get; set; }
    public decimal PRV_E1_CONST_POWER_UNIT2_INT { get; set; }
    public decimal PRV_E1_CONST_POWER_UNIT2_CONSP { get; set; }
    public decimal PRV_E1_HOUSE_COL_INT { get; set; }
    public decimal PRV_E1_HOUSE_COL_CONSP { get; set; }
    public decimal PRV_E1_KSR_INT { get; set; }
    public decimal PRV_E1_KSR_CONSP { get; set; }
    public decimal PRV_E1_TFR_TO_EBUS_INT { get; set; }
    public decimal PRV_E1_TFR_TO_EBUS { get; set; }
    public decimal PRV_E1_WS_FENCELIGHT_INT { get; set; }
    public decimal PRV_E1_WS_FENCELIGHT_CONSP { get; set; }
    public string PRV_E1_FREEZE_TIME { get; set; }
    public decimal PRV_E1_TOT_GT_GEN { get; set; }
    public decimal PRV_E1_TOT_EBUS_CONSP { get; set; }
    public decimal PRV_E1_TOT_NEBUS_CONSP { get; set; }
    public decimal PRV_E1_UNIT2_OFFSITE_INT { get; set; }
    public decimal PRV_E1_UNIT2_OFFSITE_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_UNIT2_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_UNIT2_CONSP { get; set; }
    public decimal PRV_E1_NAP_STORAGE_INT { get; set; }
    public decimal PRV_E1_HOLDING_POND_INT { get; set; }
    public decimal PRV_E1_NAP_STORAGE_CONSP { get; set; }
    public decimal PRV_E1_HOLDING_POND_CONSP { get; set; }
    public decimal PRV_E1_HOLDING_POND_INT2 { get; set; }
    public decimal PRV_E1_HOLDING_POND_CONSP2 { get; set; }
    public decimal PRV_E1_OFFSITE_15MVA_INT { get; set; }
    public decimal PRV_E1_OFFSITE_15MVA_CONSP { get; set; }
    public decimal PRV_E1_OFFSITE_3MVA_INT { get; set; }
    public decimal PRV_E1_OFFSITE_3MVA_CONSP { get; set; }
    public decimal PRV_E1_GEN_PWR_KSR_INT { get; set; }
    public decimal PRV_E1_GEN_PWR_KSR_CONSP { get; set; }
    public decimal PRV_E1_GEN_PWR_HOUSE_COL_INT { get; set; }
    public decimal PRV_E1_GEN_PWR_HOUSE_COL_CONSP { get; set; }
    public decimal PRV_E1_GEN_PWR_CIVIL_BLDG_INT { get; set; }
    public decimal PRV_E1_GEN_PWR_CIVIL_BLDG_CONSP { get; set; }
    public decimal PRV_E1_GEN_PWR_WS_FENCELIGHT_INT { get; set; }
    public decimal PRV_E1_GEN_PWR_WS_FENCELIGHT_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_UPHS1_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_UPHS1_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_RW_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_RW_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_UPHS2_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_UPHS2_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_3MVA_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_3MVA_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_OTHER_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_OTHER_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_WPT_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_DMP_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_ETP_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_ACT_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_UCT_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_IAC_CONSP { get; set; }
    public decimal PRV_E1_3MVA_COND_ID { get; set; }
    public decimal PRV_E1_3MVA_SUB_COND_ID { get; set; }
    public decimal PRV_E1_PUR_PWR_RATE { get; set; }
    public decimal PRV_E1_PUR_PWR_NAPSTRG_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_NAPSTRG_CONSP { get; set; }
    public decimal PRV_E1_PWR_CONSP_E_LOAD { get; set; }
    public decimal PRV_E1_PWR_CONSP_NE_LOAD { get; set; }
    public decimal PRV_E1_CIVIL_BLDG_CONSP_RATE { get; set; }
    public decimal PRV_E1_HOUSE_COL_CONSP_RATE { get; set; }
    public decimal PRV_E1_KSR_CONSP_RATE { get; set; }
    public decimal PRV_E1_WS_FENCELIGHT_CONSP_RATE { get; set; }
    public decimal PRV_E1_PUR_PWR_UPHS1_CONSP_RATE { get; set; }
    public decimal PRV_E1_PUR_PWR_RW_CONSP_RATE { get; set; }
    public decimal PRV_E1_PUR_PWR_3MVA_CONSP_RATE { get; set; }
    public decimal PRV_E1_PUR_PWR_OTHER_CONSP_RATE { get; set; }
    public string PRV_E1_PUR_PWR_CONSP_COND { get; set; }
    public decimal PRV_E1_PUR_PWR_IND_LOAD { get; set; }
    public decimal PRV_E1_PUR_PWR_HOUSE_LOAD { get; set; }
    public decimal PRV_E1_PUR_PWR_HOUSE_RDG_CORR { get; set; }
    public decimal PRV_E1_PUR_PWR_MAX_DEMAND { get; set; }
    public decimal PRV_E1_PUR_PWR_UPSH2_CONSP_RATE { get; set; }
    public decimal PRV_E1_PUR_PWR_NAPSTRG_CONSP_RATE { get; set; }
    public decimal PRV_E1_PUR_PWR_AVL_BAL_LOAD { get; set; }
    public decimal PRV_E1_REVAMP_CONSP_UNIT1 { get; set; }
    public decimal PRV_E1_PUR_PWR_SSP_INT { get; set; }
    public decimal PRV_E1_PUR_PWR_CONSP_SSP { get; set; }
    public decimal PRV_E1_PUR_PWR_SSP_CONSP_RATE { get; set; }
    public decimal PRV_E1_IEX_PURCHASED { get; set; }
    public decimal PRV_E1_PUR_POWER_TOTAL { get; set; }
    public decimal PRV_E1_PUR_PWR_GP3_CONSP { get; set; }
    public decimal PRV_E1_PUR_PWR_GP3_CONSP_RATE { get; set; }
    public decimal PRV_E1_RECEIPT_UPH2_GP3 { get; set; }
    public decimal PRV_E1_PUR_PWR_GP3_INT { get; set; }
    public decimal PRV_E1_GT2_EXPORT_GP3_ID { get; set; }
    public decimal PRV_E1_RECEIPT_UPH12_TOTAL { get; set; }
    public decimal PRV_E1_GT1_EXPORT_GP3_ID { get; set; }
    public decimal PRV_E1_RECEIPT_UPH1_GP3 { get; set; }
    public decimal PRV_E1_GT1_EXPORT_GP3 { get; set; }
    public decimal PRV_E1_GT2_EXPORT_GP3 { get; set; }
    public decimal PRV_TXT_TOT_OFFSITE_CONSP { get; set; }
  }
}
