namespace itsppisapi.Models
{
    public class POS003Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public string OU1_DATE_MOD { get; set; }
        public dynamic OU1_USER_ID { get; set; }
        public string OU1_USER_NAME { get; set; }

        public dynamic OU1_HCL_RECPT { get; set; }
        public dynamic OU1_HCL_OTANK_LEVEL { get; set; }
        public dynamic OU1_HCL_OTANK_STOCK { get; set; }
        public dynamic OU1_HCL_NTANK_LEVEL { get; set; }
        public dynamic OU1_HCL_NTANK_STOCK { get; set; }
        public dynamic OU1_HCL_STOCK { get; set; }
        public dynamic OU1_HCL_CONSP { get; set; }
        public dynamic OU1_SULACID_RECPT { get; set; }
        public dynamic OU1_SULACID_TANK_LEVEL { get; set; }
        public dynamic OU1_SULACID_STOCK { get; set; }
        public dynamic OU1_SULACID_CONSP { get; set; }
        public dynamic OU1_CLYE_RECPT { get; set; }
        public dynamic OU1_CLYE_TANK_LEVEL { get; set; }
        public dynamic OU1_CLYE_STOCK { get; set; }
        public dynamic OU1_CLYE_CONSP { get; set; }
        public dynamic OU1_HSD_RECPT { get; set; }
        public dynamic OU1_HSD_EDG_LEVEL { get; set; }
        public dynamic OU1_HSD_GT_LEVEL { get; set; }
        // public dynamic OU1_HSD_GT_STOCK { get; set; }
        public dynamic OU1_HSD_NEW_LEVEL { get; set; }
        public dynamic OU1_HSD_STOCK { get; set; }
        public dynamic OU1_HSD_CONSP { get; set; }
        public dynamic OU1_ALUM_RECPT { get; set; }
        public dynamic OU1_ALUM_STOCK { get; set; }
        public dynamic OU1_ALUM_CONSP { get; set; }
        public dynamic OU1_CHLWPT_RECPT { get; set; }
        public dynamic OU1_CHLWPT_STOCK { get; set; }
        public dynamic OU1_CHLWPT_CONSP { get; set; }
        public dynamic OU1_CHLRW_RECPT { get; set; }
        public dynamic OU1_CHLRW_STOCK { get; set; }
        public dynamic OU1_CHLRW_CONSP { get; set; }
        public dynamic OU1_CHLCT_RECPT { get; set; }
        public dynamic OU1_CHLCT_STOCK { get; set; }
        public dynamic OU1_CHLCT_CONSP { get; set; }
        public dynamic OU1_HYPO_RECPT { get; set; }
        public dynamic OU1_HYPO_STOCK { get; set; }
        public dynamic OU1_HYPO_CONSP { get; set; }
        public dynamic OU1_N7356_RECPT { get; set; }
        public dynamic OU1_N7356_STOCK { get; set; }
        public dynamic OU1_N7356_CONSP { get; set; }
        public dynamic OU1_N8301D_RECPT { get; set; }
        public dynamic OU1_N8301D_STOCK { get; set; }
        public dynamic OU1_N8301D_CONSP { get; set; }
        public dynamic OU1_N7342_RECPT { get; set; }
        public dynamic OU1_N7342_STOCK { get; set; }
        public dynamic OU1_N7342_CONSP { get; set; }
        public dynamic OU1_N7307_RECPT { get; set; }
        public dynamic OU1_N7307_STOCK { get; set; }
        public dynamic OU1_N7307_CONSP { get; set; }
        public dynamic OU1_STBX_RECPT { get; set; }
        public dynamic OU1_STBX_STOCK { get; set; }
        public dynamic OU1_STBX_CONSP { get; set; }
        public dynamic OU1_HYDRAZINE_RECPT { get; set; }
        public dynamic OU1_HYDRAZINE_STOCK { get; set; }
        public dynamic OU1_HYDRAZINE_CONSP { get; set; }
        public dynamic OU1_TSP_RECPT { get; set; }
        public dynamic OU1_TSP_STOCK { get; set; }
        public dynamic OU1_TSP_CONSP { get; set; }
        public dynamic OU1_HITECH_RECPT { get; set; }
        public dynamic OU1_HITECH_STOCK { get; set; }
        public dynamic OU1_HITECH_CONSP { get; set; }
        public dynamic OU1_POLYEL_RECPT { get; set; }
        public dynamic OU1_POLYEL_STOCK { get; set; }
        public dynamic OU1_POLYEL_CONSP { get; set; }
        public dynamic OU1_ACT_ALUM_RECPT { get; set; }
        public dynamic OU1_ACT_ALUM_STOCK { get; set; }
        public dynamic OU1_ACT_ALUM_CONSP { get; set; }
        public dynamic OU1_MOLSIEVE_RECPT { get; set; }
        public dynamic OU1_MOLSIEVE_STOCK { get; set; }
        public dynamic OU1_MOLSIEVE_CONSP { get; set; }
        public dynamic OU1_ACT_CARBON_RECPT { get; set; }
        public dynamic OU1_ACT_CARBON_STOCK { get; set; }
        public dynamic OU1_ACT_CARBON_CONSP { get; set; }
        public dynamic OU1_SSF_PEB_RECPT { get; set; }
        public dynamic OU1_SSF_PEB_STOCK { get; set; }
        public dynamic OU1_SSF_PEB_CONSP { get; set; }
        public dynamic OU1_SSF_SAND_RECPT { get; set; }
        public dynamic OU1_SSF_SAND_STOCK { get; set; }
        public dynamic OU1_SSF_SAND_CONSP { get; set; }
        public dynamic OU1_DMP_PEB_RECPT { get; set; }
        public dynamic OU1_DMP_PEB_STOCK { get; set; }
        public dynamic OU1_DMP_PEB_CONSP { get; set; }
        public dynamic OU1_WPT_SAND_RECPT { get; set; }
        public dynamic OU1_WPT_SAND_STOCK { get; set; }
        public dynamic OU1_WPT_SAND_CONSP { get; set; }
        public dynamic OU1_INDION225_RECPT { get; set; }
        public dynamic OU1_INDION225_STOCK { get; set; }
        public dynamic OU1_INDION225_CONSP { get; set; }
        public dynamic OU1_INDION850_RECPT { get; set; }
        public dynamic OU1_INDION850_STOCK { get; set; }
        public dynamic OU1_INDION850_CONSP { get; set; }
        public dynamic OU1_FFIP_RECPT { get; set; }
        public dynamic OU1_FFIP_CONSP { get; set; }
        public dynamic OU1_FFIP_STOCK { get; set; }
        public dynamic OU1_HSD_EXPORTT_UNIT2 { get; set; }
        public string OU1_REMARKS { get; set; }
        public dynamic OU1_HCL_G2TANK_LEVEL { get; set; }
        public dynamic OU1_CLYE_G2TANK_LEVEL { get; set; }
        public dynamic OU1_HLIME_RECPT { get; set; }
        public dynamic OU1_HLIME_STOCK { get; set; }
        public dynamic OU1_HLIME_CONSP { get; set; }
        public dynamic OU1_CLYE_OTANK_STOCK { get; set; }
        public dynamic OU1_HYPO_RECPT_STP { get; set; }
        public dynamic OU1_HYPO_CONSP_STP { get; set; }
        public dynamic OU1_HYPO_STOCK_STP { get; set; }
        public dynamic OU1_N7308_RECPT { get; set; }
        public dynamic OU1_N7308_CONSP { get; set; }
        public dynamic OU1_N7308_STOCK { get; set; }
        public dynamic OU1_BLEACH_POWDER_RECPT { get; set; }
        public dynamic OU1_BLEACH_POWDER_CONSP { get; set; }
        public dynamic OU1_BLEACH_POWDER_STOCK { get; set; }
        public dynamic OU1_PAC_RECPT { get; set; }
        public dynamic OU1_PAC_CONSP { get; set; }
        public dynamic OU1_PAC_STOCK { get; set; }
        public dynamic OU1_NAP315_RECPT { get; set; }
        public dynamic OU1_NAP315_CONSP { get; set; }
        public dynamic OU1_NAP315_STOCK { get; set; }
        public dynamic OU1_NA1005_RECPT { get; set; }
        public dynamic OU1_NA1005_CONSP { get; set; }
        public dynamic OU1_NA1005_STOCK { get; set; }
        public dynamic OU1_N73202_RECPT { get; set; }
        public dynamic OU1_N73202_CONSP { get; set; }
        public dynamic OU1_N73202_STOCK { get; set; }
        public dynamic OU1_PAC_TANKA_LEVEL { get; set; }
        public dynamic OU1_PAC_TANKA_STOCK { get; set; }
        public dynamic OU1_PAC_TANKB_STOCK { get; set; }
        public dynamic OU1_PAC_TANKB_LEVEL { get; set; }
        public dynamic OU1_CD2001L_RECPT { get; set; }
        public dynamic OU1_CD2001L_CONSP { get; set; }
        public dynamic OU1_CD2001L_STOCK { get; set; }
        public dynamic OU1_CDDS_HPA_RECPT { get; set; }
        public dynamic OU1_CDDS_HPA_CONSP { get; set; }
        public dynamic OU1_CDDS_HPA_STOCK { get; set; }
        public dynamic OU1_CDDS_2625AC_RECPT { get; set; }
        public dynamic OU1_CDDS_2625AC_CONSP { get; set; }
        public dynamic OU1_CDDS_2625AC_STOCK { get; set; }
        public dynamic OU1_HCL_NEWTANK_STOCK { get; set; }
        public dynamic OU1_HCL_G2TANK_STOCK { get; set; }
        public dynamic OU1_CLYE_G2TANK_STOCK { get; set; }

        // ------------------------PRV---------------------------------------
        public dynamic PRV_OU1_TRANS_DATE { get; set; }
        public dynamic PRV_OU1_HCL_RECPT { get; set; }
        public dynamic PRV_OU1_HCL_G2TANK_LEVEL { get; set; }
        public dynamic PRV_OU1_HCL_NTANK_LEVEL { get; set; }
        public dynamic PRV_OU1_HCL_NEWTANK_STOCK { get; set; }
        public dynamic PRV_OU1_HCL_STOCK { get; set; }
        public dynamic PRV_OU1_HCL_OTANK_LEVEL { get; set; }
        public dynamic PRV_OU1_HCL_CONSP { get; set; }
        public dynamic PRV_OU1_CLYE_RECPT { get; set; }
        public dynamic PRV_OU1_CLYE_TANK_LEVEL { get; set; }
        public dynamic PRV_OU1_CLYE_G2TANK_LEVEL { get; set; }
        public dynamic PRV_OU1_CLYE_STOCK { get; set; }
        public dynamic PRV_OU1_CLYE_CONSP { get; set; }
        public dynamic PRV_OU1_SULACID_RECPT { get; set; }
        public dynamic PRV_OU1_SULACID_TANK_LEVEL { get; set; }
        public dynamic PRV_OU1_SULACID_STOCK { get; set; }
        public dynamic PRV_OU1_SULACID_CONSP { get; set; }
        public dynamic PRV_OU1_HSD_RECPT { get; set; }
        public dynamic PRV_OU1_HSD_EDG_LEVEL { get; set; }
        public dynamic PRV_OU1_HSD_GT_LEVEL { get; set; }
        public dynamic PRV_OU1_HSD_NEW_LEVEL { get; set; }
        public dynamic PRV_OU1_HSD_EXPORTT_UNIT2 { get; set; }
        public dynamic PRV_OU1_HSD_CONSP { get; set; }
        public dynamic PRV_OU1_HSD_STOCK { get; set; }
        public dynamic PRV_OU1_ALUM_RECPT { get; set; }
        public dynamic PRV_OU1_ALUM_CONSP { get; set; }
        public dynamic PRV_OU1_ALUM_STOCK { get; set; }
        public dynamic PRV_OU1_CHLWPT_RECPT { get; set; }
        public dynamic PRV_OU1_CHLWPT_CONSP { get; set; }
        public dynamic PRV_OU1_CHLWPT_STOCK { get; set; }
        public dynamic PRV_OU1_CHLRW_RECPT { get; set; }
        public dynamic PRV_OU1_CHLRW_CONSP { get; set; }
        public dynamic PRV_OU1_CHLRW_STOCK { get; set; }
        public dynamic PRV_OU1_CHLCT_RECPT { get; set; }
        public dynamic PRV_OU1_CHLCT_CONSP { get; set; }
        public dynamic PRV_OU1_CHLCT_STOCK { get; set; }
        public dynamic PRV_OU1_HYPO_RECPT { get; set; }
        public dynamic PRV_OU1_HYPO_CONSP { get; set; }
        public dynamic PRV_OU1_HYPO_STOCK { get; set; }
        public dynamic PRV_OU1_HYPO_RECPT_STP { get; set; }
        public dynamic PRV_OU1_HYPO_CONSP_STP { get; set; }
        public dynamic PRV_OU1_HYPO_STOCK_STP { get; set; }
        public dynamic PRV_OU1_N7356_RECPT { get; set; }
        public dynamic PRV_OU1_N7356_CONSP { get; set; }
        public dynamic PRV_OU1_N7356_STOCK { get; set; }
        public dynamic PRV_OU1_N8301D_RECPT { get; set; }
        public dynamic PRV_OU1_N8301D_CONSP { get; set; }
        public dynamic PRV_OU1_N8301D_STOCK { get; set; }
        public dynamic PRV_OU1_N7342_RECPT { get; set; }
        public dynamic PRV_OU1_N7342_CONSP { get; set; }
        public dynamic PRV_OU1_N7342_STOCK { get; set; }
        public dynamic PRV_OU1_N7307_RECPT { get; set; }
        public dynamic PRV_OU1_N7307_CONSP { get; set; }
        public dynamic PRV_OU1_N7307_STOCK { get; set; }
        public dynamic PRV_OU1_N7308_RECPT { get; set; }
        public dynamic PRV_OU1_N7308_CONSP { get; set; }
        public dynamic PRV_OU1_N7308_STOCK { get; set; }
        public dynamic PRV_OU1_STBX_RECPT { get; set; }
        public dynamic PRV_OU1_STBX_CONSP { get; set; }
        public dynamic PRV_OU1_STBX_STOCK { get; set; }
        public dynamic PRV_OU1_HYDRAZINE_RECPT { get; set; }
        public dynamic PRV_OU1_HYDRAZINE_CONSP { get; set; }
        public dynamic PRV_OU1_HYDRAZINE_STOCK { get; set; }
        public dynamic PRV_OU1_TSP_RECPT { get; set; }
        public dynamic PRV_OU1_TSP_CONSP { get; set; }
        public dynamic PRV_OU1_TSP_STOCK { get; set; }
        public dynamic PRV_OU1_HITECH_RECPT { get; set; }
        public dynamic PRV_OU1_HITECH_CONSP { get; set; }
        public dynamic PRV_OU1_HITECH_STOCK { get; set; }
        public dynamic PRV_OU1_POLYEL_RECPT { get; set; }
        public dynamic PRV_OU1_POLYEL_CONSP { get; set; }
        public dynamic PRV_OU1_POLYEL_STOCK { get; set; }
        public dynamic PRV_OU1_ACT_ALUM_RECPT { get; set; }
        public dynamic PRV_OU1_ACT_ALUM_CONSP { get; set; }
        public dynamic PRV_OU1_ACT_ALUM_STOCK { get; set; }
        public dynamic PRV_OU1_MOLSIEVE_RECPT { get; set; }
        public dynamic PRV_OU1_MOLSIEVE_CONSP { get; set; }
        public dynamic PRV_OU1_MOLSIEVE_STOCK { get; set; }
        public dynamic PRV_OU1_ACT_CARBON_RECPT { get; set; }
        public dynamic PRV_OU1_ACT_CARBON_CONSP { get; set; }
        public dynamic PRV_OU1_ACT_CARBON_STOCK { get; set; }
        public dynamic PRV_OU1_SSF_PEB_RECPT { get; set; }
        public dynamic PRV_OU1_SSF_PEB_CONSP { get; set; }
        public dynamic PRV_OU1_SSF_PEB_STOCK { get; set; }
        public dynamic PRV_OU1_SSF_SAND_RECPT { get; set; }
        public dynamic PRV_OU1_SSF_SAND_CONSP { get; set; }
        public dynamic PRV_OU1_SSF_SAND_STOCK { get; set; }
        public dynamic PRV_OU1_DMP_PEB_RECPT { get; set; }
        public dynamic PRV_OU1_DMP_PEB_CONSP { get; set; }
        public dynamic PRV_OU1_DMP_PEB_STOCK { get; set; }
        public dynamic PRV_OU1_WPT_SAND_RECPT { get; set; }
        public dynamic PRV_OU1_WPT_SAND_CONSP { get; set; }
        public dynamic PRV_OU1_WPT_SAND_STOCK { get; set; }
        public dynamic PRV_OU1_INDION225_RECPT { get; set; }
        public dynamic PRV_OU1_INDION225_CONSP { get; set; }
        public dynamic PRV_OU1_INDION225_STOCK { get; set; }
        public dynamic PRV_OU1_INDION850_RECPT { get; set; }
        public dynamic PRV_OU1_INDION850_CONSP { get; set; }
        public dynamic PRV_OU1_INDION850_STOCK { get; set; }
        public dynamic PRV_OU1_FFIP_RECPT { get; set; }
        public dynamic PRV_OU1_FFIP_CONSP { get; set; }
        public dynamic PRV_OU1_FFIP_STOCK { get; set; }
        public dynamic PRV_OU1_HLIME_RECPT { get; set; }
        public dynamic PRV_OU1_HLIME_CONSP { get; set; }
        public dynamic PRV_OU1_HLIME_STOCK { get; set; }
        public dynamic PRV_OU1_BLEACH_POWDER_RECPT { get; set; }
        public dynamic PRV_OU1_BLEACH_POWDER_CONSP { get; set; }
        public dynamic PRV_OU1_BLEACH_POWDER_STOCK { get; set; }
        public dynamic PRV_OU1_PAC_TANKA_LEVEL { get; set; }
        public dynamic PRV_OU1_PAC_TANKA_STOCK { get; set; }
        public dynamic PRV_OU1_PAC_TANKB_LEVEL { get; set; }
        public dynamic PRV_OU1_PAC_TANKB_STOCK { get; set; }
        public dynamic PRV_OU1_PAC_RECPT { get; set; }
        public dynamic PRV_OU1_PAC_CONSP { get; set; }
        public dynamic PRV_OU1_PAC_STOCK { get; set; }
        public dynamic PRV_OU1_NAP315_RECPT { get; set; }
        public dynamic PRV_OU1_NAP315_CONSP { get; set; }
        public dynamic PRV_OU1_NAP315_STOCK { get; set; }
        public dynamic PRV_OU1_NA1005_RECPT { get; set; }
        public dynamic PRV_OU1_NA1005_CONSP { get; set; }
        public dynamic PRV_OU1_NA1005_STOCK { get; set; }
        public dynamic PRV_OU1_CD2001L_RECPT { get; set; }
        public dynamic PRV_OU1_CD2001L_CONSP { get; set; }
        public dynamic PRV_OU1_CD2001L_STOCK { get; set; }
        public dynamic PRV_OU1_CDDS_HPA_RECPT { get; set; }
        public dynamic PRV_OU1_CDDS_HPA_CONSP { get; set; }
        public dynamic PRV_OU1_CDDS_HPA_STOCK { get; set; }
        public dynamic PRV_OU1_CDDS_2625AC_RECPT { get; set; }
        public dynamic PRV_OU1_CDDS_2625AC_CONSP { get; set; }
        public dynamic PRV_OU1_CDDS_2625AC_STOCK { get; set; }
        public dynamic PRV_OU1_N73202_RECPT { get; set; }
        public dynamic PRV_OU1_N73202_CONSP { get; set; }
        public dynamic PRV_OU1_N73202_STOCK { get; set; }

        //----------------------------DV-----------------------------

        public dynamic PARM_G_HCL_NDS { get; set; }
        public dynamic PARM_G_HCL_NMF { get; set; }
        public dynamic PARM_G_HCL_ODS { get; set; }
        public dynamic PARM_G_HCL_OMF { get; set; }
        public dynamic PARM_G_SULPH_ACID_MF { get; set; }
        public dynamic PARM_G_HSD_EDG_MF { get; set; }
        public dynamic PARM_G_HSD_GT_MF { get; set; }
        public dynamic PARM_G_HSD_NEWTANK_MF { get; set; }
        public dynamic PARM_G_HSD_NWDEADSTOCK_MF { get; set; }
        public dynamic PARM_G_HCL_G2DS { get; set; }
        public dynamic PARM_G_HCL_G2MF { get; set; }

        public dynamic PARM_OU_HCL_STOCK { get; set; }
        public dynamic parm_ou_clye_stock { get; set; }
        public dynamic PARM_ou_sulacid_stock { get; set; }
        public dynamic parm_ou_hsd_stock { get; set; }
        public dynamic parm_ou_alum_stock { get; set; }
        public dynamic parm_ou_chlwpt_stock { get; set; }
        public dynamic parm_ou_chlrw_stock { get; set; }
        public dynamic parm_ou_chlct_stock { get; set; }
        public dynamic parm_ou_hypo_stock { get; set; }
        public dynamic parm_ou_hypo_stock_stp { get; set; }
        public dynamic parm_ou_n7356_stock { get; set; }
        public dynamic parm_ou_n8301d_stock { get; set; }
        public dynamic Parm_ou_n7342_stock { get; set; }
        public dynamic parm_ou_n7307_stock { get; set; }
        public dynamic parm_ou_n7308_stock { get; set; }
        public dynamic parm_ou_stbx_stock { get; set; }
        public dynamic parm_ou_hydrazine_stock { get; set; }
        public dynamic parm_ou_tsp_stock { get; set; }
        public dynamic parm_ou_hitech_stock { get; set; }
        public dynamic parm_ou_polyel_stock { get; set; }
        public dynamic parm_ou_act_alum_stock { get; set; }
        public dynamic parm_ou_molsieve_stock { get; set; }
        public dynamic parm_ou_act_carbon_stock { get; set; }
        public dynamic parm_ou_ssf_peb_stock { get; set; }
        public dynamic parm_ou_ssf_sand_stock { get; set; }
        public dynamic parm_ou_dmp_peb_stock { get; set; }
        public dynamic parm_ou_wpt_sand_stock { get; set; }
        public dynamic parm_ou_indion225_stock { get; set; }
        public dynamic parm_ou_indion850_stock { get; set; }
        public dynamic parm_ou_ffip_stock { get; set; }
        public dynamic parm_ou_hlime_stock { get; set; }
        public dynamic parm_ou_bleach_powder_stock { get; set; }
        public dynamic PARM_OU_PAC_STOCK { get; set; }
        public dynamic PARM_OU_NAP315_STOCK { get; set; }
        public dynamic PARM_OU_NA1005_STOCK { get; set; }
        public dynamic PARM_OU_CD2001L_STOCK { get; set; }
        public dynamic PARM_OU_CDDS_HPA_STOCK { get; set; }
        public dynamic PARM_OU_CDDS_2625AC_STOCK { get; set; }
        public dynamic PARM_OU_N73202_STOCK { get; set; }

        public dynamic parm_ng_dsg_comp_fact_ab { get; set; }
        public dynamic parm_ng_dsg_comp_fact_gt { get; set; }
        public dynamic parm_dsg_mol_wt { get; set; }
        public dynamic parm_ng_act_comp_fact_ab { get; set; }
        public dynamic parm_ng_act_comp_fact_gt { get; set; }
        public dynamic parm_dsg_temp_gt { get; set; }
        public dynamic parm_dsg_prs_gt { get; set; }
        public dynamic parm_kelvin_temp { get; set; }
        public dynamic parm_dsg_prs_hrsg { get; set; }
        public dynamic parm_dsg_temp_hrsg { get; set; }
        public dynamic parm_cf_nm3_sm3 { get; set; }
    }
    public class Func_IN_STK_Model
    {
        public decimal IN_STK { get; set; }
    }
}
