namespace itsppisapi.Models
{
    public class POS010Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public string OU1_DATE_MOD { get; set; }
        public dynamic OU1_USER_ID { get; set; }
        public string OU1_USER_NAME { get; set; }

        public dynamic OU1_RW_RECPT_KSR_INT { get; set; }
        public dynamic OU1_RW_RECPT_KSR_INT_DIFF { get; set; }
        public dynamic OU1_RW_RECPT_KSR_INT2 { get; set; }
        public dynamic OU1_RW_RECPT_KSR_INT2_DIFF { get; set; }
        public dynamic OU1_RW_KST_32LINE_INT { get; set; }
        public dynamic OU1_RW_KST_32LINE_INT_DIFF { get; set; }
        public dynamic OU1_RW_RECPT_KSR { get; set; }
        public dynamic OU1_RW_EXPORTT_UNIT3 { get; set; }
        public dynamic OU1_FW_CONSP_BW { get; set; }
        public dynamic OU1_BACKWASH_WPT_GP3 { get; set; }
        public dynamic OU1_RW_TOTAL_RECPT { get; set; }
        public dynamic OU1_RW_CONSP_WPT_INT { get; set; }
        public dynamic OU1_RW_CONSP_WPT_INT_DIFF { get; set; }
        public dynamic OU1_RW_CONSP_WPT_INT_NEW { get; set; }
        public dynamic OU1_RW_WPT_CONSP_INT_NEW_DIFF { get; set; }
        public dynamic OU1_RW_CONSP_WPT { get; set; }
        public dynamic OU1_RW_CONSP_GB { get; set; }
        public dynamic OU1_RW_CONSP_GB_GP1 { get; set; }
        public dynamic OU1_RW_CONSP_GB_GP2 { get; set; }
        public dynamic OU1_RW_CONSP_DILUTION { get; set; }
        public dynamic OU1_RW_CONSP_DILUTION_GP1 { get; set; }
        public dynamic OU1_RW_CONSP_DILUTION_GP2 { get; set; }
        public dynamic OU1_RW_TOTAL_CONSP { get; set; }
        public dynamic OU1_RW_R2_TANK_LEVEL { get; set; }
        public dynamic OU1_RW_R2_TANK_STOCK { get; set; }
        public dynamic OU1_RW_R3_TANK_LEVEL { get; set; }
        public dynamic OU1_RW_R3_TANK_STOCK { get; set; }
        public dynamic OU1_RW_CALC_STOCK { get; set; }
        public dynamic OU1_RW_MEAS_STOCK { get; set; }
        public string OU1_REMARKS { get; set; }
        public dynamic OU1_WPT_3_CONS { get; set; }
        public dynamic OU1_WPT_TOTAL { get; set; }
        public dynamic OU1_FW_TANK1_LEVEL { get; set; }
        public dynamic OU1_FW_TANK1_STOCK { get; set; }
        public dynamic OU1_FW_TANK2_LEVEL { get; set; }
        public dynamic OU1_FW_TANK2_STOCK { get; set; }
        public dynamic OU1_FW_TANK3_LEVEL { get; set; }
        public dynamic OU1_FW_TANK3_STOCK { get; set; }
        public dynamic OU1_FW_TANK4_STOCK { get; set; }
        public dynamic OU1_FW_STOCK { get; set; }
        public dynamic OU1_FW_CONSP_DW_INT2 { get; set; }
        public dynamic OU1_FW_CONSP_DW_INT2_DIFF { get; set; }
        public dynamic OU1_FW_CONSP_DW { get; set; }
        public dynamic OU1_FW_CONSP_DW_UNIT2 { get; set; }
        public dynamic OU1_FW_CONSP_SW_INT { get; set; }
        public dynamic OU1_FW_CONSP_SW_DIFF { get; set; }
        public dynamic OU1_FW_CONSP_SW_GPIA { get; set; }
        public dynamic OU1_FW_CONSP_SSP { get; set; }
        public dynamic U2_FW_CONSP_SW_GPI_INT { get; set; }
        public dynamic U2_FW_CONSP_SW_GPI_INT_DIFF { get; set; }
        public dynamic U2_FW_CONSP_SW_GPI { get; set; }
        public dynamic OU1_FW_CONSP_DW_SSP { get; set; }
        public dynamic U2_FW_CONSP_SW_GPII_INT { get; set; }
        public dynamic U2_FW_CONSP_SW_GPII_INT_DIFF { get; set; }
        public dynamic OU1_FW_EXPORTT_UNIT2 { get; set; }
        public dynamic OU1_DW_GP3_UE { get; set; }
        public dynamic OU1_FW_CONSP_SW { get; set; }
        public dynamic OU1_SW_GP3_UE { get; set; }
        public dynamic OU1_FW_CONSP_UCT_INT { get; set; }
        public dynamic OU1_FW_CONSP_UCT_INT_DIFF { get; set; }
        public dynamic OU1_FW_CONSP_UCT_GPI { get; set; }
        public dynamic OU1_FW_GP3_UE { get; set; }
        public dynamic OU1_FIRE_CONSP_UCT_GPI_INT { get; set; }
        public dynamic OU1_FIRE_CONSP_UCT_GPI_INT_DIFF { get; set; }
        public dynamic OU1_FIRE_CONSP_UCT_GPI { get; set; }
        public dynamic OU1_FW_CONSP_UCT { get; set; }
        public dynamic OU1_FW_CONSP_ACT_INT { get; set; }
        public dynamic OU1_FW_GP1_MEAS_ACT_MAKEUP { get; set; }
        public dynamic OU1_FW_CONSP_ACT { get; set; }
        public dynamic OU1_FW_GP2_MEAS_ACT_MAKEUP { get; set; }
        public dynamic OU1_SPG_CT_GP3 { get; set; }
        public dynamic OU1_FW_CONSP_FIRE { get; set; }
        public dynamic OU1_FW_CONSP_FIRE_UNIT2 { get; set; }
        public dynamic OU1_FW_GP1_GP2_SINK { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT1 { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT1_DIFF { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT2 { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT2_DIFF { get; set; }
        public dynamic OU1_FW_CONSP_DMP_GP1 { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT3 { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT3_DIFF { get; set; }
        public dynamic OU1_FW_CONSP_DMP_GP2 { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT4 { get; set; }
        public dynamic OU1_FW_CONSP_DMP_INT4_DIFF { get; set; }
        public dynamic OU1_FW_CONSP_DMP { get; set; }
        public dynamic OU1_FW_CONSP_BW_GPI { get; set; }
        public dynamic OU1_FW_CONSP_BW_GPII { get; set; }
        public dynamic OU1_FW_TOTAL_CONSP { get; set; }
        public dynamic OU1_DMW_PROD_INT1 { get; set; }
        public dynamic OU1_DMW_PROD_INT1_DIFF { get; set; }
        public dynamic OU1_DMW_PROD_INT2 { get; set; }
        public dynamic OU1_DMW_PROD_INT2_DIFF { get; set; }
        public dynamic OU1_DMW_PROD_INT3 { get; set; }
        public dynamic OU1_DMW_PROD_INT3_DIFF { get; set; }
        public dynamic OU1_DMW_PROD { get; set; }
        public dynamic OU1_DMW_MAKEUP_GPII_INT { get; set; }
        public dynamic OU1_DMW_MAKEUP_GPII { get; set; }
        public dynamic OU1_DMW_MAKEUP_GPI { get; set; }
        public dynamic OU1_DMW_TANK1_LEVEL { get; set; }
        public dynamic OU1_DMW_TANK1_STOCK { get; set; }
        public dynamic OU1_DMW_TANK2_LEVEL { get; set; }
        public dynamic OU1_DMW_TANK2_STOCK { get; set; }
        public dynamic OU1_DMW_TANK3_STOCK { get; set; }
        public dynamic OU1_DMW_STOCK { get; set; }
        public dynamic OU1_PW_TANK1_LEVEL { get; set; }
        public dynamic OU1_PW_TANK1_STOCK { get; set; }
        public dynamic OU1_PW_TANK2_LEVEL { get; set; }
        public dynamic OU1_PW_TANK2_STOCK { get; set; }
        public dynamic OU1_PW_TANK3_STOCK_GP3 { get; set; }
        public dynamic OU1_PW_STOCK { get; set; }
        public dynamic OU1_APC_PROD_INT { get; set; }
        public dynamic OU1_APC_PROD_INT_DIFF { get; set; }
        public dynamic OU1_APC_PROD { get; set; }
        public dynamic OU1_UPC_PROD { get; set; }
        public dynamic OU1_UTC_PROD { get; set; }
        public dynamic OU1_ATC_PROD { get; set; }
        public dynamic OU1_USC_PROD { get; set; }
        public dynamic OU1_CTTC_PROD { get; set; }
        public dynamic OU1_COND_EXPORTT_UNIT2 { get; set; }
        public dynamic OU1_TC_TFRT_PW_UNIT1 { get; set; }
        public dynamic OU1_CONDENSATE_DRAINED_GPI { get; set; }
        public dynamic OU1_NET_CONDENSATE { get; set; }
        public dynamic OU1_PW_EXPORTT_UNIT2_TANK { get; set; }
        public dynamic OU1_PW_FEED_EXPORTT_UNIT2 { get; set; }
        public dynamic OU1_PW_FEED_UNIT1 { get; set; }
        public dynamic OU1_PW_GP1_FEED_IMPORT_GP3 { get; set; }
        public dynamic OU1_PW_GP1_FEED_EXPORT_GP3 { get; set; }
        public dynamic OU1_REGN_LOSS_DMP_GP1 { get; set; }
        public dynamic OU1_REGN_LOSS_MB_GP1 { get; set; }
        public dynamic OU1_PW_CONSP_MEEFOG_INT { get; set; }
        public dynamic OU1_PW_CONSP_MEEFOG { get; set; }
        public dynamic OU1_PW_CONSP_SPG_INT { get; set; }
        public dynamic OU1_PW_CONSP_SPG_WO_MEEFOG { get; set; }
        public dynamic OU1_PW_CONSP_SPG { get; set; }
        public dynamic OU1_PW_CONSP_UNIT1_INT { get; set; }
        public dynamic OU1_PW_CONSP_UNIT1 { get; set; }
        public dynamic OU1_PW_CONSP_UREA { get; set; }
        public dynamic OU1_PW_CONSP_AMM { get; set; }
        public dynamic OU1_PW_EXPORTT_GPII { get; set; }
        public dynamic OU1_PW_IMPORTF_UNIT2 { get; set; }
        public dynamic OU1_PW_GP1_EXPORT_GP3 { get; set; }
        public dynamic OU1_PW_GP1_IMPORT_GP3 { get; set; }
        public dynamic OU1_TC_IMPORTF_UNIT2_INT { get; set; }
        public dynamic OU1_TC_IMPORTF_UNIT2 { get; set; }
        public dynamic OU1_SC_IMPORTF_UNIT2_INT { get; set; }
        public dynamic OU1_SC_IMPORTF_UNIT2 { get; set; }
        public dynamic OU1_APC_IMPORTF_UNIT2 { get; set; }
        public dynamic OU1_UPC_IMPORTF_UNIT2 { get; set; }
        public dynamic OU1_COND_EXPORTT_UNIT1 { get; set; }
        public dynamic OU1_TC_TFRT_PW_UNIT2 { get; set; }
        public dynamic OU1_CONDENSATE_DRAINED_GPII { get; set; }
        public dynamic OU1_NET_COND_GPII { get; set; }
        public dynamic OU1_PW_EXPORTT_UNIT1_TANK { get; set; }
        public dynamic OU1_PW_FEED_EXPORTT_UNIT1 { get; set; }
        public dynamic OU1_PW_FEED_UNIT2 { get; set; }
        public dynamic OU1_PW_FEED_IMPORT_GP3 { get; set; }
        public dynamic OU1_PW_GP2_FEED_EXPORT_GP3 { get; set; }
        public dynamic OU1_REGN_LOSS_DMP_GP2 { get; set; }
        public dynamic OU1_REGN_LOSS_MB_GP2 { get; set; }
        public dynamic OU1_PW_EXPORTT_UNIT2 { get; set; }
        public dynamic OU1_PW_IMPORT_GP3 { get; set; }
        public dynamic OU1_PW_GP2_EXPORT_GP3 { get; set; }

        public dynamic OU1_RW_EXPORTT_UNIT2 { get; set; }
        public dynamic OU1_FW_CONSP_DW_INT1 { get; set; }
        public dynamic OU1_FW_IMPORTF_UNIT2_INT { get; set; }
        public dynamic OU1_REGN_LOSS_DMP { get; set; }
        public dynamic OU1_FW_CONSP_MISC_UNIT2 { get; set; }

        public dynamic TXT_CAL_R3_LEVEL { get; set; }
        public dynamic TXT_WPT_RCPT { get; set; }
        public dynamic TXT_FW_CONSP_ACT_GPII { get; set; }
        public dynamic TXT_FW_CONSP_UCT_GPII { get; set; }
        public dynamic TXT_DMW_STOCK_GP1 { get; set; }
        public dynamic TXT_PW_STOCK_GP1 { get; set; }
        public dynamic TXT_TOT_COND_GPI { get; set; }
        public dynamic TXT_COND_IMP_FROM_UNIT2 { get; set; }
        public dynamic TXT_PW_EXPORTT_GP1_TANK { get; set; }
        public dynamic TXT_OU_PW_FEED_EXPORTT_UNIT1 { get; set; }
        public dynamic TXT_DMW_STOCK_GPII { get; set; }
        public dynamic TXT_PW_STOCK_GPII { get; set; }
        public dynamic TXT_TOT_COND_GPII { get; set; }
        public dynamic TXT_COND_IMPORTF_UNIT1 { get; set; }
        public dynamic TXT_PW_TFRF_UNIT1 { get; set; }
        public dynamic TXT_PW_FEED_EXPORTT_UNIT2 { get; set; }
        public dynamic TXT_PW_EXPORTT_UNIT1 { get; set; }
        public dynamic TXT_PW_IMPORTF_UNIT1 { get; set; }

        public dynamic OU1_FW_GP1_SINK { get; set; }
        public dynamic OU1_FW_GPII_SINK { get; set; }
        public dynamic OU1_FW_TOTAL_RECPT { get; set; }
        public dynamic OU1_FW_CONSP_TOTL_UNIT2 { get; set; }
        public dynamic OU1_FW_CONSP_DW_INT1_DIFF { get; set; }

        // ------------------------PRV----------------------
        public dynamic PRV_OU_TRANS_DATE { get; set; }
        public dynamic PRV_OU_RW_RECPT_KSR_INT { get; set; }
        public dynamic PRV_OU_RW_RECPT_KSR_INT2 { get; set; }
        public dynamic PRV_OU_RW_KST_32LINE_INT { get; set; }
        public dynamic PRV_OU_FW_CONSP_BW { get; set; }
        public dynamic PRV_OU_RW_CONSP_WPT_INT { get; set; }
        public dynamic PRV_OU_RW_CONSP_WPT_INT_NEW { get; set; }
        public dynamic PRV_OU_RW_CONSP_GB { get; set; }
        public dynamic PRV_OU_RW_CONSP_DILUTION { get; set; }
        public dynamic PRV_OU_RW_R2_TANK_LEVEL { get; set; }
        public dynamic PRV_OU_RW_R3_TANK_LEVEL { get; set; }
        public string PRV_OU_REMARKS { get; set; }
        public dynamic PRV_OU_FW_TANK1_LEVEL { get; set; }
        public dynamic PRV_OU_FW_TANK2_LEVEL { get; set; }
        public dynamic PRV_OU_FW_TANK3_LEVEL { get; set; }
        public dynamic PRV_OU_FW_CONSP_DW_INT2 { get; set; }
        public dynamic PRV_OU_FW_CONSP_SW_INT { get; set; }
        public dynamic PRV_OU_FW_CONSP_UCT_INT { get; set; }
        public dynamic PRV_OU_FW_GP3_UE { get; set; }
        public dynamic PRV_OU_FIRE_CONSP_UCT_GPI_INT { get; set; }
        public dynamic PRV_OU_FW_CONSP_ACT_INT { get; set; }
        public dynamic PRV_OU_FW_CONSP_FIRE { get; set; }
        public dynamic PRV_OU_FW_CONSP_FIRE_UNIT2 { get; set; }
        public dynamic PRV_OU_FW_CONSP_DMP_INT1 { get; set; }
        public dynamic PRV_OU_FW_CONSP_DMP_INT2 { get; set; }
        public dynamic PRV_OU_FW_CONSP_DMP_INT3 { get; set; }
        public dynamic PRV_OU_FW_CONSP_DMP_INT4 { get; set; }
        public dynamic PRV_OU_DMW_PROD_INT1 { get; set; }
        public dynamic PRV_OU_DMW_PROD_INT2 { get; set; }
        public dynamic PRV_OU_DMW_PROD_INT3 { get; set; }
        public dynamic PRV_OU_DMW_MAKEUP_GPII_INT { get; set; }
        public dynamic PRV_OU_DMW_TANK1_LEVEL { get; set; }
        public dynamic PRV_OU_DMW_TANK2_LEVEL { get; set; }
        public dynamic PRV_OU_PW_TANK1_LEVEL { get; set; }
        public dynamic PRV_OU_PW_TANK2_LEVEL { get; set; }
        public dynamic PRV_OU_APC_PROD_INT { get; set; }
        public dynamic PRV_OU_COND_EXPORTT_UNIT2 { get; set; }
        public dynamic PRV_OU_TC_TFRT_PW_UNIT1 { get; set; }
        public dynamic PRV_OU_CONDENSATE_DRAINED_GPI { get; set; }
        public dynamic PRV_OU_PW_EXPORTT_UNIT2_TANK { get; set; }
        public dynamic PRV_OU_PW_FEED_EXPORTT_UNIT2 { get; set; }
        public dynamic PRV_OU_PW_GP1_FEED_IMPORT_GP3 { get; set; }
        public dynamic PRV_OU_PW_GP1_FEED_EXPORT_GP3 { get; set; }
        public dynamic PRV_OU_PW_CONSP_MEEFOG_INT { get; set; }
        public dynamic PRV_OU_PW_CONSP_SPG_INT { get; set; }
        public dynamic PRV_OU_PW_CONSP_UNIT1_INT { get; set; }
        public dynamic PRV_OU_PW_EXPORTT_GPII { get; set; }
        public dynamic PRV_OU_PW_IMPORTF_UNIT2 { get; set; }
        public dynamic PRV_OU_PW_GP1_EXPORT_GP3 { get; set; }
        public dynamic PRV_OU_PW_GP1_IMPORT_GP3 { get; set; }
        public dynamic PRV_OU_TC_IMPORTF_UNIT2_INT { get; set; }
        public dynamic PRV_OU_SC_IMPORTF_UNIT2_INT { get; set; }
        public dynamic PRV_OU_COND_EXPORTT_UNIT1 { get; set; }
        public dynamic PRV_OU_TC_TFRT_PW_UNIT2 { get; set; }
        public dynamic PRV_OU_CONDENSATE_DRAINED_GPII { get; set; }
        public dynamic PRV_OU_PW_EXPORTT_UNIT1_TANK { get; set; }
        public dynamic PRV_OU_PW_FEED_EXPORTT_UNIT1 { get; set; }
        public dynamic PRV_OU_PW_FEED_IMPORT_GP3 { get; set; }
        public dynamic PRV_OU_PW_GP2_FEED_EXPORT_GP3 { get; set; }
        public dynamic PRV_OU_PW_IMPORT_GP3 { get; set; }
        public dynamic PRV_OU_PW_GP2_EXPORT_GP3 { get; set; }

        // ------------------------DV----------------------
        public dynamic PARM_G_MF_KSR_RCPT { get; set; }
        public dynamic DIS_OU1_HS_CONSP_CTT { get; set; }
        public dynamic PARM_G_MF_WPT_CONSP { get; set; }
        public dynamic PARM_G_MF_RW_R2 { get; set; }
        public dynamic PARM_G_CONST_STOCK_R2 { get; set; }
        public dynamic PARM_G_MF_RW_R3 { get; set; }
        public dynamic PARM_G_CONST_STOCK_FWT { get; set; }
        public dynamic PARM_G_MF_DW_INT1 { get; set; }
        public dynamic PARM_G_MF_DW_INT2 { get; set; }
        public dynamic PARM_G_ADD_CHLRN_WTR { get; set; }
        public dynamic PARM_G_MF_SW { get; set; }
        public dynamic PARM_G_MF_DMW_TANK { get; set; }
        public dynamic parm_hs_consp_ctt_ph { get; set; }
        public dynamic parm_hs_consp_uct_ph { get; set; }
        public dynamic parm_rw_gb_consp_per_gpii { get; set; }
        public dynamic parm_rw_dil_consp_per_gpii { get; set; }
        public dynamic PARM_G_MF_SW_GPIA { get; set; }
        public dynamic parm_G_MF_PW_MEEFOG { get; set; }
        public dynamic s_water_process_consp { get; set; }
        public dynamic OU3_MAKEUP_SPG_CT_DIFF { get; set; }
        public dynamic PARM_CALC_STK_PREV_DAY { get; set; }
        public dynamic PARM_PW_TANK1_STK_PREV_DAY { get; set; }
        public dynamic PARM_PW_TANK2_STK_PREV_DAY { get; set; }
        public dynamic PARM_DMW_TANK1_STK_PREV_DAY { get; set; }
        public dynamic PARM_DMW_TANK2_STK_PREV_DAY { get; set; }

        public dynamic PARM_FW_STOCK_PREV_DAY { get; set; }
        public dynamic parm_dm1_int { get; set; }

    }
}
