namespace itsppisapi.Models
{
    public class POS009Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public string OU1_DATE_MOD { get; set; }
        public dynamic OU1_USER_ID { get; set; }
        public string OU1_USER_NAME { get; set; }

        public decimal OU1_AB1_KS_PROD_INT { get; set; }
        public decimal OU1_AB1_KS_PROD { get; set; }
        public decimal OU1_AB2_KS_PROD_INT { get; set; }
        public decimal OU1_AB2_KS_PROD { get; set; }
        public decimal OU1_KS_REC_HRSG3 { get; set; }
        public decimal OU1_TOTAL_KS_PROD { get; set; }
        public decimal OU1_KS_IMPORTF_UNIT2 { get; set; }
        public decimal OU1_TOTAL_KS_AVAILABLE { get; set; }
        public decimal OU1_KS_EXP_INT { get; set; }
        public decimal OU1_KS_EXP { get; set; }
        public decimal OU1_KS_HS_LETDOWN { get; set; }
        public decimal OU1_KS_EXPORTT_UNIT2_INT { get; set; }
        public decimal OU1_KS_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_KS_CONSP_VENTING { get; set; }
        public decimal OU1_KS_CONSP_REVAMP_UNIT1 { get; set; }
        public decimal OU1_KS_CONSP_AMM { get; set; }
        public decimal OU1_KS_TOT_CONSP { get; set; }
        public decimal OU1_IMPORT_KS_CONSP_UREA { get; set; }
        public decimal OU1_IMPORT_KS_CONSP_AMM { get; set; }
        public string OU1_REMARKS_D { get; set; }
        public string OU1_REMARKS_M { get; set; }
        public decimal OU1_HS_PRS_MPBFP { get; set; }
        public decimal OU1_HS_TEMP_MPBFP { get; set; }
        public decimal TXT_KS_CONSP_DISS { get; set; }
        public decimal OU1_KS_CONSP_UREA { get; set; }
        public decimal OU1_HS_CF_MPBFP { get; set; }
        public decimal OU1_HS_PRS_FD1 { get; set; }
        public decimal OU1_HS_TEMP_FD1 { get; set; }
        public decimal OU1_HS_CF_FD1 { get; set; }
        public decimal OU1_HS_PRS_FD2 { get; set; }
        public decimal OU1_HS_TEMP_FD2 { get; set; }
        public decimal OU1_HS_CF_FD2 { get; set; }
        public decimal OU1_HS_PRS_HPBFP { get; set; }
        public decimal OU1_HS_TEMP_HPBFP { get; set; }
        public decimal OU1_HS_CF_HPBFP { get; set; }
        public decimal OU1_HS_PRS_TP801A { get; set; }
        public decimal OU1_HS_TEMP_TP801A { get; set; }
        public decimal OU1_HS_CF_TP801A { get; set; }
        public decimal OU1_HS_PRS_TP801B { get; set; }
        public decimal OU1_HS_TEMP_TP801B { get; set; }
        public decimal OU1_HS_CF_TP801B { get; set; }
        public decimal OU1_HS_PRS_TP933A { get; set; }
        public decimal OU1_HS_TEMP_TP933A { get; set; }
        public decimal OU1_HS_CF_TP933A { get; set; }
        public decimal OU1_HS_PRS_TP933B { get; set; }
        public decimal OU1_HS_TEMP_TP933B { get; set; }
        public decimal OU1_HS_CF_TP933B { get; set; }
        public decimal OU1_HS_PRS_TP5933C { get; set; }
        public decimal OU1_HS_TEMP_TP5933C { get; set; }
        public decimal OU1_HS_CF_TP5933C { get; set; }
        public decimal OU1_HS_PRS_TP808B { get; set; }
        public decimal OU1_HS_TEMP_TP808B { get; set; }
        public decimal OU1_HS_CF_TP808B { get; set; }
        public decimal OU1_HS_PRS_TP808C { get; set; }
        public decimal OU1_HS_TEMP_TP808C { get; set; }
        public decimal OU1_HS_CF_TP808C { get; set; }
        public decimal OU1_HS_VAM_AVG_FLOW { get; set; }
        public decimal OU1_HS_VAM_RUN_HRS { get; set; }
        public decimal OU1_HS_HRSG1_PROD_INT { get; set; }
        public decimal OU1_HS_PROD_INCL_VAM_CONSP { get; set; }
        public decimal OU1_HS_HRSG2_PROD_INT { get; set; }
        public decimal OU1_HS_HRSG2_PROD { get; set; }
        public decimal OU1_HS_CONSP_VAM { get; set; }
        public decimal OU1_HS_HRSG1_PROD { get; set; }
        public decimal TXT_KS_HS_PRDS { get; set; }
        public decimal OU1_TOTAL_HS_PROD { get; set; }
        public decimal OU1_HS_EXP_INT { get; set; }
        public decimal OU1_HS_EXP_SPG { get; set; }
        public decimal OU1_HS_CONSP_MPBFW_INT { get; set; }
        public decimal OU1_HS_CONSP_MPBFW_INT_DIFF { get; set; }
        public decimal OU1_HS_CONSP_MPBFW { get; set; }
        public decimal OU1_HS_CONSP_FD1_INT { get; set; }
        public decimal OU1_HS_CONSP_FD1_INT_DIFF { get; set; }
        public decimal OU1_HS_CONSP_FD1 { get; set; }
        public decimal OU1_HS_CONSP_FD2_INT { get; set; }
        public decimal OU1_HS_CONSP_FD2_INT_DIFF { get; set; }
        public decimal OU1_HS_CONSP_FD2 { get; set; }
        public decimal OU1_HS_LS_LETDOWN { get; set; }
        public decimal OU1_HS_CONSP_NPT { get; set; }
        public decimal OU1_HS_CONSP_ATOMIZING { get; set; }
        public decimal OU1_HS_CONSP_MFT { get; set; }
        public decimal OU1_HS_CONSP_HPBFW_INT { get; set; }
        public decimal OU1_HS_CONSP_HPBFW_INT_DIFF { get; set; }
        public decimal OU1_HS_CONSP_HPBFW { get; set; }
        public decimal OU1_HS_AVG_FLW_TP801A { get; set; }
        public decimal OU1_HS_CONSP_TP801A { get; set; }
        public decimal OU1_HS_AVG_FLW_TP801B { get; set; }
        public decimal OU1_HS_CONSP_TP801B { get; set; }
        public decimal OU1_HS_AVG_FLW_TP933A { get; set; }
        public decimal OU1_HS_CONSP_TP933A { get; set; }
        public decimal OU1_HS_AVG_FLW_TP933B { get; set; }
        public decimal OU1_HS_CONSP_TP933B { get; set; }
        public decimal OU1_HS_TP5933C_INT { get; set; }
        public decimal OU1_HS_TP5933C_INT_DIFF { get; set; }
        public decimal OU1_HS_CONSP_PWT_GP2 { get; set; }
        public decimal OU1_HS_TP808B_INT { get; set; }
        public decimal OU1_HS_TP808B_INT_DIFF { get; set; }
        public decimal OU1_HS_CONSP_TP808B { get; set; }
        public decimal OU1_HS_TP808C_INT { get; set; }
        public decimal OU1_HS_TP808C_INT_DIFF { get; set; }
        public decimal OU1_HS_CONSP_TP808C { get; set; }
        public decimal OU1_HS_INTERNAL_CONSP { get; set; }
        public decimal OU1_HS_CONSP_VENTING { get; set; }
        public decimal OU1_HS_CONSP_REVAMP_UNIT1 { get; set; }
        public decimal OU1_HS_CONSP_UREA { get; set; }
        public decimal OU1_HS_CONSP_AMM { get; set; }
        public decimal OU1_HS_TOT_CONSP { get; set; }
        public decimal OU1_LS_INT_PROD_BF_BL { get; set; }
        public decimal OU1_LS_EXP_INT { get; set; }
        public decimal OU1_LS_EXP_INT_DIFF { get; set; }
        public decimal OU1_LS_CONSP_DEARATOR { get; set; }
        public decimal OU1_LS_INT_PROD_AF_BL { get; set; }
        public decimal OU1_TOTAL_LS_PROD { get; set; }
        public decimal OU1_LS_EXPORTT_UNIT2_INT { get; set; }
        public decimal OU1_LS_EXPORTT_UNIT2 { get; set; }
        public decimal OU1_LS_CONSP_VENTING { get; set; }
        public decimal OU1_LS_EXPORT_GP3 { get; set; }
        public decimal TXT_LS_CONSP_AMM { get; set; }
        public decimal OU1_LS_CONSP_UREA { get; set; }
        public decimal OU1_LS_TOT_CONSP { get; set; }
        public decimal OU1_LS_IMPORTF_UNIT2_INT { get; set; }
        public decimal OU1_KS_GP3_EXPORTT_UNIT2 { get; set; }

        // -----------------PRV---------------------
        public string PRV_OU_TRANS_DATE { get; set; }
        public decimal PRV_OU_AB1_KS_PROD_INT { get; set; }
        public decimal PRV_OU_AB2_KS_PROD_INT { get; set; }
        public decimal PRV_OU_KS_EXP_INT { get; set; }
        public decimal PRV_OU_KS_EXPORTT_UNIT2_INT { get; set; }
        public decimal PRV_OU_KS_CONSP_VENTING { get; set; }
        public decimal PRV_OU_KS_CONSP_REVAMP_UNIT1 { get; set; }
        public decimal PRV_OU_IMPORT_KS_CONSP_UREA { get; set; }
        public string PRV_OU_REMARKS { get; set; }
        public decimal PRV_OU_HS_PRS_MPBFP { get; set; }
        public decimal PRV_OU_HS_TEMP_MPBFP { get; set; }
        public decimal PRV_OU_HS_PRS_FD1 { get; set; }
        public decimal PRV_OU_HS_TEMP_FD1 { get; set; }
        public decimal PRV_OU_HS_PRS_FD2 { get; set; }
        public decimal PRV_OU_HS_TEMP_FD2 { get; set; }
        public decimal PRV_OU_HS_PRS_HPBFP { get; set; }
        public decimal PRV_OU_HS_TEMP_HPBFP { get; set; }
        public decimal PRV_OU_HS_PRS_TP801A { get; set; }
        public decimal PRV_OU_HS_TEMP_TP801A { get; set; }
        public decimal PRV_OU_HS_PRS_TP801B { get; set; }
        public decimal PRV_OU_HS_TEMP_TP801B { get; set; }
        public decimal PRV_OU_HS_PRS_TP933A { get; set; }
        public decimal PRV_OU_HS_TEMP_TP933A { get; set; }
        public decimal PRV_OU_HS_PRS_TP933B { get; set; }
        public decimal PRV_OU_HS_TEMP_TP933B { get; set; }
        public decimal PRV_OU_HS_PRS_TP5933C { get; set; }
        public decimal PRV_OU_HS_TEMP_TP5933C { get; set; }
        public decimal PRV_OU_HS_PRS_TP808B { get; set; }
        public decimal PRV_OU_HS_TEMP_TP808B { get; set; }
        public decimal PRV_OU_HS_CF_TP808B { get; set; }
        public decimal PRV_OU_HS_PRS_TP808C { get; set; }
        public decimal PRV_OU_HS_TEMP_TP808C { get; set; }
        public decimal PRV_OU_HS_VAM_AVG_FLOW { get; set; }
        public decimal PRV_OU_HS_VAM_RUN_HRS { get; set; }
        public decimal PRV_OU_HS_HRSG1_PROD_INT { get; set; }
        public decimal PRV_OU_HS_HRSG2_PROD_INT { get; set; }
        public decimal PRV_OU_HS_EXP_INT { get; set; }
        public decimal PRV_OU_HS_CONSP_MPBFW_INT { get; set; }
        public decimal PRV_OU_HS_CONSP_FD1_INT { get; set; }
        public decimal PRV_OU_HS_CONSP_FD2_INT { get; set; }
        public decimal PRV_OU_HS_LS_LETDOWN { get; set; }
        public decimal PRV_OU_HS_CONSP_HPBFW_INT { get; set; }
        public decimal PRV_OU_HS_AVG_FLW_TP801A { get; set; }
        public decimal PRV_OU_HS_AVG_FLW_TP801B { get; set; }
        public decimal PRV_OU_HS_AVG_FLW_TP933A { get; set; }
        public decimal PRV_OU_HS_AVG_FLW_TP933B { get; set; }
        public decimal PRV_OU_HS_TP5933C_INT { get; set; }
        public decimal PRV_OU_HS_TP808B_INT { get; set; }
        public decimal PRV_OU_HS_TP808C_INT { get; set; }
        public decimal PRV_OU_HS_CONSP_VENTING { get; set; }
        public decimal PRV_OU_HS_CONSP_REVAMP_UNIT1 { get; set; }
        public decimal PRV_OU_LS_EXP_INT { get; set; }
        public decimal PRV_OU_LS_EXPORTT_UNIT2_INT { get; set; }
        public decimal PRV_OU_LS_CONSP_VENTING { get; set; }
        public decimal PRV_OU_LS_IMPORTF_UNIT2_INT { get; set; }


        // ----------------DV-------------------------
        public decimal OU3_KS_STEAM_SUPPLY_GP1_2 { get; set; }
        public decimal parm_aval_prs_hpbfw { get; set; }
        public decimal parm_dsgnd_prs_hpbfw { get; set; }
        public decimal parm_aval_prs_mpbfw { get; set; }
        public decimal parm_dsgnd_prs_mpbfw { get; set; }
        public decimal parm_aval_prs_fd { get; set; }
        public decimal parm_dsgnd_prs_fd { get; set; }
        public decimal parm_hs_consp_ctt_ph { get; set; }
        public decimal parm_hs_consp_uct_ph { get; set; }
        public decimal parm_hs_consp_pwt_gp2_ph { get; set; }
        public decimal parm_hs_consp_pwt_ph { get; set; }
        public decimal parm_hs_consp_npt_ph { get; set; }
        public decimal parm_bfw_enthalpy { get; set; }
        public decimal parm_bfw_temp { get; set; }
        public decimal parm_ls_stm_enthalpy { get; set; }
        public decimal parm_cf_atomzing_stm { get; set; }
        public decimal parm_hs_consp_mft_ph { get; set; }
        public decimal parm_npt_pump_run_hrs { get; set; }
        public decimal parm_ou1_ab_nap { get; set; }
        public decimal parm_mft_pump_run_hrs { get; set; }
        public decimal parm_tp801a_pump_run_hrs { get; set; }
        public decimal parm_tp801b_pump_run_hrs { get; set; }
        public decimal parm_tp933a_pump_run_hrs { get; set; }
        public decimal parm_tp933b_pump_run_hrs { get; set; }
    }
    public class Func_HS_CF_CALC_Model
    {
        public decimal IN_CF { get; set; }
    }
}
