namespace itsppisapi.Models
{
    public class POS007Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public string OU1_DATE_MOD { get; set; }
        public dynamic OU1_USER_ID { get; set; }
        public string OU1_USER_NAME { get; set; }

        public decimal OU1_NPIT_INT { get; set; }
        public decimal OU1_NPIT_INT_DIFF { get; set; }
        public decimal OU1_NPIT_NEW_INT { get; set; }
        public decimal OU1_NPIT_NEW_INT_DIFF { get; set; }
        public decimal OU1_ACT_BD_UNIT1_INT { get; set; }
        public decimal OU1_NPIT_INT_DIFF_TOTAL { get; set; }
        public decimal OU1_UCT_BD_UNIT1_INT { get; set; }
        public decimal OU1_ACT_BD_ETP { get; set; }
        public decimal OU1_UCT_BD_ETP { get; set; }
        public decimal OU1_KSR_INT { get; set; }
        public decimal OU1_KSR_INT_DIFF { get; set; }
        public decimal OU1_KSR { get; set; }
        public decimal OU1_EFFL_HP_TO_GB_INT { get; set; }
        public decimal OU1_EFFL_HP_TO_GB_INT_DIFF { get; set; }
        public decimal OU1_EFFL_HP_TO_GB { get; set; }
        public decimal OU1_OILY_EFFL_INT { get; set; }
        public decimal OU1_OILY_EFFL_INT_DIFF { get; set; }
        public decimal OU1_OILY_EFFL_ETP { get; set; }
        public decimal OU1_ACT_BW_ETP { get; set; }
        public decimal OU1_UCT_BW_ETP { get; set; }
        public decimal OU1_ACT_BD { get; set; }
        public decimal OU1_UCT_BD { get; set; }
        public decimal OU1_OIL_WATER_EFFL_ETP { get; set; }
        public decimal OU1_EFFL_TO_GB { get; set; }
        public decimal OU1_TOTAL_HP_CONSP { get; set; }
        public decimal OU1_TOT_EFF_FRM_ETP { get; set; }
        public decimal OU1_HP_EAST_LEVEL { get; set; }
        public decimal OU1_HP_EAST_STOCK { get; set; }
        public decimal OU1_HP_WEST_LEVEL { get; set; }
        public decimal OU1_HP_WEST_STOCK { get; set; }
        public decimal OU1_500PIT_GEN { get; set; }
        public decimal TXT_EFFL_FROM_100M3 { get; set; }
        public decimal OU1_HP_RECIPT_ETP { get; set; }
        public decimal OU1_BAGG_GEN { get; set; }
        public decimal OU1_TOTAL_HP_RECIPT { get; set; }
        public decimal OU1_HP_DISTRIBUTION_KSR { get; set; }
        public decimal OU1_HP_DISTRIBUTION_GB { get; set; }
        public decimal OU1_EFFL_NET_DISCHARGE { get; set; }
        public decimal OU1_AVG_HP_DISTRIBUTION_KSR { get; set; }
        public decimal OU1_AVG_HP_DISTRIBUTION_GB { get; set; }
        public decimal OU1_GB_DISTRIBUTION_ETP { get; set; }
        public decimal OU1_GB_DISTRIBUTION_HP { get; set; }
        public decimal OU1_FROM_STP { get; set; }
        public decimal OU1_SUM_GB_DISTRIBUTION { get; set; }
        public decimal OU1_STP_EFFL_RECYCLED { get; set; }
        public decimal OU1_CLEAR_RATE { get; set; }
        public decimal OU1_OILY_SLUDGE { get; set; }
        public decimal OU1_WPT { get; set; }
        public decimal OU1_NEW_STP { get; set; }
        public decimal OU1_OLD_STP { get; set; }
        public decimal OU1_STP { get; set; }
        public decimal OU1_50PIT_GEN { get; set; }
        public decimal OU1_EFFL_FROM_100M3 { get; set; }
        public decimal OU1_EFFL_RECYCLE_100M3 { get; set; }
        public decimal OU1_OLD_STP_INT { get; set; }
        public decimal OU1_OLD_STP_INPUT { get; set; }
        public decimal OU1_NEW_STP_INT { get; set; }
        public decimal OU1_NEW_STP_INPUT { get; set; }
        public decimal OU1_STP_INPUT_TOT { get; set; }
        public decimal TXT_FROM_STP { get; set; }
        public decimal OU1_STP_DISCHARGE_RECYCLED { get; set; }
        public decimal ou1_hp_stock { get; set; }

        // --------------------------PRV-------------------------------
        public string PRV_OU_TRANS_DATE { get; set; }
        public decimal PRV_OU_NPIT_INT { get; set; }
        public decimal PRV_OU_NPIT_NEW_INT { get; set; }
        public decimal PRV_OU_ACT_BD_UNIT1_INT { get; set; }
        public decimal PRV_OU_UCT_BD_UNIT1_INT { get; set; }
        public decimal PRV_OU_KSR_INT { get; set; }
        public decimal PRV_OU_EFFL_HP_TO_GB_INT { get; set; }
        public decimal PRV_OU_OILY_EFFL_INT { get; set; }
        public decimal PRV_OU_HP_EAST_LEVEL { get; set; }
        public decimal PRV_OU_HP_WEST_LEVEL { get; set; }
        public decimal PRV_OU_500PIT_GEN { get; set; }
        public decimal PRV_OU_CLEAR_RATE { get; set; }
        public decimal PRV_OU_OILY_SLUDGE { get; set; }
        public decimal PRV_OU_WPT { get; set; }
        public decimal PRV_OU_NEW_STP { get; set; }
        public decimal PRV_OU_STP { get; set; }
        public decimal PRV_OU_50PIT_GEN { get; set; }
        public decimal PRV_OU_EFFL_RECYCLE_100M3 { get; set; }
        public decimal PRV_OU_OLD_STP_INT { get; set; }
        public decimal PRV_OU_NEW_STP_INT { get; set; }
        public decimal PRV_OU_STP_DISCHARGE_RECYCLED { get; set; }

        // --------------------------DV-------------------------------
        public decimal parm_npit_etp { get; set; }
        public decimal parm_hp_etp { get; set; }
        public decimal parm_ksr_etp { get; set; }
        public decimal parm_p822_ph_etp { get; set; }
        public decimal parm_p823_ph_etp { get; set; }
        public decimal parm_poily_ph_etp { get; set; }
        public decimal parm_p50pita_ph_etp { get; set; }
        public decimal parm_p50pitb_ph_etp { get; set; }
        public decimal parm_p50pitc_ph_etp { get; set; }
        public decimal parm_p50pitd_ph_etp { get; set; }
        public decimal parm_p500pita_ph_etp { get; set; }
        public decimal parm_p500pitb_ph_etp { get; set; }
        public decimal parm_p500pitc_ph_etp { get; set; }
        public decimal parm_p500pitd_ph_etp { get; set; }
        public decimal parm_p500pite_ph_etp { get; set; }
        public decimal parm_p500pitf_ph_etp { get; set; }
        public decimal parm_pstpa_ph_etp { get; set; }
        public decimal parm_pstpb_ph_etp { get; set; }
        public decimal parm_pstpc_ph_etp { get; set; }
        public decimal parm_pstpd_ph_etp { get; set; }
        public decimal PARM_BAGG_EASTA_PH { get; set; }
        public decimal PARM_BAGG_EASTB_PH { get; set; }
        public decimal PARM_BAGG_WESTA_PH { get; set; }
        public decimal PARM_BAGG_WESTB_PH { get; set; }
        public decimal parm_100m3_old_pump_ph_etp { get; set; }
        public decimal parm_p6752a_ph_etp { get; set; }
        public decimal parm_p6752b_ph_etp { get; set; }
        public decimal parm_p6752c_ph_etp { get; set; }
        public decimal parm_p6751pita_ph_etp { get; set; }
        public decimal parm_p6751pitb_ph_etp { get; set; }
        public decimal parm_p6751pitc_ph_etp { get; set; }
        public decimal parm_effl_recycle_ph_stp { get; set; }
        public decimal PARM_G_MF_HP_TO_GB { get; set; }
        public decimal PARM_G_MF_OIL_EFFL_ETP { get; set; }
        public decimal parm_p822_run_hrs { get; set; }
        public decimal parm_p823_run_hrs { get; set; }
        public decimal OU1_RW_CONSP_DILUTION { get; set; }
        public decimal OU1_FW_CONSP_BW { get; set; }
        public decimal parm_hp_stock { get; set; }
        public decimal parm_hp_east_stock { get; set; }
        public decimal parm_hp_west_stock { get; set; }
        public decimal PARM_BAGGEA_RUN_HRS_P50_EASTA { get; set; }
        public decimal PARM_BAGGEB_RUN_HRS_P50_EASTB { get; set; }
        public decimal PARM_BAGGWA_RUN_HRS_P50_WESTA { get; set; }
        public decimal PARM_BAGGWB_RUN_HRS_P50_WESTB { get; set; }
        public decimal A_TOTAL_BLOWDOWN { get; set; }
        public decimal PARM_BAGGEA_RUN_HRS_P301B { get; set; }
        public decimal PARM_BAGGEB_RUN_HRS_P301B { get; set; }
        public decimal PARM_BAGGWA_RUN_HRS_P301C { get; set; }
        public decimal PARM_BAGGWB_RUN_HRS_P301D { get; set; }
        public decimal parm_effl_recycle_pump_run_hrs { get; set; }
    }
}
