namespace itsppisapi.Models
{
    public class POS006Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string OU1_TRANS_DATE { get; set; }
        public string OU1_UNIT_ID { get; set; }
        public string OU1_DATE_MOD { get; set; }
        public dynamic OU1_USER_ID { get; set; }
        public string OU1_USER_NAME { get; set; }

        public string OU1_NAP_TFR_TANK { get; set; }
        public dynamic OU1_NAP_GT1_INT { get; set; }
        public dynamic OU1_NAP_GT1_INT_DIFF { get; set; }
        public dynamic OU1_NAP_CONSP_GT { get; set; }
        public dynamic OU1_NAP_CONSP_GT1 { get; set; }
        public dynamic OU1_NAP_GT2_INT { get; set; }
        public dynamic OU1_NAP_GT2_INT_DIFF { get; set; }
        public dynamic OU1_NAP_CONSP_GT2 { get; set; }
        public dynamic OU1_NAP_AB1_INT { get; set; }
        public dynamic OU1_NAP_CONSP_AB { get; set; }
        public dynamic OU1_NAP_CONSP_AB1 { get; set; }
        public dynamic OU1_NAP_AB2_INT { get; set; }
        public dynamic OU1_NAP_CONSP_AB2 { get; set; }
        public dynamic OU1_NAP_CONSP_SPG { get; set; }
        public dynamic A_NAP_CONSP_AMM { get; set; }
        public dynamic OU1_DAYTANK_LEVEL { get; set; }
        public dynamic OU1_DAYTANK_MEAS_STOCK { get; set; }
        public dynamic OU1_NAP_IMPORTF_UNIT2 { get; set; }
        public dynamic OU1_DAYTANK_CALC_STOCK { get; set; }
        public dynamic OU1_DAYTANK_DIFF_PERCENT { get; set; }
        public dynamic OU1_NAP_STOCK { get; set; }
        public dynamic OU1_TANK_A_NAP_LEVEL { get; set; }
        public dynamic OU1_TANK_A_WTR_LEVEL { get; set; }
        public dynamic OU1_TANK_A_TEMP { get; set; }
        public dynamic OU1_TANK_A_DENSITY { get; set; }
        public dynamic OU1_TANK_A_STOCK { get; set; }
        public dynamic OU1_TANK_B_NAP_LEVEL { get; set; }
        public dynamic OU1_TANK_B_WTR_LEVEL { get; set; }
        public dynamic OU1_TANK_B_TEMP { get; set; }
        public dynamic OU1_TANK_B_DENSITY { get; set; }
        public dynamic OU1_TANK_B_STOCK { get; set; }
        public dynamic OU1_TANK_C_NAP_LEVEL { get; set; }
        public dynamic OU1_TANK_C_WTR_LEVEL { get; set; }
        public dynamic OU1_TANK_C_TEMP { get; set; }
        public dynamic OU1_TANK_C_DENSITY { get; set; }
        public dynamic OU1_TANK_C_STOCK { get; set; }
        public dynamic OU1_TANK_D_NAP_LEVEL { get; set; }
        public dynamic OU1_TANK_D_WTR_LEVEL { get; set; }
        public dynamic OU1_TANK_D_TEMP { get; set; }
        public dynamic OU1_TANK_D_DENSITY { get; set; }
        public dynamic OU1_TANK_D_STOCK { get; set; }
        public dynamic OU1_SNT_NAP_LEVEL { get; set; }
        public dynamic OU1_SNT_WTR_LEVEL { get; set; }
        public dynamic OU1_SNT_TEMP { get; set; }
        public dynamic OU1_SNT_DENSITY { get; set; }
        public dynamic OU1_SNT_STOCK { get; set; }
        public string OU1_NAP_TFR_TANK1_GPII { get; set; }
        public dynamic OU1_NAP_TFRT_DAYTANK_GPII { get; set; }
        public dynamic OU1_SNT_RECPT { get; set; }
        public dynamic OU1_SNT_TFR { get; set; }
        public dynamic OU1_DAY_TANK_LEVEL_ACTL { get; set; }
        public dynamic OU1_DAYTANK_MEAS_STOCK_ACTL { get; set; }
        public dynamic OU1_TANK_A_NAP_LEVEL_ACTL { get; set; }
        public dynamic OU1_TANK_A_STOCK_ACTL { get; set; }
        public dynamic OU1_TANK_B_NAP_LEVEL_ACTL { get; set; }
        public dynamic OU1_TANK_B_STOCK_ACTL { get; set; }
        public dynamic OU1_TANK_C_NAP_LEVEL_ACTL { get; set; }
        public dynamic OU1_TANK_C_STOCK_ACTL { get; set; }
        public dynamic OU1_TANK_D_NAP_LEVEL_ACTL { get; set; }
        public dynamic OU1_TANK_D_STOCK_ACTL { get; set; }
        public dynamic OU1_SNT_NAP_LEVEL_ACTL { get; set; }
        public dynamic OU1_SNT_STOCK_ACTL { get; set; }
        public dynamic DIFF_GP2_ACTL { get; set; }
        public string OU1_NAP_UNITTFR_TANK { get; set; }
        public string OU1_NAP_UNITTFR_TO_TANK { get; set; }
        public string OU1_NAP_TFR_FOR_UNIT { get; set; }
        public dynamic OU1_TFRTANK_NAP_LEVEL_BFR { get; set; }
        public dynamic OU1_TFRTANK_WTR_LEVEL_BFR { get; set; }
        public dynamic OU1_TFRTANK_STOCK_BFR { get; set; }
        public dynamic OU1_TFRTANK_NAP_LEVEL_AFT { get; set; }
        public dynamic OU1_TFRTANK_WTR_LEVEL_AFT { get; set; }
        public dynamic OU1_TFRTANK_STOCK_AFT { get; set; }

        public dynamic OU1_NAP_TOT_RECEIPT { get; set; }
        public dynamic OU1_NAP_CONSP_TOTAL { get; set; }
        public dynamic OU1_NAP_CONSP_UNIT2 { get; set; }

        public dynamic TXT_TOT_NAP_CONSP_GP1 { get; set; }
        public dynamic TXT_RCPT_IOC { get; set; }
        public dynamic TXT_NAP_TFRT_DT_GPII_DIFF { get; set; }
        public dynamic TXT_NAP_IMPORTF_UNIT2 { get; set; }
        public dynamic TXT_TOT_NAP_STK_GP1 { get; set; }
        public dynamic TXT_TANK_A_WTR_LEVEL { get; set; }
        public dynamic TXT_TANK_A_TEMP { get; set; }
        public dynamic TXT_TANK_A_DENSITY { get; set; }
        public dynamic TXT_TANK_B_WTR_LEVEL { get; set; }
        public dynamic TXT_TANK_B_TEMP { get; set; }
        public dynamic TXT_TANK_B_DENSITY { get; set; }
        public dynamic TXT_TANK_C_WTR_LEVEL { get; set; }
        public dynamic TXT_TANK_C_TEMP { get; set; }
        public dynamic TXT_TANK_C_DENSITY { get; set; }
        public dynamic TXT_TANK_D_WTR_LEVEL { get; set; }
        public dynamic TXT_TANK_D_TEMP { get; set; }
        public dynamic TXT_TANK_D_DENSITY { get; set; }
        public dynamic TXT_SNT_WTR_LEVEL { get; set; }
        public dynamic TXT_SNT_TEMP { get; set; }
        public dynamic TXT_SNT_DENSITY { get; set; }
        public dynamic TXT_TOT_NAP_ACTL_STK_CFCL { get; set; }
        public dynamic TXT_TOT_NAP_STK_GP2 { get; set; }
        public dynamic TXT_NAP_QTY_TFR { get; set; }

        // --------------------------PRV-------------------------------
        public string PRV_OU1_TRANS_DATE { get; set; }
        public dynamic PRV_OU1_NAP_TFR_TANK { get; set; }
        public dynamic PRV_OU1_NAP_GT1_INT { get; set; }
        public dynamic PRV_OU1_NAP_GT1_INT_DIFF { get; set; }
        public dynamic PRV_OU1_NAP_CONSP_GT1 { get; set; }
        public dynamic PRV_OU1_NAP_GT2_INT { get; set; }
        public dynamic PRV_OU1_NAP_GT2_INT_DIFF { get; set; }
        public dynamic PRV_OU1_NAP_CONSP_GT2 { get; set; }
        public dynamic PRV_OU1_NAP_AB1_INT { get; set; }
        public dynamic PRV_OU1_NAP_CONSP_AB1 { get; set; }
        public dynamic PRV_OU1_NAP_AB2_INT { get; set; }
        public dynamic PRV_OU1_NAP_CONSP_AB2 { get; set; }
        public dynamic PRV_OU1_NAP_CONSP_SPG { get; set; }
        public dynamic PRV_A_NAP_CONSP_AMM { get; set; }
        public dynamic PRV_OU1_DAYTANK_LEVEL { get; set; }
        public dynamic PRV_OU1_DAYTANK_MEAS_STOCK { get; set; }
        public dynamic PRV_OU1_NAP_IMPORTF_UNIT2 { get; set; }
        public dynamic PRV_OU1_DAYTANK_CALC_STOCK { get; set; }
        public dynamic PRV_OU1_DAYTANK_DIFF_PERCENT { get; set; }
        public dynamic PRV_OU1_NAP_STOCK { get; set; }
        public dynamic PRV_OU1_TANK_A_NAP_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_A_WTR_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_A_TEMP { get; set; }
        public dynamic PRV_OU1_TANK_A_DENSITY { get; set; }
        public dynamic PRV_OU1_TANK_A_STOCK { get; set; }
        public dynamic PRV_OU1_TANK_B_NAP_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_B_WTR_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_B_TEMP { get; set; }
        public dynamic PRV_OU1_TANK_B_DENSITY { get; set; }
        public dynamic PRV_OU1_TANK_B_STOCK { get; set; }
        public dynamic PRV_OU1_TANK_C_NAP_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_C_WTR_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_C_TEMP { get; set; }
        public dynamic PRV_OU1_TANK_C_DENSITY { get; set; }
        public dynamic PRV_OU1_TANK_C_STOCK { get; set; }
        public dynamic PRV_OU1_TANK_D_NAP_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_D_WTR_LEVEL { get; set; }
        public dynamic PRV_OU1_TANK_D_TEMP { get; set; }
        public dynamic PRV_OU1_TANK_D_DENSITY { get; set; }
        public dynamic PRV_OU1_TANK_D_STOCK { get; set; }
        public dynamic PRV_OU1_SNT_NAP_LEVEL { get; set; }
        public dynamic PRV_OU1_SNT_WTR_LEVEL { get; set; }
        public dynamic PRV_OU1_SNT_TEMP { get; set; }
        public dynamic PRV_OU1_SNT_DENSITY { get; set; }
        public dynamic PRV_OU1_SNT_STOCK { get; set; }
        public string PRV_OU1_NAP_TFR_TANK1_GPII { get; set; }
        public dynamic PRV_OU1_NAP_TFRT_DAYTANK_GPII { get; set; }
        public dynamic PRV_OU1_SNT_RECPT { get; set; }
        public dynamic PRV_OU1_SNT_TFR { get; set; }
        public dynamic PRV_OU1_DAY_TANK_LEVEL_ACTL { get; set; }
        public dynamic PRV_OU1_DAYTANK_MEAS_STOCK_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_A_NAP_LEVEL_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_A_STOCK_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_B_NAP_LEVEL_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_B_STOCK_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_C_NAP_LEVEL_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_C_STOCK_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_D_NAP_LEVEL_ACTL { get; set; }
        public dynamic PRV_OU1_TANK_D_STOCK_ACTL { get; set; }
        public dynamic PRV_OU1_SNT_NAP_LEVEL_ACTL { get; set; }
        public dynamic PRV_OU1_SNT_STOCK_ACTL { get; set; }
        public string PRV_OU1_NAP_UNITTFR_TANK { get; set; }
        public string PRV_OU1_NAP_UNITTFR_TO_TANK { get; set; }
        public string PRV_OU1_NAP_TFR_FOR_UNIT { get; set; }
        public dynamic PRV_OU1_TFRTANK_NAP_LEVEL_BFR { get; set; }
        public dynamic PRV_OU1_TFRTANK_WTR_LEVEL_BFR { get; set; }
        public dynamic PRV_OU1_TFRTANK_STOCK_BFR { get; set; }
        public dynamic PRV_OU1_TFRTANK_NAP_LEVEL_AFT { get; set; }
        public dynamic PRV_OU1_TFRTANK_WTR_LEVEL_AFT { get; set; }
        public dynamic PRV_OU1_TFRTANK_STOCK_AFT { get; set; }

        // --------------------------DV-------------------------------
        public dynamic parm_nap_numeric_const { get; set; }
        public dynamic PARM_TANK_A_DENSITY15 { get; set; }
        public dynamic PARM_TANK_B_DENSITY15 { get; set; }
        public dynamic PARM_TANK_C_DENSITY15 { get; set; }
        public dynamic PARM_TANK_D_DENSITY15 { get; set; }
        public dynamic PARM_SNT_DENSITY15 { get; set; }
        public dynamic PARM_TANK_A_DENSITY30 { get; set; }
        public dynamic PARM_TANK_B_DENSITY30 { get; set; }
        public dynamic PARM_TANK_C_DENSITY30 { get; set; }
        public dynamic PARM_TANK_D_DENSITY30 { get; set; }
        public dynamic PARM_SNT_DENSITY30 { get; set; }
        public dynamic parm_mf_day_tank_stock { get; set; }
        public dynamic parm_tank_a_dead_stock { get; set; }
        public dynamic parm_tank_b_dead_stock { get; set; }
        public dynamic parm_tank_c_dead_stock { get; set; }
        public dynamic parm_tank_d_dead_stock { get; set; }
        public dynamic parm_tank_snt_dead_stock { get; set; }
        public dynamic parm_tank_a_calib_const { get; set; }
        public dynamic parm_tank_b_calib_const { get; set; }
        public dynamic parm_tank_c_calib_const { get; set; }
        public dynamic parm_tank_d_calib_const { get; set; }
        public dynamic parm_tank_snt_calib_const { get; set; }
        public dynamic parm_tank_a_vol_pm { get; set; }
        public dynamic parm_tank_b_vol_pm { get; set; }
        public dynamic parm_tank_c_vol_pm { get; set; }
        public dynamic parm_tank_d_vol_pm { get; set; }
        public dynamic parm_tank_snt_vol_pm { get; set; }
        public dynamic parm_nap_cv { get; set; }
        public dynamic parm_tank_a_roof_wt { get; set; }
        public dynamic parm_tank_b_roof_wt { get; set; }
        public dynamic parm_tank_c_roof_wt { get; set; }
        public dynamic parm_tank_d_roof_wt { get; set; }
        public dynamic parm_snt_stock { get; set; }
        public string lvch_unit_G_101A { get; set; }
        public string lvch_unit_G_6001A { get; set; }
        public string lvch_unit_G_6001B { get; set; }
        public string lvch_unit_G_6001C { get; set; }
        public dynamic parm_nap_stock { get; set; }
        public dynamic parm_tank_c_stock { get; set; }
    }
}
