namespace itsppisapi.Models
{
    public class PMS212Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string M_TRANS_DATE { get; set; }
        public string M_UNIT_ID { get; set; }
        public string M_DATE_MOD { get; set; }
        public dynamic M_USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public dynamic AM_PLANT_LOAD { get; set; }
        public dynamic AM_PROD { get; set; }
        public dynamic AM_SALE { get; set; }
        public dynamic AM_STOCK { get; set; }
        public dynamic AM_SUPP_UREA { get; set; }
        public dynamic NG_ALLOC { get; set; }
        public dynamic NG_BAL_CONSP_AMM { get; set; }
        public dynamic NG_CONSP_SPG { get; set; }
        public dynamic NG_RECPT_CFCL { get; set; }
        public dynamic NG_RECPT_GAIL { get; set; }
        public dynamic BG_BULK_STOCK { get; set; }
        public dynamic BG_DESP_RAIL { get; set; }
        public dynamic BG_DESP_ROAD { get; set; }
        public dynamic BG_DESP_TOTAL { get; set; }
        public dynamic BG_TOTAL_BAGG_QTY { get; set; }
        public dynamic NAP_CONSP_TOTAL { get; set; }
        public dynamic NAP_STOCK { get; set; }
        public dynamic UR_TOTAL_UREA_PROD { get; set; }
        public dynamic UR_UREA_PLANT_LOAD { get; set; }
        public dynamic AM2_PLANT_LOAD { get; set; }
        public dynamic AM2_PROD { get; set; }
        public dynamic AM2_SALE { get; set; }
        public dynamic AM2_STOCK { get; set; }
        public dynamic UR2_TOTAL_UREA_PROD { get; set; }
        public dynamic UR2_TOT_AMM_CONSP { get; set; }
        public dynamic UR2_UREA_PLANT_LOAD { get; set; }
        public dynamic NG2_GAIL_RECPT { get; set; }
        public dynamic NG2_ALLOC { get; set; }
        public dynamic NG2_CONSP_AMM { get; set; }
        public dynamic NG2_CONSP_SPG { get; set; }
        public dynamic NAP2_CONSP_TOTAL { get; set; }
        public dynamic NAP2_STOCK { get; set; }
        public dynamic BG2_BULK_STOCK { get; set; }
        public dynamic BG2_DESP_RAIL { get; set; }
        public dynamic BG2_DESP_ROAD { get; set; }
        public dynamic BG2_DESP_TOTAL { get; set; }
        public dynamic BG2_TOTAL_BAGG_QTY { get; set; }
        public dynamic DIS_TM_AM_PROD { get; set; }
        public dynamic DIS_TY_AM_PROD { get; set; }
        public dynamic DIS_TM_AM2_PROD { get; set; }
        public dynamic DIS_TY_AM2_PROD { get; set; }
        public dynamic DIS_DAY_TOT_AMM_PROD { get; set; }
        public dynamic DIS_TM_TOT_AMM_PROD { get; set; }
        public dynamic DIS_TY_TOT_AMM_PROD { get; set; }
        public dynamic DIS_TM_UR_PROD { get; set; }
        public dynamic DIS_TY_UR_PROD { get; set; }
        public dynamic DIS_TM_UR2_PROD { get; set; }
        public dynamic DIS_TY_UR2_PROD { get; set; }
        public dynamic DIS_DAY_TOT_UR_PROD { get; set; }
        public dynamic DIS_TM_TOT_UR_PROD { get; set; }
        public dynamic DIS_TY_TOT_UR_PROD { get; set; }
        public dynamic DIS_TM_NG_CONSP_SPG { get; set; }
        public dynamic DIS_TY_NG_CONSP_SPG { get; set; }
        public dynamic DIS_TM_NG2_CONSP_SPG { get; set; }
        public dynamic DIS_TY_NG2_CONSP_SPG { get; set; }
        public dynamic DIS_DAY_TOT_NG_CONSP_SPG { get; set; }
        public dynamic DIS_TM_TOT_NG_CONSP_SPG { get; set; }
        public dynamic DIS_TY_TOT_NG_CONSP_SPG { get; set; }
        public dynamic DIS_TM_NG_CONSP_AMM { get; set; }
        public dynamic DIS_TY_NG_CONSP_AMM { get; set; }
        public dynamic DIS_TM_NG2_CONSP_AMM { get; set; }
        public dynamic DIS_TY_NG2_CONSP_AMM { get; set; }
        public dynamic DIS_DAY_TOT_NG_CONSP_AMM { get; set; }
        public dynamic DIS_TM_TOT_NG_CONSP_AMM { get; set; }
        public dynamic DIS_TY_TOT_NG_CONSP_AMM { get; set; }
        public dynamic DIS_TM_NAP_CONSP_TOTAL { get; set; }
        public dynamic DIS_TY_NAP_CONSP_TOTAL { get; set; }
        public dynamic DIS_TM_NAP2_CONSP_TOTAL { get; set; }
        public dynamic DIS_TY_NAP2_CONSP_TOTAL { get; set; }
        public dynamic DIS_DAY_TOT_NAP_CONSP_TOTAL { get; set; }
        public dynamic DIS_TM_TOT_NAP_CONSP_TOTAL { get; set; }
        public dynamic DIS_TY_TOT_NAP_CONSP_TOTAL { get; set; }
        public dynamic DIS_TM_AM_SUPP_UREA { get; set; }
        public dynamic DIS_TY_AM_SUPP_UREA { get; set; }
        public dynamic DIS_TM_UR2_AMM_CONSP { get; set; }
        public dynamic DIS_TY_UR2_AMM_CONSP { get; set; }
        public dynamic DIS_DAY_TOT_UR_AMM_CONSP { get; set; }
        public dynamic DIS_TM_TOT_UR_AMM_CONSP { get; set; }
        public dynamic DIS_TY_TOT_UR_AMM_CONSP { get; set; }
        public dynamic DIS_TM_BG_DESP_RAIL { get; set; }
        public dynamic DIS_TY_BG_DESP_RAIL { get; set; }
        public dynamic DIS_TM_BG2_DESP_RAIL { get; set; }
        public dynamic DIS_TY_BG2_DESP_RAIL { get; set; }
        public dynamic DIS_DAY_TOT_BG_DESP_RAIL { get; set; }
        public dynamic DIS_TM_TOT_BG_DESP_RAIL { get; set; }
        public dynamic DIS_TY_TOT_BG_DESP_RAIL { get; set; }
        public dynamic DIS_TM_BG_DESP_ROAD { get; set; }
        public dynamic DIS_TY_BG_DESP_ROAD { get; set; }
        public dynamic DIS_TM_BG2_DESP_ROAD { get; set; }
        public dynamic DIS_TY_BG2_DESP_ROAD { get; set; }
        public dynamic DIS_DAY_TOT_BG_DESP_ROAD { get; set; }
        public dynamic DIS_TM_TOT_BG_DESP_ROAD { get; set; }
        public dynamic DIS_TY_TOT_BG_DESP_ROAD { get; set; }
        public dynamic DIS_TM_BG_DESP_TOTAL { get; set; }
        public dynamic DIS_TY_BG_DESP_TOTAL { get; set; }
        public dynamic DIS_TM_BG2_DESP_TOTAL { get; set; }
        public dynamic DIS_TY_BG2_DESP_TOTAL { get; set; }
        public dynamic DIS_DAY_TOT_BG_DESP_TOTAL { get; set; }
        public dynamic DIS_TM_TOT_BG_DESP_TOTAL { get; set; }
        public dynamic DIS_TY_TOT_BG_DESP_TOTAL { get; set; }
        public dynamic DIS_TM_BG_BAGG_QTY { get; set; }
        public dynamic DIS_TY_BG_BAGG_QTY { get; set; }
        public dynamic DIS_TM_BG2_BAGG_QTY { get; set; }
        public dynamic DIS_TY_BG2_BAGG_QTY { get; set; }
        public dynamic DIS_DAY_TOT_BG_BAGG_QTY { get; set; }
        public dynamic DIS_TM_TOT_BG_BAGG_QTY { get; set; }
        public dynamic DIS_TY_TOT_BG_BAGG_QTY { get; set; }
        public dynamic DIS_TM_AM_SALE { get; set; }
        public dynamic DIS_TY_AM_SALE { get; set; }
        public dynamic DIS_TM_AM2_SALE { get; set; }
        public dynamic DIS_TY_AM2_SALE { get; set; }
        public dynamic DIS_DAY_TOT_AM_SALE { get; set; }
        public dynamic DIS_TM_TOT_AM_SALE { get; set; }
        public dynamic DIS_TY_TOT_AM_SALE { get; set; }
        public dynamic DIS_TM_AM_PLANT_LOAD { get; set; }
        public dynamic DIS_TY_AM_PLANT_LOAD { get; set; }
        public dynamic DIS_TM_AM2_PLANT_LOAD { get; set; }
        public dynamic DIS_TY_AM2_PLANT_LOAD { get; set; }
        public dynamic DIS_DAY_AVE_AM_PLANT_LOAD { get; set; }
        public dynamic DIS_TM_AVE_AM_PLANT_LOAD { get; set; }
        public dynamic DIS_TY_AVE_AM_PLANT_LOAD { get; set; }
        public dynamic DIS_TM_UR_PLANT_LOAD { get; set; }
        public dynamic DIS_TY_UR_PLANT_LOAD { get; set; }
        public dynamic DIS_TM_UR2_PLANT_LOAD { get; set; }
        public dynamic DIS_TY_UR2_PLANT_LOAD { get; set; }
        public dynamic DIS_DAY_AVE_UR_PLANT_LOAD { get; set; }
        public dynamic DIS_TM_AVE_UR_PLANT_LOAD { get; set; }
        public dynamic DIS_TY_AVE_UR_PLANT_LOAD { get; set; }
        public dynamic DIS_TOT_AM_STOCK { get; set; }
        public dynamic DIS_TOT_BG_BULK_STOCK { get; set; }
        public dynamic DIS_TOT_NAP_STOCK { get; set; }
        public string M_REMARK { get; set; }
        public string M_REMARK_UNIT2 { get; set; }
        public string M_REMARK_SSP { get; set; }
        public string M_C_REMARKS { get; set; }
        public string M_C_REMARKS_UNIT2 { get; set; }
    }
}
