namespace itsppisapi.Dtos
{
    public class PAS201SaveDto
    {
        public string A2_TRANS_DATE { get; set; }
        public string A2_DMY_FLG { get; set; }
        public decimal A2_USER_ID { get; set; }
        public decimal A2_NG_TOT_AMM2_INT { get; set; }
        public decimal A2_NG_TOT_AMM2_INT_DIFF { get; set; }
        public decimal A2_CF_NG_TOT_CONSP_AMM2 { get; set; }
        public decimal A2_NG_TOT_CONSP_AMM2 { get; set; }
        public decimal A2_BAL_NG_TOT_CONSP_AMM2 { get; set; }
        public decimal A2_PRS_NG_FUEL_AB_INT { get; set; }
        public decimal A2_PRS_NG_FUEL_AB_INT_DIFF { get; set; }
        public decimal A2_TEMP_NG_FUEL_AB_INT { get; set; }
        public decimal A2_TEMP_NG_FUEL_AB_INT_DIFF { get; set; }
        public decimal A2_NG_FUEL_AB_INT { get; set; }
        public decimal A2_NG_FUEL_AB_INT_DIFF { get; set; }
        public decimal A2_CF_NG_CONSP_AB { get; set; }
        public decimal A2_NG_CONSP_AB { get; set; }
        public decimal A2_NG_FEED_AMM2_INT { get; set; }
        public decimal A2_NG_FEED_AMM2_INT_DIFF { get; set; }
        public decimal A2_CF_NG_FEED_AMM2 { get; set; }
        public decimal A2_NG_CONSP_FEED_AMM2 { get; set; }
        public decimal A2_PRS_NG_FUEL_ABURNER_INT { get; set; }
        public decimal A2_PRS_NG_FUEL_ABURNER_INT_DIFF { get; set; }
        public decimal A2_TEMP_NG_FUEL_ABURNER_INT { get; set; }
        public decimal A2_TEMP_NG_FUEL_ABURNER_INT_DIF { get; set; }
        public decimal A2_NG_FUEL_ABURNER_INT { get; set; }
        public decimal A2_NG_FUEL_ABURNER_INT_DIFF { get; set; }
        public decimal A2_CF_NG_FUEL_ABURNER { get; set; }
        public decimal A2_NG_FUEL_ABURNER { get; set; }
        public decimal A2_PRS_NG_FUEL_TBURNER_INT { get; set; }
        public decimal A2_PRS_NG_FUEL_TBURNER_INT_DIFF { get; set; }
        public decimal A2_TEMP_NG_FUEL_TBURNER_INT { get; set; }
        public decimal A2_TEMP_NG_FUEL_TBURNER_INT_DIF { get; set; }
        public decimal A2_NG_FUEL_TBURNER_INT { get; set; }
        public decimal A2_NG_FUEL_TBURNER_INT_DIFF { get; set; }
        public decimal A2_CF_NG_FUEL_TBURNER { get; set; }
        public decimal A2_NG_FUEL_TBURNER { get; set; }
        public decimal A2_PRS_NG_FUEL_BA101_INT { get; set; }
        public decimal A2_PRS_NG_FUEL_BA101_INT_DIFF { get; set; }
        public decimal A2_TEMP_NG_FUEL_BA101_INT { get; set; }
        public decimal A2_TEMP_NG_FUEL_BA101_INT_DIFF { get; set; }
        public decimal A2_NG_FUEL_BA101_INT { get; set; }
        public decimal A2_NG_FUEL_BA101_INT_DIFF { get; set; }
        public decimal A2_CF_NG_FUEL_BA101 { get; set; }
        public decimal A2_NG_FUEL_BA101 { get; set; }
        public decimal A2_PRS_NG_FUEL_BA102_INT { get; set; }
        public decimal A2_PRS_NG_FUEL_BA102_INT_DIFF { get; set; }
        public decimal A2_TEMP_NG_FUEL_BA102_INT { get; set; }
        public decimal A2_TEMP_NG_FUEL_BA102_INT_DIFF { get; set; }
        public decimal A2_NG_FUEL_BA102_INT { get; set; }
        public decimal A2_NG_FUEL_BA102_INT_DIFF { get; set; }
        public decimal A2_CF_NG_FUEL_BA102 { get; set; }
        public decimal A2_NG_FUEL_BA102 { get; set; }
        public decimal A2_BAL_NG_FUEL_SH_BURNER { get; set; }
        public decimal A2_NG_GAIL_RECPT { get; set; }
        public decimal A2_NG_ALLOCATION { get; set; }
        public decimal A2_NG_NET_CV { get; set; }
        public string A2_NG_LIMITATION_FLG { get; set; }
        public decimal A2_MOL_WT_NG { get; set; }
        public decimal A2_NG_CARBON_NO { get; set; }
        public string A2_REMARKS { get; set; }
        public decimal A2_NG_FUEL_SH_BURN_INT { get; set; }
        public decimal A2_NG_FUEL_SH_BURN_INT_DIFF { get; set; }
        public decimal A2_PRS_NG_SH_BURN_INT { get; set; }
        public decimal A2_PRS_NG_SH_BURN_INT_DIFF { get; set; }
        public decimal A2_TEMP_NG_SH_BURN_INT { get; set; }
        public decimal A2_TEMP_NG_SH_BURN_INT_DIFF { get; set; }
        public decimal A2_TOT_NG_FUEL_INT { get; set; }
        public decimal A2_TOT_NG_FUEL_INT_DIFF { get; set; }
        public decimal A2_TOT_CONSP_NG_FUEL { get; set; }
        public decimal A2_CF_NG_FUEL_SH_BURN { get; set; }
        public decimal A2_NG_SYNTH_GAS_INT { get; set; }
        public decimal A2_NG_SYNTH_GAS_INT_DIFF { get; set; }
        public decimal A2_PRS_TOT_NG_FUEL_INT { get; set; }
        public decimal A2_PRS_TOT_NG_FUEL_INT_DIFF { get; set; }
        public decimal A2_TEMP_TOT_NG_FUEL_INT { get; set; }
        public decimal A2_TEMP_TOT_NG_FUEL_INT_DIFF { get; set; }
        public decimal A2_CF_TOT_NG_FUEL { get; set; }
        public decimal A2_NG_IMPORTF_UNIT1 { get; set; }
        public decimal A2_NG_EXPORTT_UNIT1 { get; set; }
        public decimal A2_NG_FUEL_FLARE_INT { get; set; }
        public decimal A2_NG_FUEL_FLARE_INT_DIFF { get; set; }
        public decimal A2_PRS_FUEL_FLARE_INT { get; set; }
        public decimal A2_PRS_FUEL_FLARE_INT_DIFF { get; set; }
        public decimal A2_TEMP_FUEL_FLARE_INT { get; set; }
        public decimal A2_TEMP_FUEL_FLARE_INT_DIFF { get; set; }
        public decimal A2_CF_FUEL_FLARE { get; set; }
        public decimal A2_NG_FUEL_FLARE { get; set; }
        public decimal A2_SYNTH_GAS_EXPTT_GP2_INT_DIFF { get; set; }
        public decimal A2_SYNTH_GAS_EXPTT_GP2_INT { get; set; }
        public decimal A2_SYNTH_GAS_EXPTT_GP1_INT_DIFF { get; set; }
        public decimal A2_SYNTH_GAS_EXPTT_GP1_INT { get; set; }
        public decimal A2_IOC_RLNG_ALLOCATION { get; set; }
        public decimal A2_IOC_RLNG_RECEIPT { get; set; }
        public decimal A2_IOC_RLNG_GCV { get; set; }
        public decimal A2_IOC_RLNG_LCV { get; set; }
        public decimal A2_PRS_NG_TRANSFER_INT { get; set; }
        public decimal A2_PRS_NG_TRANSFER_INT_DIFF { get; set; }
        public decimal A2_TEMP_NG_TRANSFER_INT { get; set; }
        public decimal A2_TEMP_NG_TRANSFER_INT_DIFF { get; set; }
        public decimal A2_NG_EXPORTT_GP1_INT { get; set; }
        public decimal A2_NG_EXPORTT_GP1_INT_DIFF { get; set; }
        public decimal A2_NG_IMPORTF_GP1_INT { get; set; }
        public decimal A2_NG_IMPORTF_GP1_INT_DIFF { get; set; }
        public decimal A2_NG_FEED_BYBAL_TO_AMM2 { get; set; }
        public decimal A2_CF_NG_TRANSFER { get; set; }
        public decimal A2_RLNG_ALLOC_ACTL_LCV { get; set; }
        public decimal A2_SPOTGAS_IOCL_ALLOC { get; set; }
        public decimal A2_SPOTGAS_IOCL_RECEIPT { get; set; }
        public decimal A2_SPOTGAS_OTH_ALLOC { get; set; }
        public decimal A2_SPOTGAS_OTH_RECEIPT { get; set; }
        public decimal A2_RLNG_IOC_RECEIPT { get; set; }
        public decimal A2_SPOTGAS_GAIL_ALLOC { get; set; }
        public decimal A2_SPOTGAS_GAIL_RECEIPT { get; set; }
        public decimal A2_SPOTGAS_GSPC_ALLOC { get; set; }
        public decimal A2_SPOTGAS_GSPC_RECEIPT { get; set; }
        public decimal A2_RIL_GAS_ALLOC { get; set; }
        public decimal A2_RIL_GAS_RECEIPT_ACTL_LCV { get; set; }
        public decimal A2_RIL_GAS_ENERGY { get; set; }
        public decimal A2_RIL_GAS_RECEIPT_ACTL_GCV { get; set; }
        public decimal A2_RIL_GAS_ENERGY_ACTL_GCV { get; set; }
        public decimal A2_RIL_SCH_ENG_GCV { get; set; }
        public decimal A2_RIL_SCH_GAS { get; set; }
        public decimal A2_RLNG_SCH_ENG_GCV { get; set; }
        public decimal A2_RLNG_GAS_ENERGY_ACTL_GCV { get; set; }
        public decimal A2_SG_IOCL_SCH_ENG_GCV { get; set; }
        public decimal A2_SG_IOCL_ENERGY_ACTL_GCV { get; set; }
        public decimal A2_SG_GAIL_SCH_ENG_GCV { get; set; }
        public decimal A2_SG_GAIL_ENERGY_ACTL_GCV { get; set; }
        public decimal A2_SG_GSPC_SCH_ENG_GCV { get; set; }
        public decimal A2_SG_GSPC_ENERGY_ACTL_GCV { get; set; }
        public decimal A2_SG_OTH_SCH_ENG_GCV { get; set; }
        public decimal A2_SG_OTH_ENERGY_ACTL_GCV { get; set; }
        public decimal A2_NG_EXPORTT_SSP { get; set; }
        public decimal A2_NG_EXPORTT_UNIT1_SSP { get; set; }
        public decimal A2_RLNG_EXPORTT_SSP { get; set; }
        public decimal A2_SPOT_EXPORTT_SSP { get; set; }
        public string A2_GAIL_METER_ONLINE { get; set; }
        public decimal A2_RIL_GAS_EXPORTT_UNIT1 { get; set; }
        public decimal A2_IOCL_RLNG_EXPORTT_UNIT1 { get; set; }
        public decimal A2_SPOT_RLNG_EXPORTT_UNIT1 { get; set; }
        public decimal A2_GAIL_LT_RLNG_RE_ALLOC { get; set; }
        public decimal A2_GAIL_LT_RLNG_RE_RECEIPT { get; set; }
        public decimal A2_GAIL_LT_RLNG_RE_SCH_ENG_GCV { get; set; }
        public decimal A2_GAIL_LT_RLNG_RE_ENG_ACT_GCV { get; set; }
        public decimal A2_GAIL_RLNG5_SCH_ENG_GCV { get; set; }
        public decimal A2_GAIL_RLNG5_ENG_ACTL_GCV { get; set; }
        public decimal A2_GAIL_RLNG5_SCH_GAS { get; set; }
        public decimal A2_GAIL_RLNG5_RECEIPT_ACTL_GCV { get; set; }
        public decimal A2_GAIL_RLNG19_SCH_ENG_GCV { get; set; }
        public decimal A2_GAIL_RLNG19_ENG_ACTL_GCV { get; set; }
        public decimal A2_GAIL_RLNG19_SCH_GAS { get; set; }
        public decimal A2_GAIL_RLNG19_RECEIPT_ACTL_GCV { get; set; }
    }
}
