namespace itsppisapi.Dtos
{
    public class PAS208SaveDto
    {
        public string A2_TRANS_DATE { get; set; }
        public string A2_DMY_FLG { get; set; }
        public decimal A2_USER_ID { get; set; }
        public decimal A2_RG_SH_PROD_INT { get; set; }
        public decimal A2_RG_SH_PROD { get; set; }
        public decimal A2_AB_SH_PROD_INT { get; set; }
        public decimal A2_AB_SH_PROD { get; set; }
        public decimal A2_TOTAL_SH_PROD { get; set; }
        public decimal A2_SH_CONSP_SYNGAS_INT { get; set; }
        public decimal A2_SH_CONSP_SYNGAS { get; set; }
        public decimal A2_SH_CONSP_AIRCOMP_INT { get; set; }
        public decimal A2_SH_CONSP_AIRCOMP { get; set; }
        // public decimal A2_SH_CONSP_UREA2_INT { get; set; }
        public decimal A2_SH_CONSP_UREA2 { get; set; }
        public decimal A2_SH_LETDOWN_SM { get; set; }
        public decimal A2_SH_TOTAL_CONSP { get; set; }
        public decimal A2_SH_EXPORTT_GPI { get; set; }
        public decimal A2_SYNGAS_SM_PROD_INT { get; set; }
        public decimal A2_SYNGAS_SM_PROD_INT_DIFF { get; set; }
        public decimal A2_SYNGAS_EXTRACT_SM_PROD { get; set; }
        public decimal A2_AIRCOMP_SM_PROD_INT { get; set; }
        public decimal A2_AIRCOMP_SM_PROD_INT_DIFF { get; set; }
        public decimal A2_AIRCOMP_EXTRCT_SM_PROD { get; set; }
        public decimal A2_TOTAL_SM_PROD { get; set; }
        public decimal A2_SM_CONSP_PSTEAM_INT { get; set; }
        public decimal A2_SM_CONSP_PSTEAM { get; set; }
        public decimal A2_SM_CONSP_REFCOMP_INT { get; set; }
        public decimal A2_SM_CONSP_REFCOMP { get; set; }
        public decimal A2_SM_CONSP_NGCOMP_INT { get; set; }
        public decimal A2_SM_CONSP_NGCOMP { get; set; }
        public decimal A2_SM_CONSP_BFW_PUMPA_INT { get; set; }
        public decimal A2_SM_CONSP_BFW_PUMPA { get; set; }
        public decimal A2_SM_CONSP_BFW_PUMPB_INT { get; set; }
        public decimal A2_SM_CONSP_BFW_PUMPB { get; set; }
        public decimal A2_SM_CONSP_SLPUMPA_INT { get; set; }
        public decimal A2_SM_CONSP_SLPUMPA { get; set; }
        public decimal A2_SM_CONSP_SLPUMPB_INT { get; set; }
        public decimal A2_SM_CONSP_SLPUMPB { get; set; }
        public decimal A2_SM_CONSP_LPUMP_INT { get; set; }
        public decimal A2_SM_CONSP_LPUMP { get; set; }
        public decimal A2_SM_CONSP_IDFAN_INT { get; set; }
        public decimal A2_SM_CONSP_IDFAN { get; set; }
        public decimal A2_SM_CONSP_FDFAN_INT { get; set; }
        public decimal A2_SM_CONSP_FDFAN { get; set; }
        public decimal A2_SM_CONSP_PACOIL_INT { get; set; }
        public decimal A2_SM_CONSP_PACOIL { get; set; }
        public decimal A2_SM_CONSP_H2SSTRIP_INT { get; set; }
        public decimal A2_SM_CONSP_H2SSTRIP { get; set; }
        public decimal A2_SM_CONSP_DISTCOL_INT { get; set; }
        public decimal A2_SM_CONSP_DISTCOL { get; set; }
        public decimal A2_SM_CONSP_ATOMIZING_INT { get; set; }
        public decimal A2_SM_CONSP_ATOMIZING { get; set; }
        public decimal A2_SM_LETDOWN_SL { get; set; }
        public decimal A2_SM_TOTAL_CONSP_AMM2 { get; set; }
        public decimal A2_SM_CONSP_AB_INT { get; set; }
        public decimal A2_SM_CONSP_AB { get; set; }
        public decimal A2_SM_CONSP_ABFDFAN_INT { get; set; }
        public decimal A2_SM_CONSP_ABFDFAN { get; set; }
        public decimal A2_ABSM_LETDOWN_ATOMIZING { get; set; }
        public decimal A2_SM_CONSP_ACWPUMPA_INT { get; set; }
        public decimal A2_SM_CONSP_ACWPUMPA { get; set; }
        public decimal A2_SM_CONSP_ACWPUMPB_INT { get; set; }
        public decimal A2_SM_CONSP_ACWPUMPB { get; set; }
        public decimal A2_SM_CONSP_ACWPUMPC_INT { get; set; }
        public decimal A2_SM_CONSP_ACWPUMPC { get; set; }
        public decimal A2_SM_CONSP_UCWPUMPA_INT { get; set; }
        public decimal A2_SM_CONSP_UCWPUMPA { get; set; }
        public decimal A2_SM_CONSP_UCWPUMPB_INT { get; set; }
        public decimal A2_SM_CONSP_UCWPUMPB { get; set; }
        public decimal A2_SM_CONSP_UCWPUMPC_INT { get; set; }
        public decimal A2_SM_CONSP_UCWPUMPC { get; set; }
        public decimal A2_SM_CONSP_CTTCPUMP_INT { get; set; }
        public decimal A2_SM_CONSP_CTTCPUMP { get; set; }
        public decimal A2_SM_TOTAL_CONSP_UTIL { get; set; }
        public decimal A2_SM_TOTAL_CONSP_GPII { get; set; }
        public decimal A2_SL_INTERNAL_PROD { get; set; }
        public decimal A2_TOTAL_SL_PROD { get; set; }
        public decimal A2_SL_CONSP_AMMREF_INT { get; set; }
        public decimal A2_SL_CONSP_AMMREF { get; set; }
        public decimal A2_SL_CONSP_NAPPREHEAT_INT { get; set; }
        public decimal A2_SL_CONSP_NAPPREHEAT { get; set; }
        public decimal A2_SL_CONSP_RNAPPREHEAT_INT { get; set; }
        public decimal A2_SL_CONSP_RNAPPREHEAT { get; set; }
        public decimal A2_SL_CONSP_EJECTOR_INT { get; set; }
        public decimal A2_SL_CONSP_EJECTOR { get; set; }
        public decimal A2_SL_CONSP_MISC { get; set; }
        public decimal A2_SL_CONSP_DEAERATOR { get; set; }
        public decimal A2_SL_TOTAL_CONSP { get; set; }
        public string A2_REMARKS { get; set; }
        public decimal A2_DESUP_WATER_INT { get; set; }
        public decimal A2_DESUP_WATER_INT_DIFF { get; set; }
        public decimal A2_IMPORT_SH_CONSP_AMM { get; set; }
        public decimal A2_IMPORT_SH_CONSP_UREA { get; set; }
        public decimal A2_LB_SH_PROD_INT { get; set; }
        public decimal A2_LB_SH_PROD { get; set; }
        public decimal A2_SH_CONSP_REVAMP_UNIT2 { get; set; }
        public decimal A2_SM_CONSP_REVAMP_UNIT2 { get; set; }
    }
}
