namespace itsppisapi.Models
{
    public class PTS229Model
    {
        public decimal MINIDENTITY { get; set; }
        public decimal MINYEAR { get; set; }
        public decimal MAXIDENTITY { get; set; }
        public decimal MAXYEAR { get; set; }
        public decimal T_YEAR { get; set; }
        public decimal T_IDENTITY { get; set; }
        public decimal T_VERSION { get; set; }
        public string T_UNIT_ID { get; set; }
        public decimal T_USER_ID { get; set; }
        public string T_USER_NAME { get; set; }
        public string T_DATE_MOD { get; set; }

        public decimal T_DM_MKUP_GP1 { get; set; }
        public decimal T_DM_MKUP_GP2 { get; set; }
        public decimal T_DM_MKUP_NET { get; set; }
        public decimal T_APC_FR_AM2 { get; set; }
        public decimal T_ATC_FR_AM2 { get; set; }
        public decimal T_SC_FR_AM2 { get; set; }
        public decimal T_UPC_FR_UR2 { get; set; }
        public decimal T_TC_UR2_TA { get; set; }
        public decimal T_TC_UR2_TB { get; set; }
        public decimal T_TC_UR2 { get; set; }
        public decimal T_SC_FR_UR2 { get; set; }
        public decimal T_ACTTC_EXP_TO_AM2 { get; set; }
        public decimal T_TC_FR_CW_TURBINE { get; set; }
        public decimal T_REC_COND_SUB_TOT { get; set; }
        public decimal T_PW_RC_OTHERS_GP1 { get; set; }
        public decimal T_REC_COND_TOT { get; set; }
        public decimal T_BFW_TO_STOR_TNK { get; set; }
        public decimal T_BFW_FR_STOR_TNK { get; set; }
        public decimal T_PW_D_TNK_TRF { get; set; }
        public decimal T_PW_CONSP_AM2 { get; set; }
        public decimal T_PW_CONSP_AB3 { get; set; }
        public decimal T_PW_PB_AM2 { get; set; }
        public decimal T_PW_PB_UR2 { get; set; }
        public decimal T_PW_CONSP_SUB_TOT { get; set; }
        public decimal T_PW_CONSP_IN_GP1 { get; set; }
        public decimal T_PW_CONSP_TOT { get; set; }
        public decimal T_FW_PRODN_FR_WPT { get; set; }
        public decimal T_FW_PURCHASED { get; set; }
        public decimal T_FW_TRF_TO_STRG_TNK { get; set; }
        public decimal T_FW_TAKEN_FR_TNK { get; set; }
        public decimal T_FW_AS_FEED_TO_DMP { get; set; }
        public decimal T_FW_AS_FEED_TO_DMP_GP1 { get; set; }
        public decimal T_FW_AS_FEED_TO_DMP_GP2 { get; set; }
        public decimal T_FW_MKUP_ACT { get; set; }
        public decimal T_FW_MKUP_UCT { get; set; }
        public decimal T_FW_MKUP_ACT_UCT { get; set; }
        public decimal T_FW_PORT { get; set; }
        public decimal T_FW_IN_FBW { get; set; }
        public decimal T_FW_IN_FBW_GP1 { get; set; }
        public decimal T_FW_IN_FBW_GP2 { get; set; }
        public decimal T_FW_IN_ETP { get; set; }
        public decimal T_FW_CONSP_OTHERS_GP1 { get; set; }
        public decimal T_FW_SB_TOT_PLT_CONSP { get; set; }
        public decimal T_FW_IN_FAC_TSHIP { get; set; }
        public decimal T_FW_IN_FIRE { get; set; }
        public decimal T_FW_IN_SERVICE { get; set; }
        public decimal T_FW_SB_TOT_NON_PLT_CONSP { get; set; }
        public decimal T_FW_NON_PLT_OTHERS_GP1 { get; set; }
        public decimal T_FW_NON_PLT_CONSP_TOT { get; set; }
        public decimal T_FW_TOT_CONSP { get; set; }
        public decimal T_FI1_PW_MKUP_SC_AP { get; set; }
        public decimal T_PW_CONS_AM2 { get; set; }
        public decimal T_RW_KS_PURCHASE { get; set; }
        public decimal T_RW_KS_PURCHASE_GP1 { get; set; }
        public decimal T_RW_KS_PURCHASE_GP2 { get; set; }
        public decimal T_RW_OTHERS_PURCHASED { get; set; }
        public decimal T_RW_SENT_TO_RESVOIR { get; set; }
        public decimal T_RW_DRW_FR_RESVOIR { get; set; }
        public decimal T_RW_TO_PW_PROD { get; set; }
        public decimal T_RW_DILUTION { get; set; }
        public decimal T_RW_DILUTION_GP1 { get; set; }
        public decimal T_RW_DILUTION_GP2 { get; set; }
        public decimal T_RW_CONSP_GP1 { get; set; }
        public decimal T_RW_CONSP_GP2 { get; set; }
        public decimal T_RW_LOSSES { get; set; }
        public decimal T_RW_DISTRIBTION_NET { get; set; }
        public decimal T_RW_1901 { get; set; }
        public decimal T_1901_COND_IMP_FR_DMP { get; set; }
        public decimal T_1901_TC_SC_TO_DMP { get; set; }
        public decimal T_1901_TOT_COND_EXP { get; set; }
        public decimal T_1901_PW_EXP_NET { get; set; }
        public decimal T_PW_CONSP_AM2_SC_AP { get; set; }
        public decimal T_FW_MKUP_ACT_SC_AP { get; set; }
        public decimal T_FI1_EXP_BFW_SC_AP { get; set; }
        public decimal T_RW_1901_SC_AP { get; set; }
        public decimal T_1901_COND_IMP_FR_DMP_SC_AP { get; set; }
        public decimal T_APC_FR_AM2_SC_AP { get; set; }
        public decimal T_1901_TC_SC_TO_DMP_SC_AP { get; set; }
        public decimal T_ACTTC_EXP_TO_AM2_SC_AP { get; set; }
        public decimal T_1901_TOT_COND_EXP_SC_AP { get; set; }
        public decimal T_1901_PW_EXP_NET_SC_AP { get; set; }
        public decimal T_PW_CONSP_AM2_SC_AH { get; set; }
        public decimal T_FW_MKUP_ACT_SC_AH { get; set; }
        public decimal T_RW_1901_SC_AH { get; set; }
        public decimal T_1901_COND_IMP_FR_DMP_SC_AH { get; set; }
        public decimal T_APC_FR_AM2_SC_AH { get; set; }
        public decimal T_1901_TC_SC_TO_DMP_SC_AH { get; set; }
        public decimal T_ACTTC_EXP_TO_AM2_SC_AH { get; set; }
        public decimal T_1901_TOT_COND_EXP_SC_AH { get; set; }
        public decimal T_1901_PW_EXP_NET_SC_AH { get; set; }
        public decimal T_FW_1905_TOT { get; set; }
        public decimal T_RW_1905_PL_CONSP { get; set; }
        public decimal T_RW_1905_PORT { get; set; }
        public decimal T_RW_1905_NP_CONSP { get; set; }
        public decimal T_RW_1905_TOT { get; set; }
        public decimal T_CD_TCSC_EXP { get; set; }
        public decimal T_CD_TC_EXP { get; set; }
        public decimal T_CD_1905_TOT { get; set; }
        public decimal T_CD_DM_IMP { get; set; }
        public decimal T_CD_NET_EXP { get; set; }
        public decimal T_FW_MKUP_UCT_SC_UP { get; set; }
        public decimal T_FW_PORT_SC_UP { get; set; }
        public decimal T_FW_SB_TOT_NON_PT_CONSP_SC_UP { get; set; }
        public decimal T_PW_1905_TOT_SC_UP { get; set; }
        public decimal T_RW_1905_PL_CONSP_SC_UP { get; set; }
        public decimal T_RW_1905_PORT_SC_UP { get; set; }
        public decimal T_RW_1905_NP_CONSP_SC_UP { get; set; }
        public decimal T_RW_1905_TOT_SC_UP { get; set; }
        public decimal T_UPC_FR_UR2_SC_UP { get; set; }
        public decimal T_CD_TCSC_EXP_SC_UP { get; set; }
        public decimal T_CD_TC_EXP_SC_UP { get; set; }
        public decimal T_CD_1905_TOT_SC_UP { get; set; }
        public decimal T_CD_DM_IMP_SC_UP { get; set; }
        public decimal T_CD_NET_EXP_SC_UP { get; set; }
        public decimal T_PW_PB_UR2_SC_UP { get; set; }
        public decimal T_FW_MKUP_UCT_SC_UH { get; set; }
        public decimal T_FW_PORT_SC_UH { get; set; }
        public decimal T_FW_SB_TOT_NON_PT_CONSP_SC_UH { get; set; }
        public decimal T_FW_1905_TOT_SC_UH { get; set; }
        public decimal T_RW_1905_PL_CONSP_SC_UH { get; set; }
        public decimal T_RW_1905_PORT_SC_UH { get; set; }
        public decimal T_RW_1905_NP_CONSP_SC_UH { get; set; }
        public decimal T_RW_1905_TOT_SC_UH { get; set; }
        public decimal T_UPC_FR_UR2_SC_UH { get; set; }
        public decimal T_CD_TCSC_EXP_SC_UH { get; set; }
        public decimal T_CD_TC_EXP_SC_UH { get; set; }
        public decimal T_CD_1905_TOT_SC_UH { get; set; }
        public decimal T_CD_DM_IMP_SC_UH { get; set; }
        public decimal T_CD_NET_EXP_SC_UH { get; set; }
        public decimal T_FW_IMP_DMW { get; set; }
        public decimal T_RW_PL_CONSP { get; set; }
        public decimal T_RW_NP_CONSP { get; set; }
        public decimal T_RW_1909_PL_NP { get; set; }
        public decimal T_PW_PB_UR2_SC_UH { get; set; }
        public decimal T_FW_IMP_DMW_SC_SP { get; set; }
        public decimal T_PW_CONSP_AB3_SC_SP { get; set; }
        public decimal T_RW_PL_CONSP_SC_SP { get; set; }
        public decimal T_RW_NP_CONSP_SC_SP { get; set; }
        public decimal T_RW_1909_PL_NP_SC_SP { get; set; }
        public decimal T_FW_IMP_DMW_SC_SH { get; set; }
        public decimal T_PW_CONSP_AB3_SC_SH { get; set; }
        public decimal T_RW_PL_CONSP_SC_SH { get; set; }
        public decimal T_RW_NP_CONSP_SC_SH { get; set; }
        public decimal T_RW_1909_PL_NP_SC_SH { get; set; }
        public decimal T_RW_PUR_SCA_UP { get; set; }
        public decimal T_PW_IN_AM2_RGB { get; set; }
        public decimal T_PW_IN_AM2_DES_F1925 { get; set; }
        public decimal T_PW_IN_AM2_DES_F1910 { get; set; }
        public decimal T_PW_IN_AM2_REC_TRF { get; set; }
        public decimal T_PW_IN_AM2 { get; set; }
        public decimal T_PW_IN_GP2 { get; set; }
        public decimal T_FI2_COND_EXP { get; set; }
        public decimal T_FI2_COND_EXP_SC_AP { get; set; }
        public decimal T_FI2_CW_MKUP_SC_AP { get; set; }
        public decimal T_FI2_PW_MKUP_SC_AP { get; set; }
        public decimal T_RW_STK_OP { get; set; }
        public decimal T_RW_STK_CL { get; set; }
        public decimal T_FW_STK_OP { get; set; }
        public decimal T_FW_STK_CL { get; set; }
        public decimal T_DMW_STK_OP { get; set; }
        public decimal T_DMW_STK_CL { get; set; }
        public decimal T_PW_STK_OP { get; set; }
        public decimal T_PW_STK_CL { get; set; }
        public decimal T_CONDENSATE_DRAINED { get; set; }
        public decimal T_NET_CONDENSATE { get; set; }
        public string T_STATUS { get; set; }
        public decimal T_FW_CONSP_SSP { get; set; }
        public decimal T_RW_EXPORTT_UNIT3 { get; set; }
        public decimal T_RW_IMPORTF_UNIT3 { get; set; }
        public decimal T_FW_IMPORTF_FB_UNIT3 { get; set; }
        public decimal T_FW_EXPORTT_UNIT3 { get; set; }
        public decimal T_FW_IMPORTF_UNIT3 { get; set; }
        public decimal T_FW_CONSP_NP_UNIT3 { get; set; }
        public decimal DIS_REC_WPT { get; set; }
        public decimal DIS_FBW_GP1 { get; set; }
        public decimal DIS_FBW_GP2 { get; set; }
        public decimal DIS_FBW_TOTAL { get; set; }
    }
}
