namespace itsppisapi.Models
{
    public class PBS210Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string S_TRANS_DATE { get; set; }
        public string S_USER_NAME { get; set; }
        public string S_USER_ID { get; set; }
        public string S_DATE_MOD { get; set; }
        public decimal NOBAG_G1_1 { get; set; }
        public decimal NOBAG_G1_2 { get; set; }
        public decimal NOBAG_G1_3 { get; set; }
        public decimal NOBAG_G1_4 { get; set; }
        public decimal NOBAG_G1_5 { get; set; }
        public decimal NOBAG_G1_6 { get; set; }
        public decimal NOBAG_G1_7 { get; set; }
        public decimal NOBAG_G1_8 { get; set; }
        public decimal NOBAG_G1_9 { get; set; }
        public decimal NOBAG_G1_10 { get; set; }
        public decimal BAGQTY_G1_1 { get; set; }
        public decimal BAGQTY_G1_2 { get; set; }
        public decimal BAGQTY_G1_3 { get; set; }
        public decimal BAGQTY_G1_4 { get; set; }
        public decimal BAGQTY_G1_5 { get; set; }
        public decimal BAGQTY_G1_6 { get; set; }
        public decimal BAGQTY_G1_7 { get; set; }
        public decimal BAGQTY_G1_8 { get; set; }
        public decimal BAGQTY_G1_9 { get; set; }
        public decimal BAGQTY_G1_10 { get; set; }
        public decimal NOBAG45_G1_1 { get; set; }
        public decimal NOBAG45_G1_2 { get; set; }
        public decimal NOBAG45_G1_3 { get; set; }
        public decimal NOBAG45_G1_4 { get; set; }
        public decimal NOBAG45_G1_5 { get; set; }
        public decimal NOBAG45_G1_6 { get; set; }
        public decimal NOBAG45_G1_7 { get; set; }
        public decimal NOBAG45_G1_8 { get; set; }
        public decimal NOBAG45_G1_9 { get; set; }
        public decimal NOBAG45_G1_10 { get; set; }
        public decimal NOBAG45_G1_11 { get; set; }
        public decimal NOBAG45_G1_12 { get; set; }
        public decimal NOBAG45_G1_13 { get; set; }
        public decimal BAGQTY45_G1_1 { get; set; }
        public decimal BAGQTY45_G1_2 { get; set; }
        public decimal BAGQTY45_G1_3 { get; set; }
        public decimal BAGQTY45_G1_4 { get; set; }
        public decimal BAGQTY45_G1_5 { get; set; }
        public decimal BAGQTY45_G1_6 { get; set; }
        public decimal BAGQTY45_G1_7 { get; set; }
        public decimal BAGQTY45_G1_8 { get; set; }
        public decimal BAGQTY45_G1_9 { get; set; }
        public decimal BAGQTY45_G1_10 { get; set; }
        public decimal BAGQTY45_G1_11 { get; set; }
        public decimal BAGQTY45_G1_12 { get; set; }
        public decimal BAGQTY45_G1_13 { get; set; }
        public decimal NOBAG_G2_1 { get; set; }
        public decimal NOBAG_G2_2 { get; set; }
        public decimal NOBAG_G2_3 { get; set; }
        public decimal NOBAG_G2_4 { get; set; }
        public decimal BAGQTY_G2_1 { get; set; }
        public decimal BAGQTY_G2_2 { get; set; }
        public decimal BAGQTY_G2_3 { get; set; }
        public decimal BAGQTY_G2_4 { get; set; }
        public decimal NOBAG45_G2_1 { get; set; }
        public decimal NOBAG45_G2_2 { get; set; }
        public decimal NOBAG45_G2_3 { get; set; }
        public decimal NOBAG45_G2_4 { get; set; }
        public decimal BAGQTY45_G2_1 { get; set; }
        public decimal BAGQTY45_G2_2 { get; set; }
        public decimal BAGQTY45_G2_3 { get; set; }
        public decimal BAGQTY45_G2_4 { get; set; }
        public decimal NOBAG45_G3_1 { get; set; }
        public decimal NOBAG45_G3_2 { get; set; }
        public decimal NOBAG45_G3_3 { get; set; }
        public decimal NOBAG45_G3_4 { get; set; }
        public decimal NOBAG45_G3_5 { get; set; }
        public decimal NOBAG45_G3_6 { get; set; }
        public decimal NOBAG45_G3_7 { get; set; }
        public decimal NOBAG45_G3_8 { get; set; }
        public decimal BAGQTY45_G3_1 { get; set; }
        public decimal BAGQTY45_G3_2 { get; set; }
        public decimal BAGQTY45_G3_3 { get; set; }
        public decimal BAGQTY45_G3_4 { get; set; }
        public decimal BAGQTY45_G3_5 { get; set; }
        public decimal BAGQTY45_G3_6 { get; set; }
        public decimal BAGQTY45_G3_7 { get; set; }
        public decimal BAGQTY45_G3_8 { get; set; }
        public decimal NOBAG_DISLV { get; set; }
        public decimal NOBAG_DISLV_U2 { get; set; }
        public decimal NOBAG_DISLV_U3 { get; set; }
        public decimal NOBAG_DISLV_UPH { get; set; }
        public decimal TOT { get; set; }
        public decimal DMG_BG_A { get; set; }
        public decimal DMG_BG_B { get; set; }
        public decimal DMG_BG_C { get; set; }
        public decimal TOTD { get; set; }
        public dynamic G_WEIGHT_OF_BAG { get; set; }
        public dynamic G_WEIGHT_OF_BAG_45 { get; set; }
    }
}
