namespace itsppisapi.Dtos
{
    public class PES301SaveDto
    {
        public string TDATE { get; set; }

        public string E3_DMY_FLG { get; set; }
        public decimal E3_GAS_TURBINE_GEN_INT { get; set; }
        public decimal E3_GAS_TURBINE_GEN_INT_DIFF { get; set; }
        public decimal E3_TOT_GEN { get; set; }

        public decimal E3_RECEIPT_FROM_JVVNL_GRID_INT { get; set; }
        public decimal E3_RECEIPT_FROM_JVVNL_GRID_INT_DIFF { get; set; }
        public decimal E3_11_KV_BUS_A_TO_ISBL_INT { get; set; }
        public decimal E3_11_KV_BUS_B_TO_ISBL_INT { get; set; }
        public decimal E3_CT_FEEDER_1_INT { get; set; }
        public decimal E3_CT_FEEDER_2_INT { get; set; }
        public decimal E3_TOT_11_KV_SUPPLY_TO_CT { get; set; }
        public decimal E3_PDG_T7 { get; set; }
        public decimal E3_PDG_T8 { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_UPH_1_INT { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_UPH_2_INT { get; set; }
        public decimal E3_11_KV_BUS_A_TO_ISBL_INT_DIFF { get; set; }
        public decimal E3_11_KV_BUS_B_TO_ISBL_INT_DIFF { get; set; }
        public decimal E3_TOT_11_KV_SUPPLY_TO_ISBL { get; set; }
        public decimal E3_CT_FEEDER_1_INT_DIFF { get; set; }
        public decimal E3_CT_FEEDER_2_INT_DIFF { get; set; }
        public decimal E3_PDG_T7_ID { get; set; }
        public decimal E3_PDG_T8_ID { get; set; }
        public decimal E3_TOT_11_KV_SUPPLY_TO_ONU_3 { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_UPH_1_INT_DIFF { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_UPH_2_INT_DIFF { get; set; }
        public decimal E3_11_KV_PWR_GP3_TOT_11_KV_SUPPLY { get; set; }
        public decimal E3_11_KV_PWR_GP3_UNACCOUNTED { get; set; }
        public decimal E3_PERCENTAGE_GEN { get; set; }

        public decimal E3_11_KV_SUPPLY_TO_UPH_3_FEEDER_1_INT { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_UPH_3_FEEDER_2_INT { get; set; }
        public decimal E3_TOT_11_KV_SUPPLY_TO_UPH_3 { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_ROZLD_FEEDER_1_INT { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_ROZLD_FEEDER_2_INT { get; set; }
        public decimal E3_TOT_11_KV_SUPPLY_TO_ROZLD { get; set; }
        public decimal E3_PDI11_T8 { get; set; }
        public decimal E3_PDI11_T9 { get; set; }
        public decimal E3_TOT_3_3_KV_TRSFER { get; set; }
        public decimal E3_SUPPLY_TO_AMM_11KV_MOTOR { get; set; }
        public decimal E3_11_KV_PWR_ISBL_TOT_11_KV_SUPPLY { get; set; }
        public decimal E3_11_KV_PWR_ISBL_UNACCOUNTED { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_UPH_3_FEEDER_1_INT_DIFF { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_UPH_3_FEEDER_2_INT_DIFF { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_ROZLD_FEEDER_1_INT_DIFF { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_ROZLD_FEEDER_2_INT_DIFF { get; set; }
        public decimal E3_PDI11_T8_ID { get; set; }
        public decimal E3_PDI11_T9_ID { get; set; }

        public decimal E3_AMM_415_V_PMCC_1_INT { get; set; }
        public decimal E3_AMM_415_V_PMCC_2_INT { get; set; }
        public decimal E3_UR_TA_PMCC_FEEDER_1_INT { get; set; }
        public decimal E3_UR_TA_PMCC_FEEDER_2_INT { get; set; }
        public decimal E3_UR_TB_PMCC_FEEDER_1_INT { get; set; }
        public decimal E3_UR_TB_PMCC_FEEDER_2_INT { get; set; }

        public decimal E3_SUPPLY_TO_UR_3_3_KV_MOTOR { get; set; }
        public decimal E3_TOT_3_3_KV_SUPPLY { get; set; }
        public decimal E3_3_3_KV_UNACCOUNTED { get; set; }
        public decimal E3_TOT_415V_PWR_AVAILABLE { get; set; }
        public decimal E3_LIGHTING_TRANSFMR_1_INT { get; set; }
        public decimal E3_LIGHTING_TRANSFMR_2_INT { get; set; }
        public decimal E3_TOT_LIGHT_LOAD { get; set; }
        public decimal E3_UPS_FEEDER_1_INT { get; set; }
        public decimal E3_UPS_FEEDER_2_INT { get; set; }
        public decimal E3_TOT_UPS_LOAD { get; set; }
        public decimal E3_HVAC_INT { get; set; }
        public decimal E3_CCR_HVAC_INT { get; set; }
        public decimal E3_OTHER_LT_LOADS { get; set; }
        public decimal E3_TOT_AMM_PWR_CONSP { get; set; }
        public decimal E3_TOT_UR_PWR_CONSP { get; set; }
        public decimal E3_AMM_415_V_PMCC_1_INT_DIFF { get; set; }
        public decimal E3_AMM_415_V_PMCC_2_INT_DIFF { get; set; }
        public decimal E3_UR_TA_PMCC_FEEDER_1_INT_DIFF { get; set; }
        public decimal E3_UR_TA_PMCC_FEEDER_2_INT_DIFF { get; set; }
        public decimal E3_UR_TB_PMCC_FEEDER_1_INT_DIFF { get; set; }
        public decimal E3_UR_TB_PMCC_FEEDER_2_INT_DIFF { get; set; }
        public string E3_LIGHTING_TRANSFMR_1_INT_DIFF { get; set; }
        public string E3_LIGHTING_TRANSFMR_2_INT_DIFF { get; set; }
        public string E3_UPS_FEEDER_1_INT_DIFF { get; set; }
        public string E3_UPS_FEEDER_2_INT_DIFF { get; set; }
        public string E3_HVAC_INT_DIFF { get; set; }
        public string E3_CCR_HVAC_INT_DIFF { get; set; }
        public string E3_SUPPLY_TO_PSA_MOTORS { get; set; }

        public string E3_11_KV_SUPPLY_TO_MP_7801C_INT { get; set; }
        public string E3_11_KV_SUPPLY_TO_MP_7808C_INT { get; set; }
        public string E3_SUPPLY_TO_415V_TRANSFMR_1_INT { get; set; }
        public string E3_SUPPLY_TO_415V_TRANSFMR_2_INT { get; set; }
        public string E3_11_KV_TOT_415V_AVAILABLE { get; set; }
        public string E3_11_KV_CT_UNACCOUNTED { get; set; }

        public string E3_3_3_KV_SUPPLY_TO_MP_7601B_INT { get; set; }
        public string E3_3_3_KV_SUPPLY_TO_MP_7811A_INT { get; set; }
        public string E3_3_3_KV_SUPPLY_TO_MP_7811B_INT { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_GTG_MOTOR_INT { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_UTIL_FEEDER_1_INT { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_UTIL_FEEDER_2_INT { get; set; }
        public decimal E3_TOT_SUPPLY_TO_UTIL { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_FAN_A_INT { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_FAN_B_INT { get; set; }
        public decimal E3_FROM_UNIT_1_2_TO_HRSG_FAN_INT { get; set; }
        public decimal E3_ONU_SUPPLY_TO_415V_TRANSMR_1_INT { get; set; }
        public decimal E3_ONU_SUPPLY_TO_415V_TRANSMR_2_INT { get; set; }
        public decimal E3_415_KV_TOT_3_3_KV_SUPPLY { get; set; }
        public decimal E3_ONU_UNACCOUNTED { get; set; }

        public decimal E3_TO_MAIN_AIR_COMP_INT { get; set; }
        public decimal E3_UTIL_SUPPLY_TO_415V_TRANSMR_1_INT { get; set; }
        public decimal E3_UTIL_SUPPLY_TO_415V_TRANSMR_2_INT { get; set; }
        public decimal E3_UTIL_UNACCOUNTED { get; set; }
        public decimal E3_UTIL_TOT_415V_AVAILABLE { get; set; }
        public decimal E3_RW_RESERVOIR_FEEDER_1_INT { get; set; }
        public decimal E3_DM4_CONSP { get; set; }
        public decimal E3_WPT3_CONSP { get; set; }
        public decimal E3_ETP_CONSP { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_MP_7801C_INT_DIFF { get; set; }
        public decimal E3_11_KV_SUPPLY_TO_MP_7808C_INT_DIFF { get; set; }
        public decimal E3_SUPPLY_TO_415V_TRANSFMR_1_INT_DIFF { get; set; }
        public decimal E3_SUPPLY_TO_415V_TRANSFMR_2_INT_DIFF { get; set; }
        public decimal E3_RW_RESERVOIR_FEEDER_2_INT { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_MP_7601B_INT_DIFF { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_MP_7811A_INT_DIFF { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_MP_7811B_INT_DIFF { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_GTG_MOTOR_INT_DIFF { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_UTIL_FEEDER_1_INT_DIFF { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_UTIL_FEEDER_2_INT_DIFF { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_FAN_A_INT_DIFF { get; set; }
        public decimal E3_3_3_KV_SUPPLY_TO_FAN_B_INT_DIFF { get; set; }
        public decimal E3_FROM_UNIT_1_2_TO_HRSG_FAN_INT_DIFF { get; set; }
        public decimal E3_ONU_SUPPLY_TO_415V_TRANSMR_1_INT_DIFF { get; set; }
        public decimal E3_ONU_SUPPLY_TO_415V_TRANSMR_2_INT_DIFF { get; set; }
        public decimal E3_TO_MAIN_AIR_COMP_INT_DIFF { get; set; }
        public decimal E3_UTIL_SUPPLY_TO_415V_TRANSMR_1_INT_DIFF { get; set; }
        public decimal E3_UTIL_SUPPLY_TO_415V_TRANSMR_2_INT_DIFF { get; set; }
        public decimal E3_RW_RESERVOIR_FEEDER_1_INT_DIFF { get; set; }
        public decimal E3_RW_RESERVOIR_FEEDER_2_INT_DIFF { get; set; }
        public decimal E3_RW_RESERVOIR_CONSP { get; set; }
        public string ENTERD_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public string ENTERED_DATETIME { get; set; }
        public string MODIFY_DATETIME { get; set; }
    }
}
