namespace itsppisapi.Models
{
    public class PAS001Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string A1_TRANS_DATE { get; set; }
        public dynamic A1_PRS_NG_FEED_REFMR_INT { get; set; }
        public dynamic A1_PRS_NG_FEED_REFMR_INT_DIFF { get; set; }
        public dynamic A1_TEMP_NG_FEED_REFMR_INT { get; set; }
        public dynamic A1_TEMP_NG_FEED_REFMR_INT_DIFF { get; set; }
        public dynamic A1_NG_FEED_REFMR_INT { get; set; }
        public dynamic A1_NG_FEED_REFMR_INT_DIFF { get; set; }
        public dynamic A1_MEAS_NG_CONSP_FEED_REFMR { get; set; }
        public dynamic A1_NG_CONSP_KRES_FEED_INT { get; set; }
        public dynamic A1_NG_CONSP_KRES_FEED_INT_DIFF { get; set; }
        public dynamic A1_NG_CONSP_KRES_FEED { get; set; }
        public dynamic A1_PRS_NG_FUEL_REFMR_INT { get; set; }
        public dynamic A1_PRS_NG_FUEL_REFMR_INT_DIFF { get; set; }
        public dynamic A1_TEMP_NG_FUEL_REFMR_INT { get; set; }
        public dynamic A1_TEMP_NG_FUEL_REFMR_INT_DIFF { get; set; }
        public dynamic A1_NG_FUEL_REFMR_INT { get; set; }
        public dynamic A1_NG_FUEL_REFMR_INT_DIFF { get; set; }
        public dynamic A1_NG_CONSP_FUEL_REFMR { get; set; }
        public dynamic A1_PRS_NG_FUEL_HEATER_INT { get; set; }
        public dynamic A1_PRS_NG_FUEL_HEATER_INT_DIFF { get; set; }
        public dynamic A1_NG_FUEL_HEATER_INT { get; set; }
        public dynamic A1_NG_FUEL_HEATER_INT_DIFF { get; set; }
        public dynamic A1_NG_CONSP_FUEL_HEATER { get; set; }
        public dynamic A1_NG_FUEL_ABURNER_INT { get; set; }
        public dynamic A1_NG_FUEL_ABURNER_INT_DIF { get; set; }
        public dynamic A1_NG_FUEL_ABURNER { get; set; }
        public dynamic A1_SPOT_GAS_ENG_ALLOC { get; set; }
        public dynamic A1_SPOT_GAS_ALLOC { get; set; }
        public dynamic A1_SPOT_GAS_RECEIPT { get; set; }
        public dynamic A1_NG_ALLOCATION { get; set; }
        public dynamic A1_APM_NG_RECEIPT { get; set; }
        public dynamic A1_NON_APM_ALLOC { get; set; }
        public dynamic A1_NON_APM_RECPT { get; set; }
        public dynamic A1_RLNG_ENG_ALLOC { get; set; }
        public dynamic A1_RLNG_ALLOCATION { get; set; }
        public dynamic A1_GAIL_RLNG_RECEIPT { get; set; }
        public dynamic A1_GAIL_LT_RLNG_FIRM_MMBTU { get; set; }
        public dynamic A1_GAIL_LT_RLNG_FIRM_ALLOC { get; set; }
        public dynamic A1_GAIL_LT_RLNG_FIRM_RECEIPT { get; set; }
        public dynamic A1_GAIL_LT_RLNG_RE_MMBTU { get; set; }
        public dynamic A1_GAIL_LT_RLNG_RE_ALLOC { get; set; }
        public dynamic A1_GAIL_LT_RLNG_RE_RECEIPT { get; set; }
        public dynamic A1_PMT_NG_ENG_ALLOC { get; set; }
        public dynamic A1_PMT_NG_ALLOC { get; set; }
        public dynamic A1_PMT_NG_RECEIPT { get; set; }
        public dynamic A1_RLNG_SPOT_ENG_ALLOC { get; set; }
        public dynamic A1_RLNG_SPOT_ALLOC { get; set; }
        public dynamic A1_RLNG_SPOT_RECPT { get; set; }
        public dynamic A1_FALLBACK_GAS_ALLOC { get; set; }
        public dynamic A1_NG_IMPORTF_UNIT2 { get; set; }
        public dynamic A1_NG_CONSP_UNIT2 { get; set; }
        public dynamic A1_AMM_CFG3_SPOT_GAS_ALLOC_ENG { get; set; }
        public dynamic A1_AMM_CFG3_SPOT_GAS_ALLOC_SM3 { get; set; }
        public dynamic A1_AMM_CFG3_SPOT_GAS_RECEIPT { get; set; }
        public dynamic A1_NG_CONSP_AMM { get; set; }
        public dynamic A1_BAL_NG_CONSP_FEED_REFMR { get; set; }
        public dynamic A1_NG_RECPT { get; set; }
        public string A1_NG_LIMITATION_FLG { get; set; }
        public dynamic A1_ACTL_NG_CV_NET { get; set; }
        public dynamic A1_RLNG_GCV { get; set; }
        public dynamic A1_MOL_WT_NG { get; set; }
        public dynamic A1_NG_CARBON_NO { get; set; }
        public string A1_GAIL_METER_ONLINE { get; set; }
        public dynamic A1_PRS_SURPLUS_GAS_INT { get; set; }
        public dynamic A1_PRS_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic A1_TEMP_SURPLUS_GAS_INT { get; set; }
        public dynamic A1_TEMP_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic A1_SURPLUS_GAS_INT { get; set; }
        public dynamic A1_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic A1_SURPLUS_GAS_PROD { get; set; }
        public dynamic A1_PRS_CO2_INT { get; set; }
        public dynamic A1_PRS_CO2_INT_DIFF { get; set; }
        public dynamic A1_TEMP_CO2_INT { get; set; }
        public dynamic A1_TEMP_CO2_INT_DIFF { get; set; }
        public dynamic A1_CO2_INT { get; set; }
        public dynamic A1_CO2_INT_DIFF { get; set; }
        public dynamic A1_CO2_PROD { get; set; }
        public dynamic A1_PRS_PERMEATE_INT { get; set; }
        public dynamic A1_PRS_PERMEATE_INT_DIFF { get; set; }
        public dynamic A1_TEMP_PERMEATE_INT { get; set; }
        public dynamic A1_TEMP_PERMEATE_INT_DIFF { get; set; }
        public dynamic A1_PERMEATE_INT { get; set; }
        public dynamic A1_PERMEATE_INT_DIFF { get; set; }
        public dynamic A1_PERMEATE_FLOW { get; set; }
        public dynamic A1_AMM_TANK_A_LEVEL { get; set; }
        public dynamic A1_AMM_TANK_A_STOCK { get; set; }
        public dynamic A1_AMM_TANK_B_LEVEL { get; set; }
        public dynamic A1_AMM_TANK_B_STOCK { get; set; }
        public dynamic A1_PROD_HRS { get; set; }
        public dynamic A1_PGRU_RUN_HRS { get; set; }
        public dynamic A1_HOT_AMM_TO_UREA_INT { get; set; }
        public dynamic A1_AMM_SUPP_UREA { get; set; }
        public dynamic A1_AMM_STORAGE_TO_UREA { get; set; }
        public dynamic A1_AMM_TRFR_UREA_SHIFT_A { get; set; }
        public dynamic A1_AMM_TRFR_UREA_SHIFT_B { get; set; }
        public dynamic A1_AMM_VAPOUR_EXPORTT_UNIT2 { get; set; }
        public dynamic A1_AMM_SALE { get; set; }
        public dynamic A1_AMM_PROD { get; set; }
        public dynamic A1_RECVFROM_AMM2_STOCK { get; set; }
        public dynamic A1_TFRTO_AMM2_STOCK { get; set; }
        public dynamic A1_RECVFROM_AMM3_STOCK { get; set; }
        public dynamic A1_AMM2_LOGICAL_STOCK { get; set; }
        public dynamic A1_TFRTO_AMM3_STOCK { get; set; }
        public dynamic A1_AMM3_LOGICAL_STOCK { get; set; }
        public dynamic A1_AMM1_LOGICAL_STOCK { get; set; }
        public dynamic A1_AMM_CAP_UTIL { get; set; }
        public string A1_REMARKS_D { get; set; }
        public string A1_REMARKS_M { get; set; }
        public dynamic A1_NAP_AMM_REFMR_INT { get; set; }
        public dynamic A1_NAP_CONSP_AMM_REFMR { get; set; }
        public dynamic A1_NAP_AMM_HEATER_INT { get; set; }
        public dynamic A1_NAP_CONSP_AMM_HEATER { get; set; }
        public dynamic A1_NAP_CONSP_AMM { get; set; }
        public dynamic A1_ATC_PROD_INT1 { get; set; }
        public dynamic A1_ATC_PROD_INT1_DIFF { get; set; }
        public dynamic A1_ATC_PROD_INT2 { get; set; }
        public dynamic A1_ATC_PROD_INT2_DIFF { get; set; }
        public dynamic A1_ATC_PROD_INT3 { get; set; }
        public dynamic A1_ATC_PROD_INT3_DIFF { get; set; }
        public dynamic A1_ATC_PROD_INT4 { get; set; }
        public dynamic A1_ATC_PROD_INT4_DIFF { get; set; }
        public dynamic A1_ATC_PROD { get; set; }
        public dynamic A1_PROCESS_STEAM_INT { get; set; }
        public dynamic A1_PROCESS_STEAMM_CONSP { get; set; }
        public dynamic A1_PROCESS_STEAM_KRES_INT { get; set; }
        public dynamic A1_PROCESS_STEAM_CONSP_KRES { get; set; }
        public dynamic A1_LS_CONSP_AMM_INT { get; set; }
        public dynamic A1_LS_CONSP_AMM { get; set; }
        public dynamic A1_AMM_SP_CONSP_FEED { get; set; }
        public dynamic A1_AMM_SP_CONSP_EQ_FUEL { get; set; }
        public dynamic A1_AMM_SP_CONSP_TOTAL_GAS { get; set; }
        public dynamic A1_AMM_SP_CONSP_KS { get; set; }
        public dynamic A1_AMM_SP_CONSP_HS { get; set; }
        public dynamic A1_AMM_SP_CONSP_LS { get; set; }
        public dynamic A1_AMM_SP_CONSP_CT { get; set; }
        public dynamic A1_AMM_SP_CONSP_DMW_IMPORT { get; set; }
        public dynamic A1_AMM_SP_CONSP_DMW_EXPORT { get; set; }
        public dynamic A1_AMM_SP_CONSP_DMW { get; set; }
        public dynamic A1_AMM_SP_CONSP_TC { get; set; }
        public dynamic A1_AMM_SP_CONSP_PC { get; set; }
        public dynamic A1_AMM_SP_CONSP_CONDENSATE { get; set; }
        public dynamic A1_AMM_SP_CONSP_NET_BFW { get; set; }
        public dynamic A1_UR_SP_CONSP_AMM { get; set; }
        public dynamic A1_UR_SP_CONSP_FEED { get; set; }
        public dynamic A1_UR_SP_CONSP_EQ_FUEL { get; set; }
        public dynamic A1_UR_SP_CONSP_TOTAL_FUEL { get; set; }
        public dynamic A1_UR_SP_CONSP_SPG_GAS { get; set; }
        public dynamic A1_UR_SP_CONSP_SPG_NAP { get; set; }
        public dynamic A1_UR_SP_CONSP_EQ_SPG { get; set; }
        public dynamic A1_UR_SP_CONSP_TOTAL_GAS { get; set; }
        public dynamic A1_SP_CONSP_ELECT_BL { get; set; }
        public dynamic A1_SP_CONSP_ELECT_CT { get; set; }
        public dynamic A1_SP_CONSP_ELECT_AMM_STRG { get; set; }
        public dynamic A1_AVG_NG_CV { get; set; }
        public dynamic A1_SP_ENG_FEED_GAS { get; set; }
        public dynamic A1_SP_ENG_FUEL { get; set; }
        public dynamic A1_SP_ENG_TOTAL { get; set; }
        public dynamic A1_SP_ENG_DIR_STEAM_BL { get; set; }
        public dynamic A1_SP_ENG_DIR_ELECT_BL { get; set; }
        public dynamic A1_SP_ENG_SUB_TOT_UTIL_BL { get; set; }
        public dynamic A1_SP_ENG_TOT_BL { get; set; }
        public dynamic A1_SP_ENG_CT_STEAM { get; set; }
        public dynamic A1_SP_ENG_CT_ELECT { get; set; }
        public dynamic A1_SP_ENG_SUB_TOT_UTIL { get; set; }
        public dynamic A1_SP_ENG_TOT_INCL_CT { get; set; }
        public dynamic A1_SP_ENG_OTH_UTIL_ALLOC { get; set; }
        public dynamic A1_SP_ENG_GROSS_ENG { get; set; }
        public dynamic A1_SP_ENG_CREDIT_BFW { get; set; }
        public dynamic A1_SP_ENG_GRAND_TOTAL { get; set; }
        public dynamic A1_SP_ENG_OVERALL_UREA { get; set; }
        public dynamic A1_AMM_BLOWER { get; set; }
        public dynamic A1_AMM_COMPRESSER_A { get; set; }
        public dynamic A1_AMM_COMPRESSER_B { get; set; }
        public dynamic A1_AMM_TRANS_PUMP { get; set; }
        public dynamic TXT_A_NG_EXPORTT_SSP { get; set; }
        public dynamic TXT_A_NG_CONSP_SPG { get; set; }
        public dynamic TXT_NG_EXPORTT_CFG3 { get; set; }
        public dynamic TXT_SYN_IMP_GP2 { get; set; }
        public dynamic TXT_SYN_EXP_GP2 { get; set; }
        public dynamic TXT_SUM_AMM_STK { get; set; }
        public dynamic TXT_AMM_COLD_STORAGE { get; set; }
        public dynamic TXT_OU_NAP_CONSP_SPG { get; set; }
        public dynamic TXT_OU_KS_CONSP_AMM { get; set; }
        public dynamic TXT_OU_HS_CONSP_AMM { get; set; }
        public dynamic TXT_E_ELECT_CONSP_AMM { get; set; }
        public dynamic TXT_E_ELECT_CONSP_ACT { get; set; }
        public dynamic TXT_E_ELECT_CONSP_AMMSTG { get; set; }
        public dynamic TXT_UR_SP_CONSP_ALLOC_GP2 { get; set; }
        public dynamic A1_GAIL_RLNG5_MMBTU { get; set; }
        public dynamic A1_GAIL_RLNG5_ALLOC { get; set; }
        public dynamic A1_GAIL_RLNG5_RECEIPT { get; set; }
        public dynamic A1_GAIL_RLNG19_MMBTU { get; set; }
        public dynamic A1_GAIL_RLNG19_ALLOC { get; set; }
        public dynamic A1_GAIL_RLNG19_RECEIPT { get; set; }
        public dynamic A1_GAIL_RLNG3_MMBTU { get; set; }
        public dynamic A1_GAIL_RLNG3_ALLOC { get; set; }
        public dynamic A1_GAIL_RLNG3_RECEIPT { get; set; }
        public dynamic A1_SPOT_GSPSC_MMBTU { get; set; }
        public dynamic A1_SPOT_GSPSC_ALLOC { get; set; }
        public dynamic A1_SPOT_GSPSC_RECEIPT { get; set; }
        public dynamic A1_SPOT_IOCL_MMBTU { get; set; }
        public dynamic A1_SPOT_IOCL_ALLOC { get; set; }
        public dynamic A1_SPOT_IOCL_RECEIPT { get; set; }
        public dynamic A1_SPOT_GAIL_MMBTU { get; set; }
        public dynamic A1_SPOT_GAIL_ALLOC { get; set; }
        public dynamic A1_SPOT_GAIL_RECEIPT { get; set; }
        public string A1_DATE_MOD { get; set; }
        public dynamic A1_USER_ID { get; set; }
        public string USER_NAME { get; set; }

        public dynamic A1_KS_STEAM_INT { get; set; }
        public dynamic A1_KS_STEAM_CONSP { get; set; }


        // --------PRIORITY-------------------
        public int ln_max_prior { get; set; }

        public int PMT_PSC_PRIORITY { get; set; }
        public int APM_NG_PRIORITY { get; set; }
        public int NON_APM_NG_PRIORITY { get; set; }
        public int RLNG_PRIORITY { get; set; }
        public int RLNG_MT_FIRM_PRIORITY { get; set; }
        public int RLNG_MT_RE_PRIORITY { get; set; }
        public int PMT_GAS_PRIORITY { get; set; }
        public int SPOT_RLNG_POOL_PRIORITY { get; set; }
        public int GAIL_LT_RLNG05_PRIORITY { get; set; }
        public int GAIL_LT_RLNG19_PRIORITY { get; set; }
        public int GAIL_LT_RLNG03_PRIORITY { get; set; }
        public int SPOT_GSPSC_PRIORITY { get; set; }
        public int SPOT_IOCL_PRIORITY { get; set; }
        public int SPOT_GAIL_PRIORITY { get; set; }
        public int CFG3_SPOT_GAS_PRIORITY { get; set; }

        public string PRIORITY_TAG1 { get; set; }
        public string PRIORITY_TAG2 { get; set; }
        public string PRIORITY_TAG3 { get; set; }
        public string PRIORITY_TAG4 { get; set; }
        public string PRIORITY_TAG5 { get; set; }
        public string PRIORITY_TAG6 { get; set; }
        public string PRIORITY_TAG7 { get; set; }
        public string PRIORITY_TAG8 { get; set; }
        public string PRIORITY_TAG9 { get; set; }
        public string PRIORITY_TAG10 { get; set; }
        public string PRIORITY_TAG11 { get; set; }
        public string PRIORITY_TAG12 { get; set; }
        public string PRIORITY_TAG13 { get; set; }
        public string PRIORITY_TAG14 { get; set; }
        public string PRIORITY_TAG15 { get; set; }


        // PRV
        public string PRV_A1_TRANS_DATE { get; set; }
        public dynamic PRV_A1_PRS_NG_FEED_REFMR_INT { get; set; }
        public dynamic PRV_A1_PRS_NG_FEED_REFMR_INT_DIFF { get; set; }
        public dynamic PRV_A1_TEMP_NG_FEED_REFMR_INT { get; set; }
        public dynamic PRV_A1_TEMP_NG_FEED_REFMR_INT_DIFF { get; set; }
        public dynamic PRV_A1_NG_FEED_REFMR_INT { get; set; }
        public dynamic PRV_A1_NG_FEED_REFMR_INT_DIFF { get; set; }
        public dynamic PRV_A1_MEAS_NG_CONSP_FEED_REFMR { get; set; }
        public dynamic PRV_A1_NG_CONSP_KRES_FEED_INT { get; set; }
        public dynamic PRV_A1_NG_CONSP_KRES_FEED_INT_DIFF { get; set; }
        public dynamic PRV_A1_NG_CONSP_KRES_FEED { get; set; }
        public dynamic PRV_A1_PRS_NG_FUEL_REFMR_INT { get; set; }
        public dynamic PRV_A1_PRS_NG_FUEL_REFMR_INT_DIFF { get; set; }
        public dynamic PRV_A1_TEMP_NG_FUEL_REFMR_INT { get; set; }
        public dynamic PRV_A1_TEMP_NG_FUEL_REFMR_INT_DIFF { get; set; }
        public dynamic PRV_A1_NG_FUEL_REFMR_INT { get; set; }
        public dynamic PRV_A1_NG_FUEL_REFMR_INT_DIFF { get; set; }
        public dynamic PRV_A1_NG_CONSP_FUEL_REFMR { get; set; }
        public dynamic PRV_A1_PRS_NG_FUEL_HEATER_INT { get; set; }
        public dynamic PRV_A1_PRS_NG_FUEL_HEATER_INT_DIFF { get; set; }
        public dynamic PRV_A1_NG_FUEL_HEATER_INT { get; set; }
        public dynamic PRV_A1_NG_FUEL_HEATER_INT_DIFF { get; set; }
        public dynamic PRV_A1_NG_CONSP_FUEL_HEATER { get; set; }
        public dynamic PRV_A1_NG_FUEL_ABURNER_INT { get; set; }
        public dynamic PRV_A1_NG_FUEL_ABURNER_INT_DIF { get; set; }
        public dynamic PRV_A1_NG_FUEL_ABURNER { get; set; }
        public dynamic PRV_A1_SPOT_GAS_ENG_ALLOC { get; set; }
        public dynamic PRV_A1_SPOT_GAS_ALLOC { get; set; }
        public dynamic PRV_A1_SPOT_GAS_RECEIPT { get; set; }
        public dynamic PRV_A1_NG_ALLOCATION { get; set; }
        public dynamic PRV_A1_APM_NG_RECEIPT { get; set; }
        public dynamic PRV_A1_NON_APM_ALLOC { get; set; }
        public dynamic PRV_A1_NON_APM_RECPT { get; set; }
        public dynamic PRV_A1_RLNG_ENG_ALLOC { get; set; }
        public dynamic PRV_A1_RLNG_ALLOCATION { get; set; }
        public dynamic PRV_A1_GAIL_RLNG_RECEIPT { get; set; }
        public dynamic PRV_A1_GAIL_LT_RLNG_FIRM_MMBTU { get; set; }
        public dynamic PRV_A1_GAIL_LT_RLNG_FIRM_ALLOC { get; set; }
        public dynamic PRV_A1_GAIL_LT_RLNG_FIRM_RECEIPT { get; set; }
        public dynamic PRV_A1_GAIL_LT_RLNG_RE_MMBTU { get; set; }
        public dynamic PRV_A1_GAIL_LT_RLNG_RE_ALLOC { get; set; }
        public dynamic PRV_A1_GAIL_LT_RLNG_RE_RECEIPT { get; set; }
        public dynamic PRV_A1_PMT_NG_ENG_ALLOC { get; set; }
        public dynamic PRV_A1_PMT_NG_ALLOC { get; set; }
        public dynamic PRV_A1_PMT_NG_RECEIPT { get; set; }
        public dynamic PRV_A1_RLNG_SPOT_ENG_ALLOC { get; set; }
        public dynamic PRV_A1_RLNG_SPOT_ALLOC { get; set; }
        public dynamic PRV_A1_RLNG_SPOT_RECPT { get; set; }
        public dynamic PRV_A1_FALLBACK_GAS_ALLOC { get; set; }
        public dynamic PRV_A1_NG_IMPORTF_UNIT2 { get; set; }
        public dynamic PRV_A1_NG_CONSP_UNIT2 { get; set; }
        public dynamic PRV_A1_AMM_CFG3_SPOT_GAS_ALLOC_ENG { get; set; }
        public dynamic PRV_A1_AMM_CFG3_SPOT_GAS_ALLOC_SM3 { get; set; }
        public dynamic PRV_A1_AMM_CFG3_SPOT_GAS_RECEIPT { get; set; }
        public dynamic PRV_A1_NG_CONSP_AMM { get; set; }
        public dynamic PRV_A1_BAL_NG_CONSP_FEED_REFMR { get; set; }
        public dynamic PRV_A1_NG_RECPT { get; set; }
        public string PRV_A1_NG_LIMITATION_FLG { get; set; }
        public dynamic PRV_A1_ACTL_NG_CV_NET { get; set; }
        public dynamic PRV_A1_RLNG_GCV { get; set; }
        public dynamic PRV_A1_MOL_WT_NG { get; set; }
        public dynamic PRV_A1_NG_CARBON_NO { get; set; }
        public string PRV_A1_GAIL_METER_ONLINE { get; set; }
        public dynamic PRV_A1_PRS_SURPLUS_GAS_INT { get; set; }
        public dynamic PRV_A1_PRS_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic PRV_A1_TEMP_SURPLUS_GAS_INT { get; set; }
        public dynamic PRV_A1_TEMP_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic PRV_A1_SURPLUS_GAS_INT { get; set; }
        public dynamic PRV_A1_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic PRV_A1_SURPLUS_GAS_PROD { get; set; }
        public dynamic PRV_A1_PRS_CO2_INT { get; set; }
        public dynamic PRV_A1_PRS_CO2_INT_DIFF { get; set; }
        public dynamic PRV_A1_TEMP_CO2_INT { get; set; }
        public dynamic PRV_A1_TEMP_CO2_INT_DIFF { get; set; }
        public dynamic PRV_A1_CO2_INT { get; set; }
        public dynamic PRV_A1_CO2_INT_DIFF { get; set; }
        public dynamic PRV_A1_CO2_PROD { get; set; }
        public dynamic PRV_A1_PRS_PERMEATE_INT { get; set; }
        public dynamic PRV_A1_PRS_PERMEATE_INT_DIFF { get; set; }
        public dynamic PRV_A1_TEMP_PERMEATE_INT { get; set; }
        public dynamic PRV_A1_TEMP_PERMEATE_INT_DIFF { get; set; }
        public dynamic PRV_A1_PERMEATE_INT { get; set; }
        public dynamic PRV_A1_PERMEATE_INT_DIFF { get; set; }
        public dynamic PRV_A1_PERMEATE_FLOW { get; set; }
        public dynamic PRV_A1_AMM_TANK_A_LEVEL { get; set; }
        public dynamic PRV_A1_AMM_TANK_A_STOCK { get; set; }
        public dynamic PRV_A1_AMM_TANK_B_LEVEL { get; set; }
        public dynamic PRV_A1_AMM_TANK_B_STOCK { get; set; }
        public dynamic PRV_A1_PROD_HRS { get; set; }
        public dynamic PRV_A1_PGRU_RUN_HRS { get; set; }
        public dynamic PRV_A1_HOT_AMM_TO_UREA_INT { get; set; }
        public dynamic PRV_A1_AMM_SUPP_UREA { get; set; }
        public dynamic PRV_A1_AMM_STORAGE_TO_UREA { get; set; }
        public dynamic PRV_A1_AMM_TRFR_UREA_SHIFT_A { get; set; }
        public dynamic PRV_A1_AMM_TRFR_UREA_SHIFT_B { get; set; }
        public dynamic PRV_A1_AMM_VAPOUR_EXPORTT_UNIT2 { get; set; }
        public dynamic PRV_A1_AMM_SALE { get; set; }
        public dynamic PRV_A1_AMM_PROD { get; set; }
        public dynamic PRV_A1_RECVFROM_AMM2_STOCK { get; set; }
        public dynamic PRV_A1_TFRTO_AMM2_STOCK { get; set; }
        public dynamic PRV_A1_RECVFROM_AMM3_STOCK { get; set; }
        public dynamic PRV_A1_AMM2_LOGICAL_STOCK { get; set; }
        public dynamic PRV_A1_TFRTO_AMM3_STOCK { get; set; }
        public dynamic PRV_A1_AMM3_LOGICAL_STOCK { get; set; }
        public dynamic PRV_A1_AMM1_LOGICAL_STOCK { get; set; }
        public dynamic PRV_A1_AMM_CAP_UTIL { get; set; }
        public string PRV_A1_REMARKS { get; set; }
        public dynamic PRV_A1_NAP_AMM_REFMR_INT { get; set; }
        public dynamic PRV_A1_NAP_CONSP_AMM_REFMR { get; set; }
        public dynamic PRV_A1_NAP_AMM_HEATER_INT { get; set; }
        public dynamic PRV_A1_NAP_CONSP_AMM_HEATER { get; set; }
        public dynamic PRV_A1_NAP_CONSP_AMM { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT1 { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT1_DIFF { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT2 { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT2_DIFF { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT3 { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT3_DIFF { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT4 { get; set; }
        public dynamic PRV_A1_ATC_PROD_INT4_DIFF { get; set; }
        public dynamic PRV_A1_ATC_PROD { get; set; }
        public dynamic PRV_A1_PROCESS_STEAM_INT { get; set; }
        public dynamic PRV_A1_PROCESS_STEAMM_CONSP { get; set; }
        public dynamic PRV_A1_PROCESS_STEAM_KRES_INT { get; set; }
        public dynamic PRV_A1_PROCESS_STEAM_CONSP_KRES { get; set; }
        public dynamic PRV_A1_LS_CONSP_AMM_INT { get; set; }
        public dynamic PRV_A1_LS_CONSP_AMM { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_FEED { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_EQ_FUEL { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_TOTAL_GAS { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_KS { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_HS { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_LS { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_CT { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_DMW_IMPORT { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_DMW_EXPORT { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_DMW { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_TC { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_PC { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_CONDENSATE { get; set; }
        public dynamic PRV_A1_AMM_SP_CONSP_NET_BFW { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_AMM { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_FEED { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_EQ_FUEL { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_TOTAL_FUEL { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_SPG_GAS { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_SPG_NAP { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_EQ_SPG { get; set; }
        public dynamic PRV_A1_UR_SP_CONSP_TOTAL_GAS { get; set; }
        public dynamic PRV_A1_SP_CONSP_ELECT_BL { get; set; }
        public dynamic PRV_A1_SP_CONSP_ELECT_CT { get; set; }
        public dynamic PRV_A1_SP_CONSP_ELECT_AMM_STRG { get; set; }
        public dynamic PRV_A1_AVG_NG_CV { get; set; }
        public dynamic PRV_A1_SP_ENG_FEED_GAS { get; set; }
        public dynamic PRV_A1_SP_ENG_FUEL { get; set; }
        public dynamic PRV_A1_SP_ENG_TOTAL { get; set; }
        public dynamic PRV_A1_SP_ENG_DIR_STEAM_BL { get; set; }
        public dynamic PRV_A1_SP_ENG_DIR_ELECT_BL { get; set; }
        public dynamic PRV_A1_SP_ENG_SUB_TOT_UTIL_BL { get; set; }
        public dynamic PRV_A1_SP_ENG_TOT_BL { get; set; }
        public dynamic PRV_A1_SP_ENG_CT_STEAM { get; set; }
        public dynamic PRV_A1_SP_ENG_CT_ELECT { get; set; }
        public dynamic PRV_A1_SP_ENG_SUB_TOT_UTIL { get; set; }
        public dynamic PRV_A1_SP_ENG_TOT_INCL_CT { get; set; }
        public dynamic PRV_A1_SP_ENG_OTH_UTIL_ALLOC { get; set; }
        public dynamic PRV_A1_SP_ENG_GROSS_ENG { get; set; }
        public dynamic PRV_A1_SP_ENG_CREDIT_BFW { get; set; }
        public dynamic PRV_A1_SP_ENG_GRAND_TOTAL { get; set; }
        public dynamic PRV_A1_SP_ENG_OVERALL_UREA { get; set; }
        public dynamic PRV_A1_AMM_BLOWER { get; set; }
        public dynamic PRV_A1_AMM_COMPRESSER_A { get; set; }
        public dynamic PRV_A1_AMM_COMPRESSER_B { get; set; }
        public dynamic PRV_A1_AMM_TRANS_PUMP { get; set; }
        public dynamic PRV_TXT_A_NG_EXPORTT_SSP { get; set; }
        public dynamic PRV_TXT_A_NG_CONSP_SPG { get; set; }
        public dynamic PRV_TXT_NG_EXPORTT_CFG3 { get; set; }
        public dynamic PRV_TXT_SYN_IMP_GP2 { get; set; }
        public dynamic PRV_TXT_SYN_EXP_GP2 { get; set; }
        //public dynamic PRV_TXT_SYN_EXP_GP2 { get; set; }
        public dynamic PRV_TXT_SUM_AMM_STK { get; set; }
        public dynamic PRV_TXT_AMM_COLD_STORAGE { get; set; }
        public dynamic PRV_TXT_OU_NAP_CONSP_SPG { get; set; }
        public dynamic PRV_TXT_OU_KS_CONSP_AMM { get; set; }
        public dynamic PRV_TXT_OU_HS_CONSP_AMM { get; set; }
        public dynamic PRV_TXT_E_ELECT_CONSP_AMM { get; set; }
        public dynamic PRV_TXT_E_ELECT_CONSP_ACT { get; set; }
        public dynamic PRV_TXT_E_ELECT_CONSP_AMMSTG { get; set; }
        public dynamic PRV_TXT_UR_SP_CONSP_ALLOC_GP2 { get; set; }
        public dynamic PRV_A1_GAIL_RLNG5_MMBTU { get; set; }
        public dynamic PRV_A1_GAIL_RLNG5_ALLOC { get; set; }
        public dynamic PRV_A1_GAIL_RLNG5_RECEIPT { get; set; }
        public dynamic PRV_A1_GAIL_RLNG19_MMBTU { get; set; }
        public dynamic PRV_A1_GAIL_RLNG19_ALLOC { get; set; }
        public dynamic PRV_A1_GAIL_RLNG19_RECEIPT { get; set; }
        public dynamic PRV_A1_SPOT_GSPSC_MMBTU { get; set; }
        public dynamic PRV_A1_SPOT_GSPSC_ALLOC { get; set; }
        public dynamic PRV_A1_SPOT_GSPSC_RECEIPT { get; set; }
        public dynamic PRV_A1_SPOT_IOCL_MMBTU { get; set; }
        public dynamic PRV_A1_SPOT_IOCL_ALLOC { get; set; }
        public dynamic PRV_A1_SPOT_IOCL_RECEIPT { get; set; }
        public dynamic PRV_A1_SPOT_GAIL_MMBTU { get; set; }
        public dynamic PRV_A1_SPOT_GAIL_ALLOC { get; set; }
        public dynamic PRV_A1_SPOT_GAIL_RECEIPT { get; set; }
        
        public dynamic PRV_A1_KS_STEAM_INT { get; set; }

    }
}
