namespace itsppisapi.Models
{
    public class PAS005Model
    {
        public string MINMONTH { get; set; }
        public decimal MINYEAR { get; set; }
        public string MAXMONTH { get; set; }
        public decimal MAXYEAR { get; set; }
        public string A1_MONTH { get; set; }
        public decimal A1_YEAR { get; set; }
        public decimal A1_USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string A1_DATE_MOD { get; set; }
        
        public decimal A1_AMM_BUDG_SP_GAS_1 { get; set; }
        public decimal A1_AMM_ACTL_SP_GAS_1 { get; set; }
        public decimal A1_AMM_CONSP_VAR_1 { get; set; }
        public decimal A1_AMM_SGAS_BURNT_1 { get; set; }
        public decimal A1_AMM_ADD_FLARING { get; set; }
        public decimal A1_AMM_USAGE_CONSP_VAR { get; set; }
        public decimal A1_AMM_OTHERS { get; set; }
        public decimal A1_AMM_NET_CONSP_VAR_1 { get; set; }
        public decimal A1_SPG_BUDG_SP_GAS { get; set; }
        public decimal A1_SPG_ACTL_SP_GAS { get; set; }
        public decimal A1_SPG_CONSP_VAR { get; set; }
        public decimal A1_SPG_2GTG_VAR { get; set; }
        public decimal A1_SPG_SU_SD_VAR { get; set; }
        public decimal A1_SPG_USAGE_CONSP_VAR { get; set; }
        public decimal A1_SPG_UTILITY_DMD_VAR { get; set; }
        public decimal A1_SPG_OTHERS { get; set; }
        public decimal A1_SPG_NET_CONSP_VAR { get; set; }
        public decimal A1_AMM_BUDG_PROD { get; set; }
        public decimal A1_AMM_ACTL_PROD { get; set; }
        public decimal A1_AMM_VOL_VAR { get; set; }
        public decimal A1_AMM_PROD_ADJ_VOL_VAR { get; set; }
        public decimal A1_AMM_BUDG_STREAM_DAYS { get; set; }
        public decimal A1_AMM_ACTL_STREAM_DAYS { get; set; }
        public decimal A1_AMM_STREAM_DAYS_LOST { get; set; }
        public decimal A1_AMM_PROD_LOST { get; set; }
        public decimal A1_AMM_PROD_LOST_GAS_LIMIT { get; set; }
        public decimal A1_AMM_PROD_LOST_SGAS { get; set; }
        public decimal A1_AMM_TOT_ACC_PROD_LOST { get; set; }
        public decimal A1_UREA_BUDG_PROD { get; set; }
        public decimal A1_UREA_ACTL_PROD { get; set; }
        public decimal A1_UREA_VOL_VAR { get; set; }
        public decimal A1_UREA_PROD_ADJ_VOL_VAR { get; set; }
        public decimal A1_UREA_BUDG_STREAM_DAYS { get; set; }
        public decimal A1_UREA_ACTL_STREAM_DAYS { get; set; }
        public decimal A1_UREA_STREAM_DAYS_LOST { get; set; }
        public decimal A1_UREA_PROD_LOST { get; set; }
        public decimal A1_UREA_PROD_LOST_GAS_LIMIT { get; set; }
        public decimal A1_UREA_TOT_ACC_PROD_LOST { get; set; }
        public decimal A1_AMM_BUDG_SP_GAS_2 { get; set; }
        public decimal A1_AMM_ACTL_SP_GAS_2 { get; set; }
        public decimal A1_AMM_ACTL_SP_GAS_AFTER_COMP { get; set; }
        public decimal A1_AMM_CONSP_VAR_2 { get; set; }
        public decimal A1_AMM_CONSP_VAR_PROD_ADJ { get; set; }
        public decimal A1_AMM_NET_CONSP_VAR_2 { get; set; }
        public decimal A1_AMM_SGAS_BURNT_2 { get; set; }
        public decimal A1_AMM_BUDG_SGAS_BURNT { get; set; }
        public decimal A1_AMM_ADDL_SGAS_BURNT { get; set; }
        public decimal A1_AMM_EQ_FUEL_ADDL_SGAS { get; set; }
        public decimal A1_AMM_EQ_AMM_PROD_SGAS { get; set; }
        public decimal A1_AMM_GROSS_GAS_CONSP_SGAS { get; set; }
        public decimal A1_AMM_GROSS_AMM_PROD_SGAS { get; set; }
        public decimal A1_AMM_SP_GAS_AFTER_SGAS { get; set; }
        public decimal A1_AMM_CONSP_VAR_SGAS { get; set; }
        public decimal A1_AMM_UNPROD_GAS_FLARING { get; set; }
        public decimal A1_AMM_BUDG_UNPROD_GAS_FLARING { get; set; }
        public decimal A1_AMM_NET_ADDL_UNPOROD_GAS { get; set; }
        public decimal A1_AMM_VAR_ADDL_FLARING { get; set; }
        public decimal A1_AMM_TOT_ACCT_VAR_ADDL_FLR { get; set; }
        public decimal A1_AMM_USAGE_VAR_ADDL_FLARING { get; set; }
        public decimal A1_SPG_BUDG_FUEL_SPG { get; set; }
        public decimal A1_SPG_ACTL_FUEL_SPG { get; set; }
        public decimal A1_SPG_EXTRA_FUEL_SPG { get; set; }
        public decimal A1_SPG_NET_VAR_AFTER_PROD_ADJ { get; set; }
        public decimal A1_SPG_HRS_2GTGS { get; set; }
        public decimal A1_SPG_IDLE_GAS_CONSP_2GTGS { get; set; }
        public decimal A1_SPG_2GTGS_VAR_PMT_UREA { get; set; }
        public decimal A1_SPG_NO_GT_STARTUP { get; set; }
        public decimal A1_SPG_GAS_GT_STARTUP { get; set; }
        public decimal A1_SPG_NO_AB_STARTUP { get; set; }
        public decimal A1_SPG_GAS_AB_STARTUP { get; set; }
        public decimal A1_SPG_TOT_GAS_SU_SD { get; set; }
        public decimal A1_UREA_NO_STARTUP { get; set; }
        public decimal A1_UREA_STEAM_STARTUP { get; set; }
        public decimal A1_UREA_GAS_STARTUP { get; set; }
        public decimal A1_TOT_STARTUP_LOSSES { get; set; }
        public decimal A1_VAR_STARTUP { get; set; }
        public decimal A1_UREA_BUDG_STM_CONSP { get; set; }
        public decimal A1_UREA_ACTL_STM_CONSP { get; set; }
        public decimal A1_UREA_ADDL_STM_CONSP { get; set; }
        public decimal A1_UREA_TOT_ADDL_STM_CONSP { get; set; }
        public decimal A1_UREA_LESS_STM_CONSP { get; set; }
        public decimal A1_UREA_NET_ADDL_STM_CONSP { get; set; }
        public decimal A1_UREA_GAS_CONSP_ADDL_STM { get; set; }
        public decimal A1_UREA_ADDL_STM_CONSP_VAR { get; set; }
        public decimal A1_AMM_BUDG_STM_CONSP { get; set; }
        public decimal A1_AMM_ACTL_STM_CONSP { get; set; }
        public decimal A1_AMM_ADDL_STM_CONSP { get; set; }
        public decimal A1_AMM_TOT_ADDL_STM_CONSP { get; set; }
        public decimal A1_AMM_GAS_CONSP_ADDL_STM { get; set; }
        public decimal A1_AMM_ADDL_STM_CONSP_VAR { get; set; }
        public decimal A1_UREA_BUDG_PROD_PWR_CONSP { get; set; }
        public decimal A1_UREA_TOT_PROD_PWR_DEMAND { get; set; }
        public decimal A1_UREA_ACTL_PROD_PWR_CONSP { get; set; }
        public decimal A1_UREA_ADDL_PWR_CONSP { get; set; }
        public decimal A1_UREA_GAS_CONSP_ADDL_PWR { get; set; }
        public decimal A1_UREA_PROD_PWR_CONSP_VAR { get; set; }
        public decimal A1_AMM_BUDG_PROD_PWR_CONSP { get; set; }
        public decimal A1_AMM_TOT_PROD_PWR_DEMAND { get; set; }
        public decimal A1_AMM_ACTL_PROD_PWR_CONSP { get; set; }
        public decimal A1_AMM_ADDL_PWR_CONSP { get; set; }
        public decimal A1_AMM_GAS_CONSP_ADDL_PWR { get; set; }
        public decimal A1_AMM_PROD_PWR_CONSP_VAR { get; set; }
        public decimal A1_TOT_ACC_VAR_SPG_FUEL { get; set; }
        public decimal A1_TOT_USAGE_VAR_SPG_FUEL { get; set; }
        public decimal A1_UREA_BUDG_OVERALL { get; set; }
        public decimal A1_UREA_ACTL_OVERALL { get; set; }
        public decimal A1_UREA_NET_VAR { get; set; }
        public decimal A1_AMM_FEED_FUEL { get; set; }
        public decimal A1_SPG_FUEL { get; set; }
        public decimal A1_TOT_ACCT_VAR { get; set; }
        public decimal A1_TOT_USAGE_VAR { get; set; }
    }
}
