namespace itsppisapi.Models
{
    public class PAS212Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string A2_TRANS_DATE { get; set; }
        public dynamic A2_PRS_CO2_INT { get; set; }
        public dynamic A2_TEMP_CO2_INT { get; set; }
        public dynamic A2_CO2_INT { get; set; }
        public dynamic A2_CO2_INT_DIFF { get; set; }
        public dynamic A2_CO2_PROD { get; set; }
        public dynamic A2_PRS_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_TEMP_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_CO2_EXPORTT_GP1_INT_DIFF { get; set; }
        public dynamic A2_CO2_EXPORTT_GP1 { get; set; }
        public dynamic A2_CO2_SUPPLY_UREA { get; set; }
        public dynamic A2_PRS_PERMEATE_INT { get; set; }
        public dynamic A2_PRS_PERMEATE_INT_DIFF { get; set; }
        public dynamic A2_TEMP_PERMEATE_INT { get; set; }
        public dynamic A2_TEMP_PERMEATE_INT_DIFF { get; set; }
        public dynamic A2_PERMEATE_INT { get; set; }
        public dynamic A2_PERMEATE_INT_DIFF { get; set; }
        public dynamic A2_PERMEATE_FLOW { get; set; }
        public dynamic A2_PROD_HRS { get; set; }
        public dynamic A2_PGRU_RUN_HRS { get; set; }
        public dynamic A2_AMM_SALE { get; set; }
        public dynamic A2_PGRU_PROD { get; set; }
        public dynamic A2_AMM_SUPP_UREA_INT { get; set; }
        public dynamic A2_AMM_SUPP_UREA { get; set; }
        public dynamic A2_AMM_TO_STORAGE_INT { get; set; }
        public dynamic A2_AMM_TO_STORAGE { get; set; }
        public dynamic A2_PRS_VAPOUR_AMM_ACTL { get; set; }
        public dynamic A2_TOT_VPR_TO_AMM2_INT { get; set; }
        public dynamic A2_TOT_VPR_TO_AMM2_INT_DIFF { get; set; }
        public dynamic A2_TOT_VPR_TO_AMM2 { get; set; }
        public dynamic A2_VPR1_TO_AMM2 { get; set; }
        public dynamic A2_VPR2_TO_AMM2 { get; set; }
        public dynamic A2_AMM_PROD { get; set; }
        public dynamic A2_AMM2_LOGICAL_STOCK { get; set; }
        public dynamic A2_AMM_CAP_UTIL { get; set; }
        public string A2_REMARKS { get; set; }
        public dynamic A2_SP_FEED_NG { get; set; }
        public dynamic A2_SP_FUEL_NG { get; set; }
        public dynamic A2_SP_TOT_NG { get; set; }
        public dynamic A2_SP_FEED_NAP { get; set; }
        public dynamic A2_SP_FUEL_NAP { get; set; }
        public dynamic A2_SP_TOT_NAP { get; set; }
        public dynamic A2_SP_PW_AMM { get; set; }
        public dynamic A2_SP_ATC_EXP { get; set; }
        public dynamic A2_SP_APC_EXP { get; set; }
        public dynamic A2_SP_ASC_EXP { get; set; }
        public dynamic A2_SP_ACTTC_EXP { get; set; }
        public dynamic A2_SP_TOT_COND_EXP_AMM2 { get; set; }
        public dynamic A2_SP_PW_IMP_AMM2 { get; set; }
        public dynamic A2_SP_SH_STEAM_AMM2 { get; set; }
        public dynamic A2_SP_SM_STEAM_EXP_ACT { get; set; }
        public dynamic A2_SP_PWR_CONSP_AMM2 { get; set; }
        public dynamic A2_SP_PWR_AMM2 { get; set; }
        public dynamic A2_SP_PWR_CONSP_ACT { get; set; }
        public dynamic A2_SP_COOL_WTR_AMM2 { get; set; }
        public dynamic A2_SP_UR_NG_AMM2 { get; set; }
        public dynamic A2_SP_UR_NG_AB { get; set; }
        public dynamic A2_SP_UR_TOT_COOL_WTR { get; set; }
        public dynamic A2_SP_UR_NAP_AMM2 { get; set; }
        public dynamic A2_SP_UR_NAP_AB { get; set; }
        public dynamic A2_SP_UR_DMW_AMM2 { get; set; }
        public dynamic A2_ENG_FEED_GAS { get; set; }
        public dynamic A2_ENG_FUEL_GAS { get; set; }
        public dynamic A2_ENG_TOT_GAS { get; set; }
        public dynamic A2_ENG_FEED_NAP { get; set; }
        public dynamic A2_ENG_FUEL_NAP { get; set; }
        public dynamic A2_ENG_TOT_NAP { get; set; }
        public dynamic A2_ENG_TOT_GAS_NAP { get; set; }
        public dynamic A2_ENG_SH_STEAM_AMM2 { get; set; }
        public dynamic A2_ENG_PWR_AMM2 { get; set; }
        public dynamic A2_ENG_TOT_AMM2 { get; set; }
        public dynamic A2_ENG_ACT_STEAM { get; set; }
        public dynamic A2_ENG_ACT_PWR { get; set; }
        public dynamic A2_ENG_TOT_CT { get; set; }
        public dynamic A2_ENG_CR_BWF_PHEAT { get; set; }
        public dynamic A2_ENG_CR_BFW_PWR { get; set; }
        public dynamic A2_ENG_CR_TOT_SH_EXP { get; set; }
        public dynamic A2_ENG_NET_ENG { get; set; }
        public dynamic A2_ENG_USP_FEED_FUEL_AMM2 { get; set; }
        public dynamic A2_ENG_USP_FUEL_AB { get; set; }
        public dynamic A2_SPE_ALLOC_EQ_NAP_PWR_UTIL { get; set; }
        public dynamic A2_ENG_NET_UREA { get; set; }
        public dynamic DIS_TOT_AMM_STOCK { get; set; }
        public dynamic DIS_AMM1_LSTOCK { get; set; }
        public string A2_DATE_MOD { get; set; }
        public decimal A2_USER_ID { get; set; }
        public string USER_NAME { get; set; }
    }
}