namespace itsppisapi.Models
{
    public class PAS201Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string A2_TRANS_DATE { get; set; }
        public dynamic A2_NG_TOT_AMM2_INT { get; set; }
        public dynamic A2_NG_TOT_AMM2_INT_DIFF { get; set; }
        public dynamic A2_NG_TOT_CONSP_AMM2 { get; set; }
        public dynamic A2_PRS_NG_FUEL_AB_INT { get; set; }
        public dynamic A2_PRS_NG_FUEL_AB_INT_DIFF { get; set; }
        public dynamic A2_TEMP_NG_FUEL_AB_INT { get; set; }
        public dynamic A2_TEMP_NG_FUEL_AB_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_AB_INT { get; set; }
        public dynamic A2_NG_FUEL_AB_INT_DIFF { get; set; }
        public dynamic A2_NG_CONSP_AB { get; set; }
        public dynamic A2_NG_FEED_AMM2_INT { get; set; }
        public dynamic A2_NG_FEED_AMM2_INT_DIFF { get; set; }
        public dynamic A2_NG_CONSP_FEED_AMM2 { get; set; }
        public dynamic A2_PRS_TOT_NG_FUEL_INT { get; set; }
        public dynamic A2_PRS_TOT_NG_FUEL_INT_DIFF { get; set; }
        public dynamic A2_TEMP_TOT_NG_FUEL_INT { get; set; }
        public dynamic A2_TEMP_TOT_NG_FUEL_INT_DIFF { get; set; }
        public dynamic A2_TOT_NG_FUEL_INT { get; set; }
        public dynamic A2_TOT_NG_FUEL_INT_DIFF { get; set; }
        public dynamic A2_TOT_CONSP_NG_FUEL { get; set; }
        public dynamic A2_PRS_NG_SH_BURN_INT { get; set; }
        public dynamic A2_PRS_NG_SH_BURN_INT_DIFF { get; set; }
        public dynamic A2_TEMP_NG_SH_BURN_INT { get; set; }
        public dynamic A2_TEMP_NG_SH_BURN_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_SH_BURN_INT { get; set; }
        public dynamic A2_NG_FUEL_SH_BURN_INT_DIFF { get; set; }
        public dynamic A2_BAL_NG_FUEL_SH_BURNER { get; set; }
        public dynamic A2_PRS_NG_FUEL_TBURNER_INT { get; set; }
        public dynamic A2_PRS_NG_FUEL_TBURNER_INT_DIFF { get; set; }
        public dynamic A2_TEMP_NG_FUEL_TBURNER_INT { get; set; }
        public dynamic A2_TEMP_NG_FUEL_TBURNER_INT_DIF { get; set; }
        public dynamic A2_NG_FUEL_TBURNER_INT { get; set; }
        public dynamic A2_NG_FUEL_TBURNER_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_TBURNER { get; set; }
        public dynamic A2_PRS_NG_FUEL_BA101_INT { get; set; }
        public dynamic A2_PRS_NG_FUEL_BA101_INT_DIFF { get; set; }
        public dynamic A2_TEMP_NG_FUEL_BA101_INT { get; set; }
        public dynamic A2_TEMP_NG_FUEL_BA101_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_BA101_INT { get; set; }
        public dynamic A2_NG_FUEL_BA101_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_BA101 { get; set; }
        public dynamic A2_PRS_NG_FUEL_BA102_INT { get; set; }
        public dynamic A2_PRS_NG_FUEL_BA102_INT_DIFF { get; set; }
        public dynamic A2_TEMP_NG_FUEL_BA102_INT { get; set; }
        public dynamic A2_TEMP_NG_FUEL_BA102_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_BA102_INT { get; set; }
        public dynamic A2_NG_FUEL_BA102_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_BA102 { get; set; }
        public dynamic A2_NG_FUEL_ABURNER { get; set; }
        public dynamic A2_PRS_FUEL_FLARE_INT { get; set; }
        public dynamic A2_PRS_FUEL_FLARE_INT_DIFF { get; set; }
        public dynamic A2_TEMP_FUEL_FLARE_INT { get; set; }
        public dynamic A2_TEMP_FUEL_FLARE_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_FLARE_INT { get; set; }
        public dynamic A2_NG_FUEL_FLARE_INT_DIFF { get; set; }
        public dynamic A2_NG_FUEL_FLARE { get; set; }
        public dynamic A2_NG_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_NG_EXPORTT_GP1_INT_DIFF { get; set; }
        public dynamic A2_NG_EXPORTT_UNIT1_SSP { get; set; }
        public dynamic A2_NG_SYNTH_GAS_INT { get; set; }
        public dynamic A2_NG_SYNTH_GAS_INT_DIFF { get; set; }
        public dynamic A2_SYNTH_GAS_EXPTT_GP1_INT { get; set; }
        public dynamic A2_SYNTH_GAS_EXPTT_GP1_INT_DIFF { get; set; }
        public dynamic A2_NG_EXPORTT_UNIT1 { get; set; }
        public dynamic A2_NG_EXPORTT_SSP { get; set; }
        public dynamic A2_RIL_SCH_ENG_GCV { get; set; }
        public string A2_GAIL_METER_ONLINE { get; set; }
        public dynamic A2_RIL_GAS_ENERGY_ACTL_GCV { get; set; }
        public dynamic A2_RIL_GAS_ENERGY { get; set; }
        public dynamic A2_RIL_SCH_GAS { get; set; }
        public dynamic A2_RIL_GAS_RECEIPT_ACTL_GCV { get; set; }
        public dynamic A2_RIL_GAS_RECEIPT_ACTL_LCV { get; set; }
        public dynamic A2_RLNG_SCH_ENG_GCV { get; set; }
        public dynamic A2_RLNG_GAS_ENERGY_ACTL_GCV { get; set; }
        public dynamic A2_IOC_RLNG_ALLOCATION { get; set; }
        public dynamic A2_RLNG_IOC_RECEIPT { get; set; }
        public dynamic A2_IOC_RLNG_RECEIPT { get; set; }
        public dynamic A2_SG_IOCL_SCH_ENG_GCV { get; set; }
        public dynamic A2_SG_IOCL_ENERGY_ACTL_GCV { get; set; }
        public dynamic A2_IOC_RLNG_LCV { get; set; }
        public dynamic A2_SPOTGAS_IOCL_ALLOC { get; set; }
        public dynamic A2_SPOTGAS_IOCL_RECEIPT { get; set; }
        public dynamic A2_IOC_RLNG_GCV { get; set; }
        public dynamic A2_SG_GAIL_SCH_ENG_GCV { get; set; }
        public dynamic A2_SG_GAIL_ENERGY_ACTL_GCV { get; set; }
        public dynamic A2_MOL_WT_NG { get; set; }
        public dynamic A2_SPOTGAS_GAIL_ALLOC { get; set; }
        public dynamic A2_SPOTGAS_GAIL_RECEIPT { get; set; }
        public dynamic A2_NG_CARBON_NO { get; set; }
        public dynamic A2_GAIL_LT_RLNG_RE_SCH_ENG_GCV { get; set; }
        public dynamic A2_GAIL_LT_RLNG_RE_ENG_ACT_GCV { get; set; }
        public string A2_NG_LIMITATION_FLG { get; set; }
        public dynamic A2_GAIL_LT_RLNG_RE_ALLOC { get; set; }
        public dynamic A2_GAIL_LT_RLNG_RE_RECEIPT { get; set; }
        // repeated field // public string A2_GAIL_METER_ONLINE { get; set; }
        public dynamic A2_SG_GSPC_SCH_ENG_GCV { get; set; }
        public dynamic A2_SPOTGAS_GSPC_ALLOC { get; set; }
        public dynamic A2_SPOTGAS_GSPC_RECEIPT { get; set; }
        public dynamic A2_SG_GSPC_ENERGY_ACTL_GCV { get; set; }
        public dynamic A_SPOTGAS_GSPC_ALLOC { get; set; }
        public dynamic A_SPOTGAS_GSPC_RECEIPT { get; set; }
        public dynamic A2_NG_IMPORTF_UNIT1 { get; set; }
        public dynamic A2_SG_OTH_SCH_ENG_GCV { get; set; }
        public dynamic A2_SG_OTH_ENERGY_ACTL_GCV { get; set; }
        public dynamic A2_NG_FEED_BYBAL_TO_AMM2 { get; set; }
        public dynamic A2_SPOTGAS_OTH_ALLOC { get; set; }
        public dynamic A2_SPOTGAS_OTH_RECEIPT { get; set; }
        public dynamic A2_RLNG_EXPORTT_SSP { get; set; }
        public dynamic A2_GAIL_RLNG5_SCH_ENG_GCV { get; set; }
        public dynamic A2_GAIL_RLNG5_ENG_ACTL_GCV { get; set; }
        public dynamic A2_SPOT_EXPORTT_SSP { get; set; }
        public dynamic A2_GAIL_RLNG5_SCH_GAS { get; set; }
        public dynamic A2_GAIL_RLNG5_RECEIPT_ACTL_GCV { get; set; }
        public dynamic A2_GAIL_RLNG19_SCH_ENG_GCV { get; set; }
        public dynamic A2_GAIL_RLNG19_ENG_ACTL_GCV { get; set; }
        public dynamic A2_GAIL_RLNG19_SCH_GAS { get; set; }
        public dynamic A2_GAIL_RLNG19_RECEIPT_ACTL_GCV { get; set; }
        public dynamic a_ng_importf_unit1 { get; set; }
        public dynamic A2_DATE_MOD { get; set; }
        public dynamic A2_USER_ID { get; set; }
        public dynamic USER_NAME { get; set; }

        // --------GAS ALLOC PRIORITY-------------------
        public string A2_RIL_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_RLNG_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_SG_IOCL_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_SG_GAIL_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_GAIL_LT_RLNG_RE_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_SG_GSPC_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_SG_OTH_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_GAIL_RLNG5_SCH_ENG_GCV_PRIORITY { get; set; }
        public string A2_GAIL_RLNG19_SCH_ENG_GCV_PRIORITY { get; set; }

        public string PRIORITY_TAG1 { get; set; }
        public string PRIORITY_TAG2 { get; set; }
        public string PRIORITY_TAG3 { get; set; }
        public string PRIORITY_TAG4 { get; set; }
        public string PRIORITY_TAG5 { get; set; }
        public string PRIORITY_TAG6 { get; set; }
        public string PRIORITY_TAG7 { get; set; }
        public string PRIORITY_TAG8 { get; set; }
        public string PRIORITY_TAG9 { get; set; }

        // PRV
        public dynamic PRV_A2_TRANS_DATE { get; set; }
        public dynamic PRV_A2_NG_TOT_AMM2_INT { get; set; }
        public dynamic PRV_A2_NG_TOT_AMM2_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_TOT_CONSP_AMM2 { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_AB_INT { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_AB_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_AB_INT { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_AB_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_AB_INT { get; set; }
        public dynamic PRV_A2_NG_FUEL_AB_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_CONSP_AB { get; set; }
        public dynamic PRV_A2_NG_FEED_AMM2_INT { get; set; }
        public dynamic PRV_A2_NG_FEED_AMM2_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_CONSP_FEED_AMM2 { get; set; }
        public dynamic PRV_A2_PRS_TOT_NG_FUEL_INT { get; set; }
        public dynamic PRV_A2_PRS_TOT_NG_FUEL_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_TOT_NG_FUEL_INT { get; set; }
        public dynamic PRV_A2_TEMP_TOT_NG_FUEL_INT_DIFF { get; set; }
        public dynamic PRV_A2_TOT_NG_FUEL_INT { get; set; }
        public dynamic PRV_A2_TOT_NG_FUEL_INT_DIFF { get; set; }
        public dynamic PRV_A2_TOT_CONSP_NG_FUEL { get; set; }
        public dynamic PRV_A2_PRS_NG_SH_BURN_INT { get; set; }
        public dynamic PRV_A2_PRS_NG_SH_BURN_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_NG_SH_BURN_INT { get; set; }
        public dynamic PRV_A2_TEMP_NG_SH_BURN_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_SH_BURN_INT { get; set; }
        public dynamic PRV_A2_NG_FUEL_SH_BURN_INT_DIFF { get; set; }
        public dynamic PRV_A2_BAL_NG_FUEL_SH_BURNER { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_TBURNER_INT { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_TBURNER_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_TBURNER_INT { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_TBURNER_INT_DIF { get; set; }
        public dynamic PRV_A2_NG_FUEL_TBURNER_INT { get; set; }
        public dynamic PRV_A2_NG_FUEL_TBURNER_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_TBURNER { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_BA101_INT { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_BA101_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_BA101_INT { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_BA101_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_BA101_INT { get; set; }
        public dynamic PRV_A2_NG_FUEL_BA101_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_BA101_INT_DIF { get; set; }
        public dynamic PRV_A2_NG_FUEL_BA101 { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_BA102_INT { get; set; }
        public dynamic PRV_A2_PRS_NG_FUEL_BA102_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_BA102_INT { get; set; }
        public dynamic PRV_A2_TEMP_NG_FUEL_BA102_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_BA102_INT { get; set; }
        public dynamic PRV_A2_NG_FUEL_BA102_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_BA102 { get; set; }
        public dynamic PRV_A2_NG_FUEL_ABURNER { get; set; }
        public dynamic PRV_A2_PRS_FUEL_FLARE_INT { get; set; }
        public dynamic PRV_A2_PRS_FUEL_FLARE_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_FUEL_FLARE_INT { get; set; }
        public dynamic PRV_A2_TEMP_FUEL_FLARE_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_FLARE_INT { get; set; }
        public dynamic PRV_A2_NG_FUEL_FLARE_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_FUEL_FLARE { get; set; }
        public dynamic PRV_A2_NG_EXPORTT_GP1_INT { get; set; }
        public dynamic PRV_A2_NG_EXPORTT_GP1_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_EXPORTT_UNIT1_SSP { get; set; }
        public dynamic PRV_A2_NG_SYNTH_GAS_INT { get; set; }
        public dynamic PRV_A2_NG_SYNTH_GAS_INT_DIFF { get; set; }
        public dynamic PRV_A2_SYNTH_GAS_EXPTT_GP1_INT { get; set; }
        public dynamic PRV_A2_SYNTH_GAS_EXPTT_GP1_INT_DIFF { get; set; }
        public dynamic PRV_A2_NG_EXPORTT_UNIT1 { get; set; }
        public dynamic PRV_A2_NG_EXPORTT_SSP { get; set; }
        public dynamic PRV_A2_RIL_SCH_ENG_GCV { get; set; }
        public string PRV_A2_GAIL_METER_ONLINE { get; set; }
        // repeated field // public dynamic PRV_A2_RIL_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_RIL_SCH_GAS { get; set; }
        public dynamic PRV_A2_RLNG_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_IOC_RLNG_ALLOCATION { get; set; }
        public dynamic PRV_A2_RLNG_IOC_RECEIPT { get; set; }
        public dynamic PRV_A2_IOC_RLNG_RECEIPT { get; set; }
        public dynamic PRV_A2_SG_IOCL_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_IOC_RLNG_LCV { get; set; }
        public dynamic PRV_A2_SPOTGAS_IOCL_RECEIPT { get; set; }
        public dynamic PRV_A2_IOC_RLNG_GCV { get; set; }
        public dynamic PRV_A2_SG_GAIL_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_MOL_WT_NG { get; set; }
        public dynamic PRV_A2_SPOTGAS_GAIL_RECEIPT { get; set; }
        public dynamic PRV_A2_NG_CARBON_NO { get; set; }
        public dynamic PRV_A2_GAIL_LT_RLNG_RE_SCH_ENG_GCV { get; set; }
        public string PRV_A2_NG_LIMITATION_FLG { get; set; }
        public dynamic PRV_A2_GAIL_LT_RLNG_RE_RECEIPT { get; set; }
        // repeated field // public string PRV_A2_GAIL_METER_ONLINE { get; set; }
        public dynamic PRV_A2_SG_GSPC_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_SG_OTH_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_SPOTGAS_OTH_RECEIPT { get; set; }
        public dynamic PRV_A2_GAIL_RLNG5_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_GAIL_RLNG5_RECEIPT_ACTL_GCV { get; set; }
        public dynamic PRV_A2_GAIL_RLNG19_SCH_ENG_GCV { get; set; }
        public dynamic PRV_A2_GAIL_RLNG19_RECEIPT_ACTL_GCV { get; set; }

        // DV
        public dynamic G_CF_NM3_SM3 { get; set; }
        public dynamic G_K_NG_FEED_REFMR { get; set; }
        public dynamic G_KE { get; set; }
        public dynamic G_MF_NG_FLOW_TO_AMM2 { get; set; }
        public dynamic G_MF_NG_FUEL_TO_AB { get; set; }
        public dynamic G_MF_NG_TOTAL_FUEL { get; set; }
        public dynamic G_DSGND_PRESSURE_CONST_NG { get; set; }
        public dynamic G_DSGND_TEMP_CONST_NG { get; set; }
        public dynamic G_MF_NG_FUEL_TO_SUPER_HEATER { get; set; }
        public dynamic G_MF_NG_FUEL_TO_TUNNEL_BURNER { get; set; }
        public dynamic G_MF_NG_FUEL_TO_BA101 { get; set; }
        public dynamic G_MF_NG_FUEL_TO_BA102 { get; set; }
        public dynamic G_MF_NG_FLARE { get; set; }
        public dynamic G_MW_NG_DSGN { get; set; }
        public dynamic G_MF_NG_FEED_TO_AMM2 { get; set; }
    }
}
