namespace itsppisapi.Models
{
    public class PAS202Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string A2_TRANS_DATE { get; set; }
        public dynamic A2_PRS_CO2_INT { get; set; }
        public dynamic A2_TEMP_CO2_INT { get; set; }
        public dynamic A2_CO2_INT { get; set; }
        public dynamic A2_CO2_INT_DIFF { get; set; }
        public dynamic A2_CO2_PROD { get; set; }
        public dynamic A2_PRS_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_TEMP_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_CO2_EXPORTT_GP1_INT_DIFF { get; set; }
        public dynamic A2_CO2_EXPORTT_GP1 { get; set; }
        public dynamic TXT_VAM_POWER { get; set; }
        public dynamic A2_CO2_SUPPLY_UREA2 { get; set; }
        public dynamic A2_IA_PA_EXPORTT_GP1_INT { get; set; }
        public dynamic A2_IA_PA_EXPORTT_GP1_INT_DIFF { get; set; }
        public dynamic A2_PRS_SURPLUS_GAS_INT { get; set; }
        public dynamic A2_PRS_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic A2_TEMP_SURPLUS_GAS_INT { get; set; }
        public dynamic A2_TEMP_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic A2_SURPLUS_GAS_INT { get; set; }
        public dynamic A2_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic A2_SURPLUS_GAS_PROD { get; set; }
        public dynamic A2_PRS_PERMEATE_INT { get; set; }
        public dynamic A2_PRS_PERMEATE_INT_DIFF { get; set; }
        public dynamic A2_TEMP_PERMEATE_INT { get; set; }
        public dynamic A2_TEMP_PERMEATE_INT_DIFF { get; set; }
        public dynamic A2_PERMEATE_INT { get; set; }
        public dynamic A2_PERMEATE_INT_DIFF { get; set; }
        public dynamic A2_PERMEATE_FLOW { get; set; }
        public dynamic A2_PROD_HRS { get; set; }
        public dynamic A2_AB_RUN_HRS { get; set; }
        public dynamic A2_PGRU_RUN_HRS { get; set; }
        public dynamic A2_AMM_SALE { get; set; }
        public dynamic A2_PGRU_PROD { get; set; }
        public dynamic A2_AMM_SUPP_UREA2_INT { get; set; }
        public dynamic A2_AMM_SUPP_UREA2 { get; set; }
        public dynamic A2_AMM_TO_STORAGE_INT { get; set; }
        public dynamic A2_AMM_TO_STORAGE { get; set; }
        public dynamic A2_PRS_VAPOUR_AMM_ACTL { get; set; }
        public dynamic A2_TOT_VPR_TO_AMM2_INT { get; set; }
        public dynamic A2_TOT_VPR_TO_AMM2_INT_DIFF { get; set; }
        public dynamic A2_TOT_VPR_TO_AMM2 { get; set; }
        public dynamic A2_VPR1_TO_AMM2 { get; set; }
        public dynamic A2_VPR2_TO_AMM2 { get; set; }
        public dynamic A2_AMM_PROD { get; set; }
        public dynamic DIS_TOT_AMM_STOCK { get; set; }
        public dynamic A2_RECVFROM_AMM2_STOCK { get; set; }
        public dynamic A2_TFRTO_AMM2_STOCK { get; set; }
        public dynamic A2_RECVFROM_AMM3_STOCK { get; set; }
        public dynamic A2_TFRTO_AMM3_STOCK { get; set; }
        public dynamic A1_RECVFROM_AMM3_STOCK { get; set; }
        public dynamic A1_TFRTO_AMM3_STOCK { get; set; }
        public dynamic DIS_AMM1_LSTOCK { get; set; }
        public dynamic A2_AMM2_LOGICAL_STOCK { get; set; }
        public dynamic A2_AMM3_LOGICAL_STOCK { get; set; }
        public dynamic A2_AMM_CAP_UTIL { get; set; }
        public string A2_NAP_LIMITATION_FLG { get; set; }
        public string A2_REMARKS_D { get; set; }
        public string A2_REMARKS_M { get; set; }
        public dynamic DIS_FEED_GAS { get; set; }
        public dynamic DIS_FUEL_NG { get; set; }
        public dynamic DIS_TOT_GAS { get; set; }
        public dynamic DIS_FEED_NAP { get; set; }
        public dynamic DIS_FUEL_NAP { get; set; }
        public dynamic DIS_TOT_NAP { get; set; }
        public dynamic DIS_PW_AMM { get; set; }
        public dynamic DIS_ATC_EXP { get; set; }
        public dynamic DIS_APC_EXP { get; set; }
        public dynamic DIS_ASC_EXP { get; set; }
        public dynamic DIS_ACTTC_EXP { get; set; }
        public dynamic DIS_TOT_COND_EXP_AMM2 { get; set; }
        public dynamic DIS_PW_IMP_AMM2 { get; set; }
        public dynamic DIS_SH_STEAM_AMM2 { get; set; }
        public dynamic DIS_SM_STEAM_EXP_ACT { get; set; }
        public dynamic DIS_PWR_CONSP_AMM2 { get; set; }
        public dynamic DIS_PWR_AMM2 { get; set; }
        public dynamic DIS_PWR_CONSP_ACT { get; set; }
        public dynamic DIS_COOL_WTR_AMM2 { get; set; }
        public dynamic DIS_SPC_AMMONIA { get; set; }
        public dynamic DIS_SPC_UR_FD_FL_AMM_EQ_NAP { get; set; }
        public dynamic DIS_SPC_FL_STM_EQ_NAP { get; set; }
        public dynamic DIS_SPE_EQ_NAP_PWR_UTIL_GP1 { get; set; }
        public dynamic DIS_SPC_TOT_EQ_NAP_UR { get; set; }
        public dynamic DIS_SPC_CR_STU_STM_EXPTT_GP1 { get; set; }
        public dynamic DIS_CF_SPC_NET_EQ_NAP_UR { get; set; }
        public dynamic DIS_TOT_COOL_WTR { get; set; }
        public dynamic DIS_DMW_AMM2 { get; set; }
        public dynamic DIS_SPC_UR_PWR_DIRECT { get; set; }
        public dynamic DIS_ENG_FEED_GAS { get; set; }
        public dynamic DIS_ENG_FUEL_GAS { get; set; }
        public dynamic DIS_ENG_TOT_GAS { get; set; }
        public dynamic DIS_ENG_FEED_NAP { get; set; }
        public dynamic DIS_ENG_FUEL_NAP { get; set; }
        public dynamic DIS_ENG_TOT_NAP { get; set; }
        public dynamic DIS_ENG_TOT_GAS_NAP { get; set; }
        public dynamic DIS_ENG_SH_STEAM_AMM2 { get; set; }
        public dynamic DIS_ENG_PWR_AMM2 { get; set; }
        public dynamic DIS_ENG_TOT_AMM2 { get; set; }
        public dynamic DIS_ENG_ACT_STEAM { get; set; }
        public dynamic DIS_ENG_ACT_PWR { get; set; }
        public dynamic DIS_ENG_TOT_CT { get; set; }
        public dynamic DIS_ENG_CR_BWF_PHEAT { get; set; }
        public dynamic DIS_ENG_CR_BFW_PWR { get; set; }
        public dynamic DIS_ENG_CR_TOT_SH_EXP { get; set; }
        public dynamic DIS_ENG_NET_ENG { get; set; }
        public dynamic DIS_ENG_USP_FEED_FUEL_AMM2 { get; set; }
        public dynamic DIS_ENG_USP_FUEL_AB { get; set; }
        public dynamic DIS_SPE_ALLOC_EQ_NAP_PWR_UTIL { get; set; }
        public dynamic DIS_ENG_USP_ALL_FF { get; set; }
        public string A2_DATE_MOD { get; set; }
        public dynamic A2_USER_ID { get; set; }
        public string USER_NAME { get; set; }

        // PRV
        public string PRV_A2_TRANS_DATE { get; set; }
        public dynamic PRV_A2_PRS_CO2_INT { get; set; }
        public dynamic PRV_A2_TEMP_CO2_INT { get; set; }
        public dynamic PRV_A2_CO2_INT { get; set; }
        public dynamic PRV_A2_CO2_INT_DIFF { get; set; }
        public dynamic PRV_A2_CO2_PROD { get; set; }
        public dynamic PRV_A2_PRS_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic PRV_A2_TEMP_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic PRV_A2_CO2_EXPORTT_GP1_INT { get; set; }
        public dynamic PRV_A2_CO2_EXPORTT_GP1_INT_DIFF { get; set; }
        public dynamic PRV_A2_CO2_EXPORTT_GP1 { get; set; }
        public dynamic PRV_TXT_VAM_POWER { get; set; }
        public dynamic PRV_A2_CO2_SUPPLY_UREA2 { get; set; }
        public dynamic PRV_A2_IA_PA_EXPORTT_GP1_INT { get; set; }
        public dynamic PRV_A2_IA_PA_EXPORTT_GP1_INT_DIFF { get; set; }
        public dynamic PRV_A2_PRS_SURPLUS_GAS_INT { get; set; }
        public dynamic PRV_A2_PRS_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_SURPLUS_GAS_INT { get; set; }
        public dynamic PRV_A2_TEMP_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic PRV_A2_SURPLUS_GAS_INT { get; set; }
        public dynamic PRV_A2_SURPLUS_GAS_INT_DIFF { get; set; }
        public dynamic PRV_A2_SURPLUS_GAS_PROD { get; set; }
        public dynamic PRV_A2_PRS_PERMEATE_INT { get; set; }
        public dynamic PRV_A2_PRS_PERMEATE_INT_DIFF { get; set; }
        public dynamic PRV_A2_TEMP_PERMEATE_INT { get; set; }
        public dynamic PRV_A2_TEMP_PERMEATE_INT_DIFF { get; set; }
        public dynamic PRV_A2_PERMEATE_INT { get; set; }
        public dynamic PRV_A2_PERMEATE_INT_DIFF { get; set; }
        public dynamic PRV_A2_PERMEATE_FLOW { get; set; }
        public dynamic PRV_A2_PROD_HRS { get; set; }
        public dynamic PRV_A2_AB_RUN_HRS { get; set; }
        public dynamic PRV_A2_PGRU_RUN_HRS { get; set; }
        public dynamic PRV_A2_AMM_SALE { get; set; }
        public dynamic PRV_A2_PGRU_PROD { get; set; }
        public dynamic PRV_A2_AMM_SUPP_UREA2_INT { get; set; }
        public dynamic PRV_A2_AMM_SUPP_UREA2 { get; set; }
        public dynamic PRV_A2_AMM_TO_STORAGE_INT { get; set; }
        public dynamic PRV_A2_AMM_TO_STORAGE { get; set; }
        public dynamic PRV_A2_PRS_VAPOUR_AMM_ACTL { get; set; }
        public dynamic PRV_A2_TOT_VPR_TO_AMM2_INT { get; set; }
        public dynamic PRV_A2_TOT_VPR_TO_AMM2_INT_DIFF { get; set; }
        public dynamic PRV_A2_TOT_VPR_TO_AMM2 { get; set; }
        public dynamic PRV_A2_VPR1_TO_AMM2 { get; set; }
        public dynamic PRV_A2_VPR2_TO_AMM2 { get; set; }
        public dynamic PRV_A2_AMM_PROD { get; set; }
        public dynamic PRV_A2_RECVFROM_AMM2_STOCK { get; set; }
        public dynamic PRV_A2_TFRTO_AMM2_STOCK { get; set; }
        public dynamic PRV_A2_AMM2_LOGICAL_STOCK { get; set; }
        public dynamic PRV_A2_AMM_CAP_UTIL { get; set; }
        public string PRV_A2_NAP_LIMITATION_FLG { get; set; }
        public string PRV_A2_REMARKS { get; set; }

        // DV
        public dynamic parm_dsgnd_temp_co2 { get; set; }
        public dynamic parm_dsgnd_prs_co2 { get; set; }
        public dynamic parm_cf_permeate_flow { get; set; }
        public dynamic parm_amm2_daily_inst_cap { get; set; }
        public dynamic parm_permeate_pmt_amm { get; set; }
        public dynamic parm_CF_NM3_SM3 { get; set; }
        public string parm_proj_sdate { get; set; }
        public dynamic parm_sm_enthalpy { get; set; }
        public dynamic parm_sh_enthalpy { get; set; }
        public dynamic parm_pwr_factor { get; set; }
        public dynamic parm_temp_diff { get; set; }
        public dynamic parm_mul_factor { get; set; }
        public dynamic ln_dsgnd_prs { get; set; }
        public dynamic A3_STK_TRSFER_FROM_GP3_TO_GP2 { get; set; }
        public dynamic A3_STK_TRSFER_FROM_GP2_TO_GP3 { get; set; }
        public dynamic parm_amm2_logical_op_stock { get; set; }
        public dynamic A3_AMM_3_LOGICAL_STK { get; set; }
        public dynamic parm_ng_consp_feed_amm2 { get; set; }
        public dynamic parm_ng_tot_consp_amm2 { get; set; }
        public dynamic parm_ng_consp_ab { get; set; }
        public dynamic parm_ng_net_cv { get; set; }
        public dynamic parm_TOT_CONSP_NG_FUEL { get; set; }
        public dynamic parm_pw_consp_amm2 { get; set; }
        public dynamic parm_atc_prod { get; set; }
        public dynamic parm_apc_prod { get; set; }
        public dynamic parm_pw_consp_ab { get; set; }
        public dynamic parm_pw_consp_rgb { get; set; }
        public dynamic parm_acttc_prod { get; set; }
        public dynamic parm_fw_consp_act { get; set; }
        public dynamic parm_fw_consp_uct { get; set; }
        public dynamic parm_ab_sh_prod { get; set; }
        public dynamic parm_sh_consp_urea2 { get; set; }
        public dynamic parm_sh_exportto_gp1 { get; set; }
        public dynamic parm_sm_consp_acwpumpa { get; set; }
        public dynamic parm_sm_consp_acwpumpb { get; set; }
        public dynamic parm_sm_consp_acwpumpc { get; set; }
        public dynamic parm_sm_consp_ucwpumpa { get; set; }
        public dynamic parm_sm_consp_ucwpumpb { get; set; }
        public dynamic parm_sm_consp_ucwpumpc { get; set; }
        public dynamic parm_sm_consp_fdfan { get; set; }
        public dynamic parm_sm_consp_bfw_pumpa { get; set; }
        public dynamic parm_sm_consp_bfw_pumpb { get; set; }
        public dynamic parm_tot_urea_prod { get; set; }
        public dynamic parm_u_usc_prod { get; set; }
        public dynamic parm_u_tot_amm_consp { get; set; }
        public dynamic parm_bal_nap_consp_pref { get; set; }
        public dynamic parm_plant_consp_gross { get; set; }
        public dynamic parm_plant_consp_net { get; set; }
        public dynamic parm_nap_net_cv { get; set; }
        public dynamic parm_act_consp { get; set; }
        public dynamic parm_sc_importf_unit2 { get; set; }
        public dynamic ln_cr_sm_fdfan_ab { get; set; }
        public dynamic ln_sm_uct { get; set; }
        public dynamic ln_sm_steam_bfw { get; set; }
    }
}
