namespace itsppisapi.Models
{
    public class PAS214Model
    {
        public string MINMONTH { get; set; }
        public decimal MINYEAR { get; set; }
        public string MAXMONTH { get; set; }
        public decimal MAXYEAR { get; set; }
        public string A2_MONTH { get; set; }
        public decimal A2_YEAR { get; set; }
        public string A2_DATE_MOD { get; set; }
        public decimal A2_USER_ID { get; set; }
        public string USER_NAME { get; set; }

        public decimal A2_AMM_BUDG_PROD { get; set; }
        public decimal A2_UREA_BUDG_PROD { get; set; }
        public decimal A2_AMM_ACTL_PROD { get; set; }
        public decimal A2_UREA_ACTL_PROD { get; set; }
        public decimal A2_AMM_VOL_VAR { get; set; }
        public decimal A2_UREA_VOL_VAR { get; set; }
        public decimal A2_AMM_BUDG_STREAM_DAYS { get; set; }
        public decimal A2_UREA_BUDG_STREAM_DAYS { get; set; }
        public decimal A2_AMM_ACTL_STREAM_DAYS { get; set; }
        public decimal A2_UREA_ACTL_STREAM_DAYS { get; set; }
        public decimal A2_AMM_STREAM_DAYS_LOST { get; set; }
        public decimal A2_UREA_STREAM_DAYS_LOST { get; set; }
        public decimal A2_AMM_PROD_LOST { get; set; }
        public decimal A2_UREA_PROD_LOST { get; set; }
        public decimal A2_AMM_PROD_LOST_NAP_LIMIT { get; set; }
        public decimal A2_UREA_PROD_LOST_NAP_LIMIT { get; set; }
        public decimal A2_AMM_TOT_ACC_PROD_LOST { get; set; }
        public decimal A2_UREA_TOT_ACC_PROD_LOST { get; set; }
        public decimal A2_AMM_BUDG_SP_NAP_2 { get; set; }
        public decimal A2_AMM_ACTL_SP_NAP_2 { get; set; }
        public decimal A2_AMM_CONSP_VAR_2 { get; set; }
        public decimal A2_AMM_ADD_FLARING { get; set; }
        public decimal A2_AMM_OTHERS { get; set; }
        public decimal A2_AMM_NET_CONSP_VAR_2 { get; set; }
        public decimal A2_AMM_NAP_LIMIT { get; set; }
        public decimal A2_AMM_USAGE_CONSP_VAR { get; set; }
        public decimal A2_AB_BUDG_SP_NAP { get; set; }
        public decimal A2_AB_ACTL_SP_NAP { get; set; }
        public decimal A2_AB_CONSP_VAR { get; set; }
        public decimal A2_AB_AMM_ADD_STM_DEMAND { get; set; }
        public decimal A2_AB_UR_ADD_STM_DEMAND { get; set; }
        public decimal A2_AB_NET_CONSP_VAR_2 { get; set; }
        public decimal A2_AB_OTHERS { get; set; }
        public decimal A2_AB_USAGE_CONSP_VAR { get; set; }
        public decimal A2_PWR_BUDG_SP_NAP { get; set; }
        public decimal A2_PWR_ACTL_SP_NAP { get; set; }
        public decimal A2_PWR_CONSP_VAR { get; set; }
        public decimal A2_PWR_ADD_DIRECT { get; set; }
        public decimal A2_PWR_ADD_ALLOC_UTIL { get; set; }
        public decimal A2_PWR_NET_CONSP_VAR_2 { get; set; }
        public decimal A2_PWR_USAGE_CONSP_VAR_SPG { get; set; }
        public decimal A2_UREA_BUDG_OVERALL { get; set; }
        public decimal A2_UREA_ACTL_OVERALL { get; set; }
        public decimal A2_UREA_NET_VAR { get; set; }
        public decimal A2_AMM_FEED_FUEL { get; set; }
        public decimal A2_AB_FUEL { get; set; }
        public decimal A2_TOT_ACCT_VAR { get; set; }
        public decimal A2_PWR_DEMAND_VAR { get; set; }
        public decimal A2_TOT_USAGE_VAR { get; set; }
        public decimal A2_AMM_BUDG_UNPROD_NAP_3 { get; set; }
        public decimal A2_AMM_ACTL_UNPROD_NAP_3 { get; set; }
        public decimal A2_AMM_ADD_UNPROD_NAP_3 { get; set; }
        public decimal A2_AB_ACTL_STM_3 { get; set; }
        public decimal A2_AB_BUDG_STM_3 { get; set; }
        public decimal A2_AB_ADD_STM_3 { get; set; }
        public decimal A2_AB_ACTL_STM_AMM_3 { get; set; }
        public decimal A2_AB_BUDG_STM_AMM_3 { get; set; }
        public decimal A2_AB_ADD_STM_AMM_3 { get; set; }
        public decimal A2_AB_ACTL_STM_UR_3 { get; set; }
        public decimal A2_AB_BUDG_STM_UR_3 { get; set; }
        public decimal A2_AB_ADD_STM_UR_3 { get; set; }
        public decimal A2_AB_ACTL_STM_SD_3 { get; set; }
        public decimal A2_AB_BUDG_STM_SD_3 { get; set; }
        public decimal A2_AB_ADD_STM_SD_3 { get; set; }
        public decimal A2_PWR_BUDG_DIRECT_4 { get; set; }
        public decimal A2_PWR_ACTL_DIRECT_4 { get; set; }
        public decimal A2_PWR_BUDG_UTIL_4 { get; set; }
        public decimal A2_PWR_ACTL_UTIL_4 { get; set; }
        public decimal A2_PWR_BUDG_ALLOC_4 { get; set; }
        public decimal A2_PWR_ACTL_ALLOC_4 { get; set; }
        public decimal A2_PWR_BUDG_ALLOC_SP_MW_4 { get; set; }
        public decimal A2_PWR_ACTL_ALLOC_SP_MW_4 { get; set; }
        public decimal TXT_AMM_BUDG_SP_NAP_2 { get; set; }
        public decimal TXT_AMM_ACTL_SP_NAP_2 { get; set; }
        public decimal TXT_AMM_CONSP_VAR_2 { get; set; }
        public decimal TXT_AMM_ADD_FLARING { get; set; }
        public decimal TXT_AMM_OTHERS { get; set; }
        public decimal TXT_AMM_NET_CONSP_VAR_2 { get; set; }
        public decimal TXT_AMM_NAP_LIMIT { get; set; }
        public decimal TXT_AMM_USAGE_CONSP_VAR { get; set; }
        public decimal TXT_AB_BUDG_SP_NAP { get; set; }
        public decimal TXT_AB_ACTL_SP_NAP { get; set; }
        public decimal TXT_AB_CONSP_VAR { get; set; }
        public decimal TXT_AB_AMM_ADD_STM_DEMAND { get; set; }
        public decimal TXT_AB_UR_ADD_STM_DEMAND { get; set; }
        public decimal TXT_AB_NET_CONSP_VAR_2 { get; set; }
        public decimal TXT_AB_OTHERS { get; set; }
        public decimal TXT_AB_USAGE_CONSP_VAR { get; set; }
        public decimal TXT_PWR_BUDG_SP_NAP { get; set; }
        public decimal TXT_PWR_ACTL_SP_NAP { get; set; }
        public decimal TXT_PWR_CONSP_VAR { get; set; }
        public decimal TXT_PWR_ADD_DIRECT { get; set; }
        public decimal TXT_PWR_ADD_ALLOC_UTIL { get; set; }
        public decimal TXT_PWR_NET_CONSP_VAR_2 { get; set; }
        public decimal TXT_PWR_USAGE_CONSP_VAR_SPG { get; set; }
        public decimal TXT_UREA_BUDG_OVERALL { get; set; }
        public decimal TXT_UREA_ACTL_OVERALL { get; set; }
        public decimal TXT_UREA_NET_VAR { get; set; }
        public decimal TXT_AMM_FEED_FUEL { get; set; }
        public decimal TXT_AB_FUEL { get; set; }
        public decimal TXT_TOT_ACCT_VAR { get; set; }
        public decimal TXT_PWR_DEMAND_VAR { get; set; }
        public decimal TXT_TOT_USAGE_VAR { get; set; }
    }
}