namespace itsppisapi.Models
{
    public class PAS205Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string A2_TRANS_DATE { get; set; }
        public string A2_NAP_TFR_TANK { get; set; }
        public decimal A2_TOT_NAP_BULK_STOCK { get; set; }
        public decimal A2_BAL_NAP_TFRT_DAYTANK { get; set; }
        public decimal A2_NAP_TFRT_DAYTANK_INT { get; set; }
        public decimal A2_NAP_TFRT_DAYTANK_INT_DIFF { get; set; }
        public decimal A2_NAP_TFRT_DAYTANK { get; set; }
        public decimal A2_NAP_TFRT_DAYTANK_MT_INT { get; set; }
        public decimal A2_NAP_TFRT_DAYTANK_MT_INT_DIFF { get; set; }
        public decimal A2_NAP_TFRT_DAYTANK_MT { get; set; }
        public decimal A2_SNAP_TFRT_RNDT { get; set; }
        public decimal A2_NAP_OPR_TEMP { get; set; }
        public decimal A2_DAYTANK_LEVEL { get; set; }
        public decimal A2_DAYTANK_STOCK { get; set; }
        public decimal TXT_DENSITY { get; set; }
        public decimal TXT_TANK2_STOCK { get; set; }
        public decimal TXT_TANK3_STOCK { get; set; }
        public decimal TXT_TANK1_STOCK { get; set; }
        public decimal TXT_NAP_RCPT_GP1 { get; set; }
        public decimal TXT_NAP_TFR_GP1 { get; set; }
        public decimal TXT_RCPT_IOC { get; set; }
        public decimal TXT_TOT_NAP_STOCK { get; set; }
        public decimal TXT_DENSITY_CONSP { get; set; }
        public decimal TXT_SNDT_DENSITY { get; set; }
        public decimal TXT_SNT_LEVEL { get; set; }
        public decimal TXT_SNT_DENSITY { get; set; }
        public decimal TXT_SNT_STOCK { get; set; }
        public decimal TXT_HDS_LOSS { get; set; }
        public decimal TXT_SN_PROD { get; set; }
        public decimal PARM_OU_SNT_OP_STK { get; set; }
        public decimal PARM_SNDT_OP_STK { get; set; }
        public decimal A2_TOT_NAP_CONSP_GP2 { get; set; }
        public decimal A2_NAP_HYD_FURN_INT { get; set; }
        public decimal A2_NAP_HYD_FURN_INT_DIFF { get; set; }
        public decimal A2_NAP_CONSP_HYD_FURN { get; set; }
        public decimal A2_NAP_DESUL_FURN_INT { get; set; }
        public decimal A2_NAP_DESUL_FURN_INT_DIFF { get; set; }
        public decimal A2_NAP_CONSP_DESUL_FURN { get; set; }
        public decimal A2_NAP_TUNNEL_BURNER_INT { get; set; }
        public decimal A2_NAP_TUNNEL_BURNER_INT_DIFF { get; set; }
        public decimal A2_NAP_CONSP_TUNNEL_BURNER { get; set; }
        public decimal A2_NAP_ARCH_BURNER_INT { get; set; }
        public decimal A2_NAP_ARCH_BURNER_INT_DIFF { get; set; }
        public decimal A2_NAP_CONSP_ARCH_BURNER { get; set; }
        public decimal A2_NAP_SHEATER_BURNER_INT { get; set; }
        public decimal A2_NAP_SHEATER_BURNER_INT_DIFF { get; set; }
        public decimal A2_NAP_CONSP_SHEATER_BURNER { get; set; }
        public decimal A2_TOT_FUELNAP_TO_AMM2 { get; set; }
        public decimal A2_NAP_AB_INT { get; set; }
        public decimal A2_NAP_AB_INT_DIFF { get; set; }
        public decimal A2_NAP_CONSP_AB { get; set; }
        public decimal A2_NAP_HDS_INT { get; set; }
        public decimal A2_NAP_HDS_INT_DIFF { get; set; }
        public decimal A2_NAP_CONSP_HDS { get; set; }
        public decimal A2_BAL_NAP_CONSP_HDS { get; set; }
        public decimal A2_SNDT_LEVEL { get; set; }
        public decimal A2_SNDT_STOCK { get; set; }
        public decimal A2_SNAP_PROD_INT { get; set; }
        public decimal A2_SNAP_PROD_INT_DIFF { get; set; }
        public decimal A2_SNAP_PROD { get; set; }
        public decimal A2_SNAP_PREF_INT { get; set; }
        public decimal A2_SNAP_PREF_INT_DIFF { get; set; }
        public decimal A2_SNAP_CONSP_PREF { get; set; }
        public decimal A2_BAL_SNAP_CONSP_PREF { get; set; }
        public string A2_REMARKS { get; set; }
        public string A2_DATE_MOD { get; set; }
        public decimal A2_USER_ID { get; set; }
        public string USER_NAME { get; set; }

        // PRV
        public string PRV_A2_TRANS_DATE { get; set; }
        public string PRV_A2_NAP_TFR_TANK { get; set; }
        public decimal PRV_A2_TOT_NAP_BULK_STOCK { get; set; }
        public decimal PRV_A2_BAL_NAP_TFRT_DAYTANK { get; set; }
        public decimal PRV_A2_NAP_TFRT_DAYTANK_INT { get; set; }
        public decimal PRV_A2_NAP_TFRT_DAYTANK_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_TFRT_DAYTANK { get; set; }
        public decimal PRV_A2_NAP_TFRT_DAYTANK_MT_INT { get; set; }
        public decimal PRV_A2_NAP_TFRT_DAYTANK_MT_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_TFRT_DAYTANK_MT { get; set; }
        public decimal PRV_A2_SNAP_TFRT_RNDT { get; set; }
        public decimal PRV_A2_NAP_OPR_TEMP { get; set; }
        public decimal PRV_A2_DAYTANK_LEVEL { get; set; }
        public decimal PRV_A2_DAYTANK_STOCK { get; set; }
        public decimal PRV_A2_TOT_NAP_CONSP_GP2 { get; set; }
        public decimal PRV_A2_NAP_HYD_FURN_INT { get; set; }
        public decimal PRV_A2_NAP_HYD_FURN_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_CONSP_HYD_FURN { get; set; }
        public decimal PRV_A2_NAP_DESUL_FURN_INT { get; set; }
        public decimal PRV_A2_NAP_DESUL_FURN_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_CONSP_DESUL_FURN { get; set; }
        public decimal PRV_A2_NAP_TUNNEL_BURNER_INT { get; set; }
        public decimal PRV_A2_NAP_TUNNEL_BURNER_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_CONSP_TUNNEL_BURNER { get; set; }
        public decimal PRV_A2_NAP_ARCH_BURNER_INT { get; set; }
        public decimal PRV_A2_NAP_ARCH_BURNER_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_CONSP_ARCH_BURNER { get; set; }
        public decimal PRV_A2_NAP_SHEATER_BURNER_INT { get; set; }
        public decimal PRV_A2_NAP_SHEATER_BURNER_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_CONSP_SHEATER_BURNER { get; set; }
        public decimal PRV_A2_TOT_FUELNAP_TO_AMM2 { get; set; }
        public decimal PRV_A2_NAP_AB_INT { get; set; }
        public decimal PRV_A2_NAP_AB_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_CONSP_AB { get; set; }
        public decimal PRV_A2_NAP_HDS_INT { get; set; }
        public decimal PRV_A2_NAP_HDS_INT_DIFF { get; set; }
        public decimal PRV_A2_NAP_CONSP_HDS { get; set; }
        public decimal PRV_A2_BAL_NAP_CONSP_HDS { get; set; }
        public decimal PRV_A2_SNDT_LEVEL { get; set; }
        public decimal PRV_A2_SNDT_STOCK { get; set; }
        public decimal PRV_A2_SNAP_PROD_INT { get; set; }
        public decimal PRV_A2_SNAP_PROD_INT_DIFF { get; set; }
        public decimal PRV_A2_SNAP_PROD { get; set; }
        public decimal PRV_A2_SNAP_PREF_INT { get; set; }
        public decimal PRV_A2_SNAP_PREF_INT_DIFF { get; set; }
        public decimal PRV_A2_SNAP_CONSP_PREF { get; set; }
        public decimal PRV_A2_BAL_SNAP_CONSP_PREF { get; set; }
        public string PRV_A2_REMARKS { get; set; }
        public decimal PRV_TXT_SN_PROD { get; set; }

        // DV
        public string ou1_nap_tfr_tank1_gpii { get; set; }
        public decimal ou1_tot_gp2_nap_stk { get; set; }
        public decimal ou1_nap_tfrt_daytank_gpii { get; set; }
        public decimal a2_nap_density { get; set; }
        public decimal G_NAP_DSGND_DENSITY { get; set; }
        public decimal G_NAP_SNDT_CALIB { get; set; }

        public decimal PARM_OP_DT_STOCK { get; set; }
    }
}
