namespace itsppisapi.Models
{
    public class PSS001Model
    {
        public string MINDT { get; set; }
        public string MAXDT { get; set; }
        public string S_TRANS_DATE { get; set; }
        public string S_DMY_FLG { get; set; }
        public dynamic S_USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string S_DATE_MOD { get; set; }
        public dynamic S_FIN_YR { get; set; }
        public string S_YYYYMM { get; set; }
        public dynamic S_SULP_OP_BALANCE { get; set; }
        public dynamic S_SULP_RECEIPT { get; set; }
        public dynamic S_SULP_CONSP_INIT_READ { get; set; }
        public dynamic S_SULP_CONSP_FINAL_READ { get; set; }
        public dynamic S_SULP_CONSP_FINAL { get; set; }
        public dynamic S_SULP_CLG_BAL { get; set; }
        public dynamic S_ROCK_PHOS_PUR_INV_RSMM { get; set; }
        public dynamic S_ROCK_PHOS_OP_BAL_RSMM { get; set; }
        public dynamic S_ROCK_PHOS_RECEIPT_RSMM { get; set; }
        public dynamic S_ROCK_PHOS_CONSP_RSMM { get; set; }
        public dynamic S_ROCK_PHOS_CLG_BAL_RSMM { get; set; }
        public dynamic S_ROCK_PHOS_P2O5_PER_RSMM { get; set; }
        public dynamic S_ROCK_PHOS_PUR_INV_JORD { get; set; }
        public dynamic S_ROCK_PHOS_OP_BAL_JORD { get; set; }
        public dynamic S_ROCK_PHOS_RECEIPT_JORD { get; set; }
        public dynamic S_ROCK_PHOS_CONSP_JORD { get; set; }
        public dynamic S_ROCK_PHOS_CLG_BAL_JORD { get; set; }
        public dynamic S_ROCK_PHOS_P2O5_PER_JORD { get; set; }
        public dynamic S_ROCK_PHOS_PUR_INV_EGYP { get; set; }
        public dynamic S_ROCK_PHOS_OP_BAL_EGYP { get; set; }
        public dynamic S_ROCK_PHOS_RECEIPT_EGYP { get; set; }
        public dynamic S_ROCK_PHOS_CONSP_EGYP { get; set; }
        public dynamic S_ROCK_PHOS_CLG_BAL_EGYP { get; set; }
        public dynamic S_ROCK_PHOS_P2O5_PER_EGYP { get; set; }
        public dynamic S_ROCK_PHOS_PUR_INV_MORO { get; set; }
        public dynamic S_ROCK_PHOS_OP_BAL_MORO { get; set; }
        public dynamic S_ROCK_PHOS_RECEIPT_MORO { get; set; }
        public dynamic S_ROCK_PHOS_CONSP_MORO { get; set; }
        public dynamic S_ROCK_PHOS_CLG_BAL_MORO { get; set; }
        public dynamic S_ROCK_PHOS_P2O5_PER_MORO { get; set; }
        public dynamic S_ROCK_PHOS_PUR_INV_NAUR { get; set; }
        public dynamic S_ROCK_PHOS_OP_BAL_NAUR { get; set; }
        public dynamic S_ROCK_PHOS_RECEIPT_NAUR { get; set; }
        public dynamic S_ROCK_PHOS_CONSP_NAUR { get; set; }
        public dynamic S_ROCK_PHOS_CLG_BAL_NAUR { get; set; }
        public dynamic S_ROCK_PHOS_P2O5_PER_NAUR { get; set; }
        public dynamic S_FILLER_OP_BALANCE { get; set; }
        public dynamic S_FILLER_RECEIPT { get; set; }
        public dynamic S_FILLER_CONSP_PSSP { get; set; }
        public dynamic S_FILLER_CONSP_GSSP { get; set; }
        public dynamic S_FILLER_CLG_BAL { get; set; }
        public dynamic S_OP_BAL_LOOSE_SSP { get; set; }
        public dynamic S_PRODUCTION_LOOSE_SSP { get; set; }
        public dynamic S_CONSP_PSSP_LOOSE_SSP { get; set; }
        public dynamic S_CONSP_GSSP_LOOSE_SSP { get; set; }
        public dynamic S_CLG_BAL_LOOSE_SSP { get; set; }
        public dynamic S_STREAM_HOUR_LOOSE_SSP { get; set; }
        public dynamic S_OP_BAL_POWDER_SSP { get; set; }
        public dynamic S_PRODUCTION_POWDER_SSP { get; set; }
        public dynamic S_DISP_PSSP_RAIL_POWDER_SSP { get; set; }
        public dynamic S_DISP_PSSP_ROAD_POWDER_SSP { get; set; }
        public dynamic S_DISP_PSSP_TOT_POWDER_SSP { get; set; }
        public dynamic S_CLG_BAL_POWDER_SSP { get; set; }
        public dynamic S_STREAM_HOUR_POWDER_SSP { get; set; }
        public dynamic S_OP_BAL_GRANU_SSP { get; set; }
        public dynamic S_PRODUCTION_GRANU_SSP_A { get; set; }
        public dynamic S_PRODUCTION_GRANU_SSP_B { get; set; }
        public dynamic S_DISP_GSSP_RAIL_GRANU_SSP { get; set; }
        public dynamic S_DISP_GSSP_ROAD_GRANU_SSP { get; set; }
        public dynamic S_DISP_GSSP_TOT_GRANU_SSP { get; set; }
        public dynamic S_CLG_BAL_GRANU_SSP { get; set; }
        public dynamic S_STREAM_HOUR_GRANU_SSP_A { get; set; }
        public dynamic S_STREAM_HOUR_GRANU_SSP_B { get; set; }
        public dynamic S_POWER_LOOSE_SSP_INIT_READ { get; set; }
        public dynamic S_POWER_LOOSE_SSP_FINAL_READ { get; set; }
        public dynamic S_POWER_LOOSE_SSP_DIFF_READ { get; set; }
        public dynamic S_POWER_GSSP_INIT_READ { get; set; }
        public dynamic S_POWER_GSSP_FINAL_READ { get; set; }
        public dynamic S_POWER_GSSP_DIFF_READ { get; set; }
        public dynamic S_POWER_OWN_LSE_SSP_INIT_READ { get; set; }
        public dynamic S_POWER_OWN_LSE_SSP_FINAL_READ { get; set; }
        public dynamic S_POWER_OWN_LSE_SSP_DIFF_READ { get; set; }
        public dynamic S_POWER_OWN_GSSP_INIT_READ { get; set; }
        public dynamic S_POWER_OWN_GSSP_FINAL_READ { get; set; }
        public dynamic S_POWER_OWN_GPSSP_DIFF_READ { get; set; }
        public dynamic S_NG_CONSP_READ_INIT { get; set; }
        public dynamic S_NG_CONSP_READ_FINAL { get; set; }
        public dynamic S_NG_CONSP_READ_DIFF { get; set; }
        public dynamic S_NG_CONSP_LSSP { get; set; }
        public dynamic S_NG_CONSP_GSSP { get; set; }
        public dynamic S_WATER_CONSP_READ_INIT { get; set; }
        public dynamic S_WATER_CONSP_READ_FINAL { get; set; }
        public dynamic S_WATER_CONSP_READ_DIFF { get; set; }
        public dynamic S_BAG_OP_BAL_PSSP { get; set; }
        public dynamic S_BAG_RECEIPT_PSSP { get; set; }
        public dynamic S_BAG_CONSP_PSSP { get; set; }
        public dynamic S_BAG_CLG_PSSP { get; set; }
        public dynamic S_BAG_OP_BAL_GSSP { get; set; }
        public dynamic S_BAG_RECEIPT_GSSP { get; set; }
        public dynamic S_BAG_CONSP_GSSP { get; set; }
        public dynamic S_BAG_CLG_GSSP { get; set; }
        public string S_REMARKS_M { get; set; }
        public string S_REMARKS_D { get; set; }
        public dynamic S_EMPTY_BAG_DAMAGED_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_RAPTURE_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_DAMAGED_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_RAPTURE_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_RECD_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_RECD_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_TESTING_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_TESTING_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_MARKT_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_MARKT_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_STND_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_STND_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_STOCK_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_STOCK_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_STOCK_ADJ_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_STOCK_ADJ_GSSP { get; set; }
        public dynamic S_EMPTY_BAG_SOUND_PSSP { get; set; }
        public dynamic S_EMPTY_BAG_SOUND_GSSP { get; set; }
        public dynamic S_DIRECT_LOAD_ROAD_PSSP { get; set; }
        public dynamic S_DIRECT_LOAD_ROAD_GSSP { get; set; }
        public dynamic S_STACK_LOAD_ROAD_PSSP { get; set; }
        public dynamic S_STACK_LOAD_ROAD_GSSP { get; set; }
        public dynamic S_PSSP_MAT_SHT_TO_SSP { get; set; }
        public dynamic S_GSSP_MAT_SHT_TO_SSP { get; set; }
        public dynamic S_RET_FRM_BAGG_TO_PSSP { get; set; }
        public dynamic S_RET_FRM_BAGG_TO_GSSP { get; set; }
        public dynamic S_PSSP_RECYCLE_QTY { get; set; }
        public dynamic S_GSSP_RECYCLE_QTY { get; set; }
        public dynamic S_BALL_MILL_HR { get; set; }
        public dynamic S_NG_IMPORTF_UNIT1 { get; set; }
        public dynamic S_WATER_BALL_MILL_READ_FINAL { get; set; }
        public dynamic S_WATER_CONSP_BALL_MILL { get; set; }
        public dynamic S_WATER_LSSP_READ_FINAL { get; set; }
        public dynamic S_WATER_CONSP_LSSP { get; set; }
        public dynamic S_WATER_GSSP_READ_FINAL { get; set; }
        public dynamic S_WATER_CONSP_GSSP { get; set; }
        public dynamic S_WATER_PROCESS_CONSP { get; set; }
        public dynamic S_WATER_DRINK_CONSP { get; set; }
        public dynamic S_ROCK_NAUR_LOSS { get; set; }
        public dynamic S_ROCK_JORD_LOSS { get; set; }
        public dynamic S_ROCK_EGYP_LOSS { get; set; }
        public dynamic S_ROCK_MORO_LOSS { get; set; }
        public dynamic S_ROCK_RSMM_LOSS { get; set; }
        public dynamic S_ROCK_PHOS_PUR_INV_EGYP3 { get; set; }
        public dynamic S_ROCK_PHOS_OP_BAL_EGYP3 { get; set; }
        public dynamic S_ROCK_PHOS_RECEIPT_EGYP3 { get; set; }
        public dynamic S_ROCK_PHOS_CONSP_EGYP3 { get; set; }
        public dynamic S_ROCK_PHOS_CLG_BAL_EGYP3 { get; set; }
        public dynamic S_ROCK_PHOS_P2O5_PER_EGYP3 { get; set; }
        public dynamic S_ROCK_EGYP3_LOSS { get; set; }
        public dynamic S_FILLER_RECEIPT_ASH { get; set; }
        public dynamic S_FILLER_CONSP_PSSP_ASH { get; set; }
        public dynamic S_FILLER_CONSP_GSSP_ASH { get; set; }
        public dynamic S_FILLER_CLG_BAL_ASH { get; set; }
        public dynamic S_FILLER_RECEIPT_TOT { get; set; }
        public dynamic S_FILLER_CONSP_PSSP_TOT { get; set; }
        public dynamic S_FILLER_CONSP_GSSP_TOT { get; set; }
        public dynamic S_FILLER_CLG_BAL_TOT { get; set; }
        public dynamic S_FILLER_OP_BALANCE_ASH { get; set; }
        public dynamic S_FILLER_OP_BALANCE_TOT { get; set; }
        public dynamic S_ROCK_PHOS_PUR_INV_RSMM3 { get; set; }
        public dynamic S_ROCK_PHOS_OP_BAL_RSMM3 { get; set; }
        public dynamic S_ROCK_PHOS_RECEIPT_RSMM3 { get; set; }
        public dynamic S_ROCK_PHOS_CONSP_RSMM3 { get; set; }
        public dynamic S_ROCK_PHOS_CLG_BAL_RSMM3 { get; set; }
        public dynamic S_ROCK_PHOS_P2O5_PER_RSMM3 { get; set; }
        public dynamic S_ROCK_RSMM3_LOSS { get; set; }
        public dynamic S_LOSS_QTY_LOOSE_SSP { get; set; }
        public dynamic S_CLG_BAL_SSP_PSSP { get; set; }
        public dynamic S_CLG_BAL_UPH_PSSP { get; set; }
        public dynamic S_CLG_BAL_SSP_GSSP { get; set; }
        public dynamic S_CLG_BAL_UPH_GSSP { get; set; }
        public dynamic S_DISP_ROAD_PSSP_UPH { get; set; }
        public dynamic S_DISP_ROAD_GSSP_UPH { get; set; }
        public dynamic S_ROCK_RSMM_GAIN { get; set; }
        public dynamic S_ROCK_JORD_GAIN { get; set; }
        public dynamic S_ROCK_EGYP_GAIN { get; set; }
        public dynamic S_ROCK_MORO_GAIN { get; set; }
        public dynamic S_ROCK_NAUR_GAIN { get; set; }
        public dynamic S_ROCK_EGYP3_GAIN { get; set; }
        public dynamic S_ROCK_RSMM3_GAIN { get; set; }
        public dynamic S_FILLER_LOSS_QTY_GYP { get; set; }
        public dynamic S_FILLER_LOSS_QTY_ASH { get; set; }
        public dynamic S_FILLER_LOSS_QTY_TOT { get; set; }

        // PRV
        public string PRV_S_TRANS_DATE { get; set; }
        public dynamic PRV_S_SULP_OP_BALANCE { get; set; }
        public dynamic PRV_S_SULP_RECEIPT { get; set; }
        public dynamic PRV_S_SULP_CONSP_INIT_READ { get; set; }
        public dynamic PRV_S_SULP_CONSP_FINAL_READ { get; set; }
        public dynamic PRV_S_SULP_CONSP_FINAL { get; set; }
        public dynamic PRV_S_SULP_CLG_BAL { get; set; }
        public dynamic PRV_S_ROCK_PHOS_PUR_INV_RSMM { get; set; }
        public dynamic PRV_S_ROCK_PHOS_OP_BAL_RSMM { get; set; }
        public dynamic PRV_S_ROCK_PHOS_RECEIPT_RSMM { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CONSP_RSMM { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CLG_BAL_RSMM { get; set; }
        public dynamic PRV_S_ROCK_PHOS_P2O5_PER_RSMM { get; set; }
        public dynamic PRV_S_ROCK_PHOS_PUR_INV_JORD { get; set; }
        public dynamic PRV_S_ROCK_PHOS_OP_BAL_JORD { get; set; }
        public dynamic PRV_S_ROCK_PHOS_RECEIPT_JORD { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CONSP_JORD { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CLG_BAL_JORD { get; set; }
        public dynamic PRV_S_ROCK_PHOS_P2O5_PER_JORD { get; set; }
        public dynamic PRV_S_ROCK_PHOS_PUR_INV_EGYP { get; set; }
        public dynamic PRV_S_ROCK_PHOS_OP_BAL_EGYP { get; set; }
        public dynamic PRV_S_ROCK_PHOS_RECEIPT_EGYP { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CONSP_EGYP { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CLG_BAL_EGYP { get; set; }
        public dynamic PRV_S_ROCK_PHOS_P2O5_PER_EGYP { get; set; }
        public dynamic PRV_S_ROCK_PHOS_PUR_INV_MORO { get; set; }
        public dynamic PRV_S_ROCK_PHOS_OP_BAL_MORO { get; set; }
        public dynamic PRV_S_ROCK_PHOS_RECEIPT_MORO { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CONSP_MORO { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CLG_BAL_MORO { get; set; }
        public dynamic PRV_S_ROCK_PHOS_P2O5_PER_MORO { get; set; }
        public dynamic PRV_S_ROCK_PHOS_PUR_INV_NAUR { get; set; }
        public dynamic PRV_S_ROCK_PHOS_OP_BAL_NAUR { get; set; }
        public dynamic PRV_S_ROCK_PHOS_RECEIPT_NAUR { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CONSP_NAUR { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CLG_BAL_NAUR { get; set; }
        public dynamic PRV_S_ROCK_PHOS_P2O5_PER_NAUR { get; set; }
        public dynamic PRV_S_FILLER_OP_BALANCE { get; set; }
        public dynamic PRV_S_FILLER_RECEIPT { get; set; }
        public dynamic PRV_S_FILLER_CONSP_PSSP { get; set; }
        public dynamic PRV_S_FILLER_CONSP_GSSP { get; set; }
        public dynamic PRV_S_FILLER_CLG_BAL { get; set; }
        public dynamic PRV_S_OP_BAL_LOOSE_SSP { get; set; }
        public dynamic PRV_S_PRODUCTION_LOOSE_SSP { get; set; }
        public dynamic PRV_S_CONSP_PSSP_LOOSE_SSP { get; set; }
        public dynamic PRV_S_CONSP_GSSP_LOOSE_SSP { get; set; }
        public dynamic PRV_S_CLG_BAL_LOOSE_SSP { get; set; }
        public dynamic PRV_S_STREAM_HOUR_LOOSE_SSP { get; set; }
        public dynamic PRV_S_OP_BAL_POWDER_SSP { get; set; }
        public dynamic PRV_S_PRODUCTION_POWDER_SSP { get; set; }
        public dynamic PRV_S_DISP_PSSP_RAIL_POWDER_SSP { get; set; }
        public dynamic PRV_S_DISP_PSSP_ROAD_POWDER_SSP { get; set; }
        public dynamic PRV_S_DISP_PSSP_TOT_POWDER_SSP { get; set; }
        public dynamic PRV_S_CLG_BAL_POWDER_SSP { get; set; }
        public dynamic PRV_S_STREAM_HOUR_POWDER_SSP { get; set; }
        public dynamic PRV_S_OP_BAL_GRANU_SSP { get; set; }
        public dynamic PRV_S_PRODUCTION_GRANU_SSP_A { get; set; }
        public dynamic PRV_S_PRODUCTION_GRANU_SSP_B { get; set; }
        public dynamic PRV_S_DISP_GSSP_RAIL_GRANU_SSP { get; set; }
        public dynamic PRV_S_DISP_GSSP_ROAD_GRANU_SSP { get; set; }
        public dynamic PRV_S_DISP_GSSP_TOT_GRANU_SSP { get; set; }
        public dynamic PRV_S_CLG_BAL_GRANU_SSP { get; set; }
        public dynamic PRV_S_STREAM_HOUR_GRANU_SSP_A { get; set; }
        public dynamic PRV_S_STREAM_HOUR_GRANU_SSP_B { get; set; }
        public dynamic PRV_S_POWER_LOOSE_SSP_INIT_READ { get; set; }
        public dynamic PRV_S_POWER_LOOSE_SSP_FINAL_READ { get; set; }
        public dynamic PRV_S_POWER_LOOSE_SSP_DIFF_READ { get; set; }
        public dynamic PRV_S_POWER_GSSP_INIT_READ { get; set; }
        public dynamic PRV_S_POWER_GSSP_FINAL_READ { get; set; }
        public dynamic PRV_S_POWER_GSSP_DIFF_READ { get; set; }
        public dynamic PRV_S_POWER_OWN_LSE_SSP_INIT_READ { get; set; }
        public dynamic PRV_S_POWER_OWN_LSE_SSP_FINAL_READ { get; set; }
        public dynamic PRV_S_POWER_OWN_LSE_SSP_DIFF_READ { get; set; }
        public dynamic PRV_S_POWER_OWN_GSSP_INIT_READ { get; set; }
        public dynamic PRV_S_POWER_OWN_GSSP_FINAL_READ { get; set; }
        public dynamic PRV_S_POWER_OWN_GPSSP_DIFF_READ { get; set; }
        public dynamic PRV_S_NG_CONSP_READ_INIT { get; set; }
        public dynamic PRV_S_NG_CONSP_READ_FINAL { get; set; }
        public dynamic PRV_S_NG_CONSP_READ_DIFF { get; set; }
        public dynamic PRV_S_NG_CONSP_LSSP { get; set; }
        public dynamic PRV_S_NG_CONSP_GSSP { get; set; }
        public dynamic PRV_S_WATER_CONSP_READ_INIT { get; set; }
        public dynamic PRV_S_WATER_CONSP_READ_FINAL { get; set; }
        public dynamic PRV_S_WATER_CONSP_READ_DIFF { get; set; }
        public dynamic PRV_S_BAG_OP_BAL_PSSP { get; set; }
        public dynamic PRV_S_BAG_RECEIPT_PSSP { get; set; }
        public dynamic PRV_S_BAG_CONSP_PSSP { get; set; }
        public dynamic PRV_S_BAG_CLG_PSSP { get; set; }
        public dynamic PRV_S_BAG_OP_BAL_GSSP { get; set; }
        public dynamic PRV_S_BAG_RECEIPT_GSSP { get; set; }
        public dynamic PRV_S_BAG_CONSP_GSSP { get; set; }
        public dynamic PRV_S_BAG_CLG_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_DAMAGED_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_RAPTURE_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_DAMAGED_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_RAPTURE_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_RECD_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_RECD_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_TESTING_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_TESTING_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_MARKT_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_MARKT_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_STND_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_STND_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_STOCK_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_STOCK_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_STOCK_ADJ_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_STOCK_ADJ_GSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_SOUND_PSSP { get; set; }
        public dynamic PRV_S_EMPTY_BAG_SOUND_GSSP { get; set; }
        public dynamic PRV_S_DIRECT_LOAD_ROAD_PSSP { get; set; }
        public dynamic PRV_S_DIRECT_LOAD_ROAD_GSSP { get; set; }
        public dynamic PRV_S_STACK_LOAD_ROAD_PSSP { get; set; }
        public dynamic PRV_S_STACK_LOAD_ROAD_GSSP { get; set; }
        public dynamic PRV_S_PSSP_MAT_SHT_TO_SSP { get; set; }
        public dynamic PRV_S_GSSP_MAT_SHT_TO_SSP { get; set; }
        public dynamic PRV_S_RET_FRM_BAGG_TO_PSSP { get; set; }
        public dynamic PRV_S_RET_FRM_BAGG_TO_GSSP { get; set; }
        public dynamic PRV_S_PSSP_RECYCLE_QTY { get; set; }
        public dynamic PRV_S_GSSP_RECYCLE_QTY { get; set; }
        public dynamic PRV_S_BALL_MILL_HR { get; set; }
        public dynamic PRV_S_NG_IMPORTF_UNIT1 { get; set; }
        public dynamic PRV_S_WATER_BALL_MILL_READ_FINAL { get; set; }
        public dynamic PRV_S_WATER_CONSP_BALL_MILL { get; set; }
        public dynamic PRV_S_WATER_LSSP_READ_FINAL { get; set; }
        public dynamic PRV_S_WATER_CONSP_LSSP { get; set; }
        public dynamic PRV_S_WATER_GSSP_READ_FINAL { get; set; }
        public dynamic PRV_S_WATER_CONSP_GSSP { get; set; }
        public dynamic PRV_S_WATER_PROCESS_CONSP { get; set; }
        public dynamic PRV_S_WATER_DRINK_CONSP { get; set; }
        public dynamic PRV_S_ROCK_NAUR_LOSS { get; set; }
        public dynamic PRV_S_ROCK_JORD_LOSS { get; set; }
        public dynamic PRV_S_ROCK_EGYP_LOSS { get; set; }
        public dynamic PRV_S_ROCK_MORO_LOSS { get; set; }
        public dynamic PRV_S_ROCK_RSMM_LOSS { get; set; }
        public dynamic PRV_S_ROCK_PHOS_PUR_INV_EGYP3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_OP_BAL_EGYP3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_RECEIPT_EGYP3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CONSP_EGYP3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CLG_BAL_EGYP3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_P2O5_PER_EGYP3 { get; set; }
        public dynamic PRV_S_ROCK_EGYP3_LOSS { get; set; }
        public dynamic PRV_S_FILLER_RECEIPT_ASH { get; set; }
        public dynamic PRV_S_FILLER_CONSP_PSSP_ASH { get; set; }
        public dynamic PRV_S_FILLER_CONSP_GSSP_ASH { get; set; }
        public dynamic PRV_S_FILLER_CLG_BAL_ASH { get; set; }
        public dynamic PRV_S_FILLER_RECEIPT_TOT { get; set; }
        public dynamic PRV_S_FILLER_CONSP_PSSP_TOT { get; set; }
        public dynamic PRV_S_FILLER_CONSP_GSSP_TOT { get; set; }
        public dynamic PRV_S_FILLER_CLG_BAL_TOT { get; set; }
        public dynamic PRV_S_FILLER_OP_BALANCE_ASH { get; set; }
        public dynamic PRV_S_FILLER_OP_BALANCE_TOT { get; set; }
        public dynamic PRV_S_ROCK_PHOS_PUR_INV_RSMM3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_OP_BAL_RSMM3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_RECEIPT_RSMM3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CONSP_RSMM3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_CLG_BAL_RSMM3 { get; set; }
        public dynamic PRV_S_ROCK_PHOS_P2O5_PER_RSMM3 { get; set; }
        public dynamic PRV_S_ROCK_RSMM3_LOSS { get; set; }
        public dynamic PRV_S_LOSS_QTY_LOOSE_SSP { get; set; }
        public dynamic PRV_S_CLG_BAL_SSP_PSSP { get; set; }
        public dynamic PRV_S_CLG_BAL_UPH_PSSP { get; set; }
        public dynamic PRV_S_CLG_BAL_SSP_GSSP { get; set; }
        public dynamic PRV_S_CLG_BAL_UPH_GSSP { get; set; }
        public dynamic PRV_S_DISP_ROAD_PSSP_UPH { get; set; }
        public dynamic PRV_S_DISP_ROAD_GSSP_UPH { get; set; }
        public dynamic PRV_S_ROCK_RSMM_GAIN { get; set; }
        public dynamic PRV_S_ROCK_JORD_GAIN { get; set; }
        public dynamic PRV_S_ROCK_EGYP_GAIN { get; set; }
        public dynamic PRV_S_ROCK_MORO_GAIN { get; set; }
        public dynamic PRV_S_ROCK_NAUR_GAIN { get; set; }
        public dynamic PRV_S_ROCK_EGYP3_GAIN { get; set; }
        public dynamic PRV_S_ROCK_RSMM3_GAIN { get; set; }
        public dynamic PRV_S_FILLER_LOSS_QTY_GYP { get; set; }
        public dynamic PRV_S_FILLER_LOSS_QTY_ASH { get; set; }
        public dynamic PRV_S_FILLER_LOSS_QTY_TOT { get; set; }

        // DV
        public dynamic DIS_S_SULP_CLG_BAL { get; set; }
        public dynamic TXT_ROCK_PHOS_OP_BAL_RSMM { get; set; }
        public dynamic TXT_ROCK_PHOS_OP_BAL_JORD { get; set; }
        public dynamic TXT_ROCK_PHOS_OP_BAL_EGYP { get; set; }
        public dynamic TXT_ROCK_PHOS_OP_BAL_MORO { get; set; }
        public dynamic TXT_ROCK_PHOS_OP_BAL_NAUR { get; set; }
        public dynamic TXT_ROCK_PHOS_OP_BAL_EGYP3 { get; set; }
        public dynamic TXT_ROCK_PHOS_OP_BAL_RSMM3 { get; set; }
        public dynamic TXT_FILLER_OP_BALANCE { get; set; }
        public dynamic TXT_FILLER_OP_BALANCE_ASH { get; set; }
        public dynamic TXT_FILLER_OP_BALANCE_TOT { get; set; }
        public dynamic TXT_OP_BAL_LOOSE_SSP { get; set; }
        public dynamic TXT_RTN_RECYCLE_PSSP { get; set; }
        public dynamic TXT_RTN_RECYCLE_GSSP { get; set; }
        public dynamic TXT_OP_BAL_POWDER_SSP { get; set; }
        public dynamic TXT_OP_BAL_SSP_PSSP { get; set; }
        public dynamic TXT_OP_BAL_UPH_PSSP { get; set; }
        public dynamic DIS_S_BAG_QTY_PSSP { get; set; }
        public dynamic TXT_OP_BAL_GRANU_SSP { get; set; }
        public dynamic TXT_OP_BAL_SSP_GSSP { get; set; }
        public dynamic TXT_OP_BAL_UPH_GSSP { get; set; }
        public dynamic DIS_S_BAG_QTY_GSSP { get; set; }
        public decimal TXT_BAG_OP_BAL_PSSP { get; set; }
        public decimal TXT_BAG_OP_BAL_GSSP { get; set; }
        public dynamic G_LSSP_PROD_FACTOR { get; set; }
        public dynamic G_GSSP_LOSS_FACTORE { get; set; }
        public dynamic DIS_E1_PUR_PWR_CONSP_SSP { get; set; }
        // public dynamic S_SULP_CONSP_FINAL { get; set; }
    }
}
